load("//rules:python.bzl", "py_test")

[
    py_test(name = lib)
    for lib in [
        "base",
        "file",
        "image",
        "json",
        "multipart",
        "numpy",
        "text",
    ]
]
