from enum import Enum

class ParameterFormat(Enum):
    Float = ...
    @property
    def size(self) -> int: ...

def compute_effective_axis_dimension(
    dimension: int, fixed_dimension: int, num_token_to_add: int = ...
) -> int: ...
def compute_serialized_parameters_size(
    num_parameters: int, dtype: ParameterFormat
) -> int: ...
