{
 "title": "bentoml-dashboard-docker-swarm",
 "time": { "from": "2021-06-14T13:02:00.364Z", "to": "2021-06-14T13:10:09.589Z" },
 "panels": [
  {
   "title": "request_in_progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "BENTOML_FashionMnistTensorflow_request_in_progress"
    }
   ]
  },
  {
   "title": "mb_request_duration",
   "type": "graph",
   "description": "microbatch request duration seconds",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.85, sum by(le) (rate(BENTOML_FashionMnistTensorflow_mb_request_duration_seconds_bucket[5m])))"
    }
   ]
  },
  {
   "title": "mb_request_total",
   "type": "graph",
   "description": "microbatch request total",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(BENTOML_FashionMnistTensorflow_mb_request_total[5m])"
    }
   ]
  },
  {
   "title": "request_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(BENTOML_FashionMnistTensorflow_request_total{endpoint=~\"/|/healthz|/metadata|/metrics|/predict\"}[5m])"
    }
   ]
  }
 ]
}