{
 "title": "bentoml-dashboard-kubernetes",
 "time": { "from": "2021-06-14T14:05:50.137Z", "to": "2021-06-14T14:14:10.627Z" },
 "panels": [
  {
   "title": "request_total",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(BENTOML_FashionMnistTensorflow_request_total{exported_endpoint=~\"/|/healthz|/metadata|/metrics|/predict\"}[5m])"
    }
   ]
  },
  {
   "title": "mb_request_duration",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 7, "x": 17, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(BENTOML_FashionMnistTensorflow_mb_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "request_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.65, sum(rate(BENTOML_FashionMnistTensorflow_request_duration_seconds_bucket{exported_endpoint=~\"/|/feedback|/healthz|/metadata|/metrics|/predict\"}[5m])) by (le))"
    }
   ]
  },
  {
   "title": "prom_scrape_duration_seconds",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(scrape_duration_seconds{job=\"bentoml-service\"}[10m])"
    }
   ]
  },
  {
   "title": "mb_batch_size_sum",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "rate(BENTOML_FashionMnistTensorflow_mb_batch_size_sum{endpoint=\"predict\"}[5m])"
    }
   ]
  }
 ]
}