{
 "title": "bentoml-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "histogram_mb_request_duration",
   "type": "graph",
   "description": "histogram for microbatch request durations",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(BENTOML_TensorflowService_mb_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "histogram_request_duration",
   "type": "graph",
   "description": "histogram of request duration",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(BENTOML_TensorflowService_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "mb_request_total",
   "type": "graph",
   "description": "microbatch total requests",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(BENTOML_TensorflowService_request_total[5m])) by (endpoint)"
    }
   ]
  }
 ]
}