from ..file_utils import add_end_docstrings, is_torch_available
from .base import PIPELINE_INIT_ARGS, ArgumentHandler, Pipeline

if is_torch_available(): ...

class TableQuestionAnsweringArgumentHandler(ArgumentHandler):
    def __call__(
        self, table=..., query=..., sequential=..., padding=..., truncation=...
    ): ...

@add_end_docstrings(PIPELINE_INIT_ARGS)
class TableQuestionAnsweringPipeline(Pipeline):
    default_input_names = ...
    def __init__(self, args_parser=..., *args, **kwargs) -> None: ...
    def batch_inference(self, **inputs): ...
    def sequential_inference(self, **inputs): ...
