{
 "title": "bentoml_service",
 "description": "BentoML metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "microbatch_total_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "BENTOML_PytorchService_mb_requestmb_duration_seconds_sum"
    }
   ]
  },
  {
   "title": "total_request",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(BENTOML_PytorchService_request_total[5m])"
    }
   ]
  },
  {
   "title": "microbatch_request_durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(BENTOML_PytorchService_mb_requestmb_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "request_durations",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(BENTOML_PytorchService_request_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}