from typing import Iterable, Sequence
import numpy as np

def validate_args(fname, args, max_fname_arg_count, compat_args): ...
def validate_kwargs(fname, kwargs, compat_args): ...
def validate_args_and_kwargs(fname, args, kwargs, max_fname_arg_count, compat_args): ...
def validate_bool_kwarg(value, arg_name, none_allowed=..., int_allowed=...): ...
def validate_axis_style_args(data, args, kwargs, arg_name, method_name): ...
def validate_fillna_kwargs(value, method, validate_scalar_dict_value=...): ...
def validate_percentile(q: float | Iterable[float]) -> np.ndarray: ...
