from ctypes import _SimpleCData
from typing import List, Type

__all__: List[str]
c_intp: Type[_SimpleCData[int]]

def load_library(libname, loader_path): ...
def ndpointer(dtype=..., ndim=..., shape=..., flags=...): ...
def as_ctypes(obj): ...
def as_array(obj, shape=...): ...
def as_ctypes_type(dtype): ...
