"""
.. deprecated:: 1.20

*This module is deprecated.  Instead of importing functions from*
``numpy.dual``, *the functions should be imported directly from NumPy
or SciPy*.

Aliases for functions which may be accelerated by SciPy.

SciPy_ can be built to use accelerated or otherwise improved libraries
for FFTs, linear algebra, and special functions. This module allows
developers to transparently support these accelerated functions when
SciPy is available but still support users who have only installed
NumPy.

.. _SciPy : https://www.scipy.org

"""
__all__ = [
    "fft",
    "ifft",
    "fftn",
    "ifftn",
    "fft2",
    "ifft2",
    "norm",
    "inv",
    "svd",
    "solve",
    "det",
    "eig",
    "eigvals",
    "eigh",
    "eigvalsh",
    "lstsq",
    "pinv",
    "cholesky",
    "i0",
]
fft = ...
ifft = ...
fftn = ...
ifftn = ...
fft2 = ...
ifft2 = ...
norm = ...
inv = ...
svd = ...
solve = ...
det = ...
eig = ...
eigvals = ...
eigh = ...
eigvalsh = ...
lstsq = ...
pinv = ...
cholesky = ...
_restore_dict = ...

def register_func(name, func): ...
def restore_func(name): ...
def restore_all(): ...
