import contextlib
import ctypes
import os
import platform
import subprocess
import time
import warnings
from ctypes import c_size_t, c_wchar, c_wchar_p, get_errno, sizeof
from shutil import which

__version__ = ...
HAS_DISPLAY = ...
EXCEPT_MSG = ...
ENCODING = ...
if platform.system() == "Windows":
    WHICH_CMD = ...
else:
    WHICH_CMD = ...

class PyperclipException(RuntimeError): ...

class PyperclipWindowsException(PyperclipException):
    def __init__(self, message) -> None: ...

def init_osx_pbcopy_clipboard(): ...
def init_osx_pyobjc_clipboard(): ...
def init_qt_clipboard(): ...
def init_xclip_clipboard(): ...
def init_xsel_clipboard(): ...
def init_klipper_clipboard(): ...
def init_dev_clipboard_clipboard(): ...
def init_no_clipboard():
    class ClipboardUnavailable: ...

class CheckedCall:
    def __init__(self, f) -> None: ...
    def __call__(self, *args): ...
    def __setattr__(self, key, value): ...

def init_windows_clipboard(): ...
def init_wsl_clipboard(): ...
def determine_clipboard(): ...
def set_clipboard(clipboard): ...
def lazy_load_stub_copy(text): ...
def lazy_load_stub_paste(): ...
def is_available() -> bool: ...

__all__ = ["copy", "paste", "set_clipboard", "determine_clipboard"]
clipboard_get = ...
clipboard_set = ...
