from typing import Literal

from .merger import Merger

DEFAULT_TYPE_SPECIFIC_MERGE_STRATEGIES: list[
    tuple[type, Literal["append", "merge", "union"]]
] = ...
always_merger: Merger = ...
merge_or_raise: Merger = ...
conservative_merger: Merger = ...
