scanner:
    diff_only: True
    linter: pycodestyle

pycodestyle:
    max-line-length: 88

    exclude: [ 'examples' ]

only_mention_files_with_errors: True

message:
    opened:
        header: "Hello @{name}! Thanks for opening this PR."
        footer: "Do see the [Hitchhiker's guide to code style](https://goo.gl/hqbW4r)"
    updated:
        header: "Hello @{name}, Thanks for updating this PR."
        footer: ""
    no_errors: "There are currently no PEP 8 issues detected in this PR. Cheers! :beers:"
        
