# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_checkout:
      - git fetch --unshallow
    pre_install:
      - git update-index --assume-unchanged docs/source/conf.py

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - requirements: requirements/docs-requirements.txt
    - method: pip
      path: .

formats:
  - epub
  - pdf
