from .configuration_auto import replace_list_option_in_docstrings

FEATURE_EXTRACTOR_MAPPING = ...

def feature_extractor_class_from_name(class_name: str): ...

class AutoFeatureExtractor:
    def __init__(self) -> None: ...
    @classmethod
    @replace_list_option_in_docstrings(FEATURE_EXTRACTOR_MAPPING)
    def from_pretrained(cls, pretrained_model_name_or_path, **kwargs): ...
