

from .auto_factory import _BaseAutoModelClass

""" Auto Model class. """
logger = ...
FLAX_MODEL_MAPPING = ...
FLAX_MODEL_FOR_PRETRAINING_MAPPING = ...
FLAX_MODEL_FOR_MASKED_LM_MAPPING = ...
FLAX_MODEL_FOR_SEQ_TO_SEQ_CAUSAL_LM_MAPPING = ...
FLAX_MODEL_FOR_IMAGE_CLASSIFICATION_MAPPING = ...
FLAX_MODEL_FOR_CAUSAL_LM_MAPPING = ...
FLAX_MODEL_FOR_SEQUENCE_CLASSIFICATION_MAPPING = ...
FLAX_MODEL_FOR_QUESTION_ANSWERING_MAPPING = ...
FLAX_MODEL_FOR_TOKEN_CLASSIFICATION_MAPPING = ...
FLAX_MODEL_FOR_MULTIPLE_CHOICE_MAPPING = ...
FLAX_MODEL_FOR_NEXT_SENTENCE_PREDICTION_MAPPING = ...
class FlaxAutoModel(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModel = ...
class FlaxAutoModelForPreTraining(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForPreTraining = ...
class FlaxAutoModelForCausalLM(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForCausalLM = ...
class FlaxAutoModelForMaskedLM(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForMaskedLM = ...
class FlaxAutoModelForSeq2SeqLM(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForSeq2SeqLM = ...
class FlaxAutoModelForSequenceClassification(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForSequenceClassification = ...
class FlaxAutoModelForQuestionAnswering(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForQuestionAnswering = ...
class FlaxAutoModelForTokenClassification(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForTokenClassification = ...
class FlaxAutoModelForMultipleChoice(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForMultipleChoice = ...
class FlaxAutoModelForNextSentencePrediction(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForNextSentencePrediction = ...
class FlaxAutoModelForImageClassification(_BaseAutoModelClass):
    _model_mapping = ...


FlaxAutoModelForImageClassification = ...
