---
### Tensorflow Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bentoml-service
  name: bentoml-service
  namespace: bentoml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bentoml-service
  template:
    metadata:
      labels:
        app: bentoml-service
    spec:
      containers:
        - image: bentoml/fashion-mnist-classifier:latest
          imagePullPolicy: IfNotPresent
          name: bentoml-service
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30

---
### Tensorflow Service
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bentoml-service
  name: bentoml-service
  namespace: bentoml
spec:
  externalTrafficPolicy: Cluster
  ports:
    - name: predict
      nodePort: 32610
      port: 5000
      protocol: TCP
      targetPort: 5000
  selector:
    app: bentoml-service
  sessionAffinity: None
  type: NodePort

---
### Tensorflow ServiceMonitor
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bentoml-service
  namespace: bentoml
spec:
  selector:
    matchLabels:
      app: bentoml-service
  endpoints:
  - port: predict