#!/usr/bin/env bash

set -e
GIT_ROOT=$(git rev-parse --show-toplevel)
cd "$GIT_ROOT" || exit 1

install_qemu() {
	ARGS=(--rm --privileged)
	if [[ -f "/.dockerenv" ]]; then
		docker run "${ARGS[@]}" multiarch/qemu-user-static:register
	else
		if [[ "$(uname)" == "Darwin" ]]; then
			docker run "${ARGS[@]}" tonistiigi/binfmt --install all
		else
			docker run "${ARGS[@]}" aptman/qus -s -l -- -p arm i386 mips64 mips64el ppc64le s390x aarch64 x86_64
		fi
	fi
	exit 0
}

usage() {
	cat <<-EOF
		Usage: buildx-utils [--help][--qemu][--platforms]

			Some helpers functions for interacting with buildx

			-h|--help|-help:
				display this usage.
			-q|--qemu|-qemu:
				install qemu to support building on multiple architecture.
			-p|--platforms|-platforms:
				run platforms check, display variables for \`uname -m\`.
	EOF
}

main() {
	while [[ $# -gt 0 ]]; do
		case $1 in
		-h | -help | --help)
			usage
			exit
			;;
		-q | -qemu | --qemu)
			install_qemu
			;;
		-p | -platforms | --platforms)
			docker buildx bake -f ./scripts/docker/docker-bake.hcl platforms --progress=plain
			exit 0
			;;
		-*)
			echo "Unknown option $1"
			exit 1
			;;
		*)
			shift
			;;
		esac
	done
}

main "$@"

