# If not running interactively, don't do anything
[ -z "$PS1" ] && return

export PS1="\[\e[31m\]bentoml\[\e[m\] \[\e[33m\]\w\[\e[m\] » "
export TERM=xterm-256color

# alias
alias grep="grep --color=auto"
alias la="ls -rthla --color=auto"

echo -e "\e[0;33m"
if [[ $EUID -eq 0 ]]; then
  cat <<WARN
WARNING: You are running this container as root, which can cause new files in
mounted volumes to be created as the root user on your host machine.

To avoid this, run the container by specifying your user's userid:

$ docker run -u \$(id -u):\$(id -g) args...
WARN
fi
echo -e "\e[m"