"""
This type stub file was generated by pyright.
"""

from circus import ArbiterHandler as _ArbiterHandler

class ArbiterHandler(_ArbiterHandler):
    def __call__(self, watchers, **kwargs): # -> ThreadedArbiter | Arbiter:
        ...
    


get_arbiter = ...
