#!/bin/bash

set -e

pushd .. >/dev/null

! [[ -d "thirdparty" ]] && mkdir thirdparty

pushd thirdparty >/dev/null
! [[ -d "protobuf" ]] && git clone --depth 1 https://github.com/protocolbuffers/protobuf.git
popd

if ! $(which protoc-gen-grpc-swift &>/dev/null); then
	echo "protoc-gen-grpc-swift is missing. Make sure to compile it first and add it to your PATH."
	exit 1
fi

protoc -I . -I ./thirdparty/protobuf/src \
	--swift_out=swift/Sources --swift_opt=Visibility=Public \
	--grpc-swift_out=swift/Sources --grpc-swift_opt=Visibility=Public \
	bentoml/grpc/v1alpha1/service.proto

popd >/dev/null

swift run BentoServiceClient
