"""
This type stub file was generated by pyright.
"""

class Redirector:
    class Handler:
        def __init__(self, redirector, name, process, pipe) -> None:
            ...
        
        def __call__(self, fd, events):
            ...
        
    
    
    def __init__(self, stdout_redirect, stderr_redirect, buffer=..., loop=...) -> None:
        ...
    
    def start(self): # -> int:
        ...
    
    def stop(self): # -> int:
        ...
    
    @staticmethod
    def get_process_pipes(process): # -> Generator[tuple[Literal['stdout'], Unknown] | tuple[Literal['stderr'], Unknown], None, None]:
        ...
    
    def add_redirections(self, process): # -> None:
        ...
    
    def remove_fd(self, fd): # -> None:
        ...
    
    def remove_redirections(self, process):
        ...
    
    def change_stream(self, stream_name, redirect_writer): # -> None:
        ...
    
    def get_stream(self, stream_name): # -> Unknown | None:
        ...
    


