import abc

_ne_builtins = ...

class NumExprClobberingError(NameError): ...

class AbstractEngine(metaclass=abc.ABCMeta):
    has_neg_frac = ...
    def __init__(self, expr) -> None: ...
    def convert(self) -> str: ...
    def evaluate(self) -> object: ...

class NumExprEngine(AbstractEngine):
    has_neg_frac = ...

class PythonEngine(AbstractEngine):
    has_neg_frac = ...
    def evaluate(self): ...

ENGINES: dict[str, type[AbstractEngine]] = ...
