from pandas._typing import FuncType
from pandas.core.computation.check import NUMEXPR_INSTALLED

if NUMEXPR_INSTALLED: ...
_TEST_MODE: bool | None = ...
_TEST_RESULT: list[bool] = ...
USE_NUMEXPR = ...
_evaluate: FuncType | None = ...
_where: FuncType | None = ...
_ALLOWED_DTYPES = ...
_MIN_ELEMENTS = ...

def set_use_numexpr(v=...): ...
def set_numexpr_threads(n=...): ...

_op_str_mapping = ...
_BOOL_OP_UNSUPPORTED = ...

def evaluate(op, a, b, use_numexpr: bool = ...): ...
def where(cond, a, b, use_numexpr=...): ...
def set_test_mode(v: bool = ...) -> None: ...
def get_test_result() -> list[bool]: ...
