

from typing import TYPE_CHECKING

from ...file_utils import _LazyModule, is_torch_available, is_vision_available
from .configuration_deit import DEIT_PRETRAINED_CONFIG_ARCHIVE_MAP, DeiTConfig

_import_structure = ...
if is_vision_available():
    ...
if is_torch_available():
    ...
if TYPE_CHECKING:
    ...
else:
    ...
