import re
import numpy as np
from pandas.util.version import Version

_np_version = ...
_nlv = ...
np_version_under1p18 = ...
np_version_under1p19 = ...
np_version_under1p20 = ...
is_numpy_dev = ...
_min_numpy_ver = ...
if _nlv < Version(_min_numpy_ver): ...
_tz_regex = ...

def np_datetime64_compat(tstring: str, unit: str = ...): ...
def np_array_datetime64_compat(arr, dtype=...): ...

__all__ = ["np", "_np_version", "is_numpy_dev"]
