from collections.abc import Callable
from typing import Any
from typing import TypeAlias

_StringOrFunction: TypeAlias = str | Callable[..., Any]
STRATEGY_END: object = ...

class StrategyList:
    NAME: str | None = ...
    def __init__(
        self, strategy_list: _StringOrFunction | list[_StringOrFunction]
    ) -> None: ...
    @classmethod
    def _expand_strategy(cls, strategy: _StringOrFunction) -> _StringOrFunction: ...
    def __call__(self, *args: Any, **kwargs: Any) -> Any: ...
