from .core import StrategyList

class FallbackStrategies(StrategyList):
    NAME = ...
    @staticmethod
    def strategy_override(config, path, base, nxt): ...
    @staticmethod
    def strategy_use_existing(config, path, base, nxt): ...
