from .core import StrategyList

class ListStrategies(StrategyList):
    NAME = ...
    @staticmethod
    def strategy_override(config, path, base, nxt): ...
    @staticmethod
    def strategy_prepend(config, path, base, nxt): ...
    @staticmethod
    def strategy_append(config, path, base, nxt): ...
