from .core import StrategyList

class SetStrategies(StrategyList):
    NAME = ...
    @staticmethod
    def strategy_union(config, path, base, nxt): ...
    @staticmethod
    def strategy_intersect(config, path, base, nxt): ...
    @staticmethod
    def strategy_override(config, path, base, nxt): ...
