apiVersion: v1
kind: Service
metadata:
  name: bento-example
  namespace: default
  labels:
    name: bento-example
    app: bento-example

spec:
  ports:
    - port: 80 
      name: http
      protocol: TCP
      targetPort: 5000
  selector:
    name: bento-example
  type: NodePort
