class Message(email.message.Message):
    multiple_use_keys = ...
    def __new__(cls, orig: email.message.Message): ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __iter__(self): ...
    @property
    def json(self): ...
