__all__ = ["install", "NullFinder", "PyPy_repr", "Protocol"]

def install(cls): ...
def disable_stdlib_finder(): ...

class NullFinder:
    @staticmethod
    def find_spec(*args, **kwargs): ...
    find_module = ...

class PyPy_repr:
    affected = ...
    def __compat_repr__(self): ...
    if affected:
        __repr__ = ...
