from typing import Any
from pandas.core.base import PandasObject

class FrozenList(PandasObject, list):
    def union(self, other) -> FrozenList: ...
    def difference(self, other) -> FrozenList: ...
    __add__ = ...
    def __getitem__(self, n): ...
    def __radd__(self, other): ...
    def __eq__(self, other: Any) -> bool: ...
    __req__ = ...
    def __mul__(self, other): ...
    __imul__ = ...
    def __reduce__(self): ...
    def __hash__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    __setitem__ = ...
    __delitem__ = ...
    pop = ...
    remove = ...
