# BentoML will provide supports for CUDA 11.3 with CUDNN 8.2.0.53
ARG PYTHON_VERSION
ARG CUDA=11.3
ARG CUDNN_MAJOR_RELEASE=8
ARG BENTOML_VERSION=0.12.1

FROM nvidia/cuda:${CUDA}.0-cudnn${CUDNN_MAJOR_RELEASE}-runtime-ubuntu18.04 as builder
FROM bentoml/model-server:${BENTOML_VERSION}-slim-py${PYTHON_VERSION}
# CUDA need to redefine here since FROM resets all ARGs except default values, which are retained
ARG CUDA
ARG CUDNN=8.2.0
ARG LIB_DIR_PREFIX=x86_64-linux-gnu

# needed for string substitutions
SHELL ["/bin/bash", "-c"]

COPY --from=builder /usr/local/cuda-${CUDA}/ /usr/local/cuda-${CUDA}/
RUN ln -s /usr/local/cuda-${CUDA} /usr/local/cuda

COPY --from=builder /usr/lib/${LIB_DIR_PREFIX}/ /usr/lib/${LIB_DIR_PREFIX}/

# Make sure we use the virtualenv
ENV PATH /usr/local/cuda/bin:$PATH

ENV LD_LIBRARY_PATH /usr/local/cuda/lib64:/usr/include/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:$LD_LIBRARY_PATH

COPY bashrc /etc/bash.bashrc
RUN chmod a+rwx /etc/bash.bashrc