FROM continuumio/miniconda3:4.8.2-alpine

# Install all build dependencies and bash for user setup scripts
USER root
RUN apk update \
    && apk add --virtual build-dependencies \
        build-base \
        gcc \
        wget \
        git \
        linux-headers \
    && apk add \
        bash \
# Restore USER as set in base image
# https://github.com/ContinuumIO/docker-images/blob/2020_02_release/miniconda3/alpine/Dockerfile
USER 10151

ARG BENTOML_VERSION
ENV BENTOML_VERSION=$BENTOML_VERSION

# pre-install BentoML base dependencies
RUN sh --login -i -c "pip install bentoml==$BENTOML_VERSION"

COPY entrypoint.sh /usr/local/bin/

ENTRYPOINT [ "entrypoint.sh" ]
CMD ["bentoml", "serve-gunicorn", "/bento"]
