ARG PYTHON_VERSION
FROM python:${PYTHON_VERSION}-slim AS compile-image
RUN apt-get update
RUN apt-get install -y --no-install-recommends build-essential gcc

ARG BENTOML_VERSION
ENV BENTOML_VERSION=$BENTOML_VERSION

RUN python -m venv /opt/venv
# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

# pre-install BentoML requirements
RUN pip install bentoml==$BENTOML_VERSION
COPY entrypoint.sh .

# multi-stage build to shave dependency cost
FROM python:${PYTHON_VERSION}-slim AS build-image
COPY --from=compile-image /opt/venv /opt/venv
COPY --from=compile-image entrypoint.sh /usr/local/bin

# Make sure we use the virtualenv:
ENV PATH="/opt/venv/bin:$PATH"

ENTRYPOINT [ "entrypoint.sh" ]
CMD ["bentoml", "serve-gunicorn", "/bento"]