apiVersion: v2
name: YataiService
description: A Helm chart to deploy YataiService to K8s
type: application
version: 0.1.0
appVersion: 0.8.5
dependencies:
  - name: ingress-nginx
    version: ~2.11.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: ingress.enabled