INDENT = ...

def safe_repr(value): ...
def eq_repr(value, repr=...): ...
def uniq_stable(elems): ...
def fix_frame_records_filenames(records): ...
def format_records(records): ...
def format_exc(etype, evalue, etb, context=..., tb_offset=...): ...
def format_outer_frames(
    context=..., stack_start=..., stack_end=..., ignore_ipython=...
): ...
