class JoblibException(Exception):
    def __init__(self, *args) -> None: ...
    def __repr__(self): ...
    __str__ = ...

class TransportableException(JoblibException):
    def __init__(self, message, etype) -> None: ...
    def unwrap(self, context_message=...): ...

_exception_mapping = ...
