def disk_used(path): ...
def memstr_to_bytes(text): ...
def mkdirp(d): ...

RM_SUBDIRS_RETRY_TIME = ...
RM_SUBDIRS_N_RETRY = ...

def rm_subdirs(path, onerror=...): ...
def delete_folder(folder_path, onerror=..., allow_non_empty=...): ...
