full_argspec_fields = ...
full_argspec_type = ...

def get_func_code(func): ...
def get_func_name(func, resolv_alias=..., win_characters=...): ...
def filter_args(func, ignore_lst, args=..., kwargs=...): ...
def format_signature(func, *args, **kwargs): ...
