import pickle

Pickler = pickle._Pickler

class _ConsistentSet:
    def __init__(self, set_sequence) -> None: ...

class _MyHash:
    def __init__(self, *args) -> None: ...

class Hasher(Pickler):
    def __init__(self, hash_name=...) -> None: ...
    def hash(self, obj, return_digest=...): ...
    def save(self, obj): ...
    def memoize(self, obj): ...
    def save_global(self, obj, name=..., pack=...): ...
    dispatch = ...
    def save_set(self, set_items): ...

class NumpyHasher(Hasher):
    def __init__(self, hash_name=..., coerce_mmap=...) -> None: ...
    def save(self, obj): ...

def hash(obj, hash_name=..., coerce_mmap=...): ...
