def format_time(t): ...
def short_format_time(t): ...
def pformat(obj, indent=..., depth=...): ...

class Logger:
    def __init__(self, depth=...) -> None: ...
    def warn(self, msg): ...
    def debug(self, msg): ...
    def format(self, obj, indent=...): ...

class PrintTime:
    def __init__(self, logfile=..., logdir=...) -> None: ...
