from ..pattern import RegexPattern

_BYTES_ENCODING = ...

class GitWildMatchPatternError(ValueError): ...

class GitWildMatchPattern(RegexPattern):
    __slots__ = ...
    @classmethod
    def pattern_to_regex(
        cls, pattern: AnyStr
    ) -> Tuple[Optional[AnyStr], Optional[bool]]: ...
    @staticmethod
    def escape(s: AnyStr) -> AnyStr: ...

class GitIgnorePattern(GitWildMatchPattern):
    def __init__(self, *args, **kw) -> None: ...
    @classmethod
    def pattern_to_regex(cls, *args, **kw): ...
