import numpy as np

def build_field_sarray(dtindex: np.ndarray) -> np.ndarray: ...
def month_position_check(fields, weekdays) -> str | None: ...
def get_date_name_field(dtindex: np.ndarray, field: str, locale=...) -> np.ndarray: ...
def get_start_end_field(
    dtindex: np.ndarray, field: str, freqstr: str | None = ..., month_kw: int = ...
) -> np.ndarray: ...
def get_date_field(dtindex: np.ndarray, field: str) -> np.ndarray: ...
def get_timedelta_field(tdindex: np.ndarray, field: str) -> np.ndarray: ...
def isleapyear_arr(years: np.ndarray) -> np.ndarray: ...
def build_isocalendar_sarray(dtindex: np.ndarray) -> np.ndarray: ...
def get_locale_names(name_type: str, locale: object = ...): ...

class RoundTo:
    @property
    def MINUS_INFTY(self) -> int: ...
    @property
    def PLUS_INFTY(self) -> int: ...
    @property
    def NEAREST_HALF_EVEN(self) -> int: ...
    @property
    def NEAREST_HALF_PLUS_INFTY(self) -> int: ...
    @property
    def NEAREST_HALF_MINUS_INFTY(self) -> int: ...

def round_nsint64(values: np.ndarray, mode: RoundTo, nanos: int) -> np.ndarray: ...
