from datetime import datetime
import numpy as np
from pandas._libs.tslibs.offsets import BaseOffset

class DateParseError(ValueError): ...

def parse_datetime_string(
    date_string: str, dayfirst: bool = ..., yearfirst: bool = ..., **kwargs
) -> datetime: ...
def parse_time_string(
    arg: str,
    freq: BaseOffset | str | None = ...,
    dayfirst: bool | None = ...,
    yearfirst: bool | None = ...,
) -> tuple[datetime, str]: ...
def quarter_to_myear(year: int, quarter: int, freq: str) -> tuple[int, int]: ...
def try_parse_dates(
    values: np.ndarray, parser=..., dayfirst: bool = ..., default: datetime | None = ...
) -> np.ndarray: ...
def try_parse_date_and_time(
    dates: np.ndarray,
    times: np.ndarray,
    date_parser=...,
    time_parser=...,
    dayfirst: bool = ...,
    default: datetime | None = ...,
) -> np.ndarray: ...
def try_parse_year_month_day(
    years: np.ndarray, months: np.ndarray, days: np.ndarray
) -> np.ndarray: ...
def try_parse_datetime_components(
    years: np.ndarray,
    months: np.ndarray,
    days: np.ndarray,
    hours: np.ndarray,
    minutes: np.ndarray,
    seconds: np.ndarray,
) -> np.ndarray: ...
def format_is_iso(f: str) -> bool: ...
def guess_datetime_format(
    dt_str, dayfirst: bool = ..., dt_str_parse=..., dt_str_split=...
) -> str | None: ...
def concat_date_cols(
    date_cols: tuple, keep_trivial_numbers: bool = ...
) -> np.ndarray: ...
def get_rule_month(source: str) -> str: ...
