#!/usr/bin/env bash

set -e

SCRIPTS_DIR="$(cd "$( dirname "$(readlink -f $0)")" && pwd)"
TEST_PATH=$(realpath "${SCRIPTS_DIR}/../")

for test in $(find "$TEST_PATH" -iname "[0-9]*-*.bats" | sort ); do
    echo "Running tests for ${test}..."
    /usr/local/bin/bats --tap "${test}"
done
