#!/bin/bash

set -e

pushd .. >/dev/null

if ! which protoc-gen-go-grpc &>/dev/null; then
	echo "protoc-gen-go-grpc is missing. Make sure to install it and add it to your PATH."
	exit 1
fi

if ! [[ -d "github.com/bentoml/bentoml/grpc" ]]; then
	protoc -I. -I ./thirdparty/protobuf/src \
		--go_out . --go_opt paths=import \
		--go-grpc_out . --go-grpc_opt paths=import \
		bentoml/grpc/v1alpha1/service.proto
fi

popd >/dev/null

# This script is a hack to test out client.go locally without using bazel.
pushd "$(dirname "$0")/github.com/bentoml/bentoml/grpc/v1alpha1/" >/dev/null
! [[ -f "go.mod" ]] && go mod init v1alpha1
go mod tidy
popd >/dev/null

# Then run the client
go run ./client.go
