contact_links:
  - name: BentoML Discussions
    url: https://github.com/bentoml/BentoML/discussions
    about: Please ask general questions here.
  - name: BentoML Slack Community
    url: https://join.slack.bentoml.org
    about: For connecting with others in the community
  - name: BentoML Enterprise Support
    url: contact@bentoml.ai
    about: Contact the BentoML team and learn more
