blank_issues_enabled: true
version: 2.1
contact_links:
  - name: BentoML issue tracker
    url: https://github.com/bentoml/BentoML/issues/new/choose
    about: Open a Pull request / Issue related here.
  - name: BentoML Discussions
    url: https://github.com/bentoml/BentoML/discussions
    about: Please ask general questions here.
  - name: BentoML Slack Community
    url: https://l.linklyhq.com/l/ktOh
    about: For connecting with others in the community
  - name: BentoML Enterprise Support
    url: contact@bentoml.ai
    about: Contact the BentoML team and learn more
  - name: BentoML Blog
    url: modelserving.com
    about: To stay informed with community updates
