name: 🚀 Feature Request
description: Submit a proposal/request for new BentoML feature.
title: "feat|proposal: "
labels: ["new-feature", "enhancement"]
body:
- type: textarea
  id: feature-request
  validations:
    required: true
  attributes:
    label: Feature request
    description: |
      A clear and concise description of the feature proposal.
    placeholder: |
      An implementation of ... can be done as follow:
- type: textarea
  id: motivation
  validations:
    required: true
  attributes:
    label: Motivation
    description: |
      Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...]. If this is related to another GitHub issue, please link here too.
    placeholder: |
      This feature would solve issue #2668 ...
- type: textarea
  id: contribution
  validations:
    required: true
  attributes:
    label: Contribution
    description: |
      Is there any way that you could help, e.g. by submitting a PR? Please make sure to read the [CONTRIBUTING.md](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md)
      as well as [DEVELOPMENT.md](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md)
    placeholder: |
      I can ...
