name: 🚀 Feature Request
description: Submit a proposal/request for new BentoML feature.
title: "feature: "
labels: ["new-feature", "enhancement"]
body:
- type: textarea
  id: feature-request
  validations:
    required: true
  attributes:
    label: Feature request
    description: |
      A clear and concise description of the feature proposal.
    placeholder: |
      An implementation of ... can be done as follow:
- type: textarea
  id: motivation
  validations:
    required: false
  attributes:
    label: Motivation
    description: |
      Please outline the motivation for the proposal. Is your feature request related to a problem? e.g., I'm always frustrated when [...].
      If this is related to another GitHub issue, please link here too.
      If you have a current workaround, please also provide it here.
    placeholder: |
      This feature would solve issue #2668 ...
- type: checkboxes
  id: contribution
  attributes:
    label: Contribution
    description: |
      Is there any way that you could help, e.g. by submitting a PR? Please make sure to read the [CONTRIBUTING.md](https://github.com/bentoml/BentoML/blob/main/CONTRIBUTING.md) as well as [DEVELOPMENT.md](https://github.com/bentoml/BentoML/blob/main/DEVELOPMENT.md)
    options:
      - label: I can contribute code.
        required: false
      - label: I can contribute documentation.
        required: false
      - label: I can help testing the feature.
        required: false
      - label: I will be open to provide feedback once the feature is released.
        required: false
