from pandas._typing import ArrayLike, DtypeObj

def cast_to_common_type(arr: ArrayLike, dtype: DtypeObj) -> ArrayLike: ...
def concat_compat(to_concat, axis: int = ..., ea_compat_axis: bool = ...): ...
def union_categoricals(
    to_union, sort_categories: bool = ..., ignore_order: bool = ...
): ...
