from pandas._typing import ArrayLike

is_bool = ...
is_integer = ...
is_float = ...
is_complex = ...
is_scalar = ...
is_decimal = ...
is_interval = ...
is_list_like = ...
is_iterator = ...

def is_number(obj) -> bool: ...
def iterable_not_string(obj) -> bool: ...
def is_file_like(obj) -> bool: ...
def is_re(obj) -> bool: ...
def is_re_compilable(obj) -> bool: ...
def is_array_like(obj) -> bool: ...
def is_nested_list_like(obj) -> bool: ...
def is_dict_like(obj) -> bool: ...
def is_named_tuple(obj) -> bool: ...
def is_hashable(obj) -> bool: ...
def is_sequence(obj) -> bool: ...
def is_dataclass(item): ...
def is_inferred_bool_dtype(arr: ArrayLike) -> bool: ...
