import numpy as np
from pandas._typing import ArrayLike, DtypeObj

isposinf_scalar = ...
isneginf_scalar = ...
nan_checker = ...
INF_AS_NA = ...

def isna(obj): ...

isnull = ...

def notna(obj): ...

notnull = ...

def isna_compat(arr, fill_value=...) -> bool: ...
def array_equivalent(
    left, right, strict_nan: bool = ..., dtype_equal: bool = ...
) -> bool: ...
def array_equals(left: ArrayLike, right: ArrayLike) -> bool: ...
def infer_fill_value(val): ...
def maybe_fill(arr: np.ndarray) -> np.ndarray: ...
def na_value_for_dtype(dtype: DtypeObj, compat: bool = ...): ...
def remove_na_arraylike(arr): ...
def is_valid_na_for_dtype(obj, dtype: DtypeObj) -> bool: ...
def isna_all(arr: ArrayLike) -> bool: ...
