apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: bentoml-custom-model
spec:
  predictor:
    containers:
      - name: bentoml-kserve-container
        image: {username}/iris_classifier:latest
