[tool.poetry]
name = "bentoml-docker"
version = "0.1.0"
description = "BentoML's Docker Images Management"
authors = ["BentoML Contributors<contact@bentoml.ai>"]

[tool.poetry.dependencies]
python = "^3.6"
docker = "^5.0.0"
Jinja2 = "^3.0.1"
cerebrus = "^0.2"
PyYAML = "^5.4.1"
absl-py = "^0.13.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"