

from ..bert.tokenization_bert import BertTokenizer

logger = ...
VOCAB_FILES_NAMES = ...
PRETRAINED_VOCAB_FILES_MAP = ...
PRETRAINED_POSITIONAL_EMBEDDINGS_SIZES = ...
PRETRAINED_INIT_CONFIGURATION = ...
class ConvBertTokenizer(BertTokenizer):
    r"""
    Construct a ConvBERT tokenizer. :class:`~transformers.ConvBertTokenizer` is identical to
    :class:`~transformers.BertTokenizer` and runs end-to-end tokenization: punctuation splitting and wordpiece. Refer
    to superclass :class:`~transformers.BertTokenizer` for usage examples and documentation concerning parameters.
    """
    vocab_files_names = ...
    pretrained_vocab_files_map = ...
    max_model_input_sizes = ...
    pretrained_init_configuration = ...


