{{- if .Values.ingress.enabled -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: yatai-ingress
  labels:
    app: yatai-ingress
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - {{ .Values.ingress.hostname }}
      secretName: {{ .secretName }}
{{- end }}
  rules:
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        - backend:
            serviceName: yatai-service
            servicePort: grpc
---
apiVersion: "stable.k8s.psg.io/v1"
kind: "Certificate"
metadata:
  name: {{ .Values.ingress.hostname }}
spec:
  domain: {{ .Values.ingress.hostname }}
{{- end }}