apiVersion: v1
kind: Service
metadata:
  name: yatai-service
  labels:
    app: yatai-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: web
    port: {{ .Values.service.ports.web }}
    targetPort: {{ .Values.service.ports.web }}
  - name: grpc
    port: {{ .Values.service.ports.grpc }}
    targetPort: {{ .Values.service.ports.grpc }}
  selector:
    app: yatai-service
