#!/usr/bin/env bash

git config --global pull.rebase true
git config --global pull.ff only

# fetch all tags
git fetch upstream --tags && git pull

# install editable wheels & tools for bentoml
pip install -e ".[tracing,grpc]" -r requirements/dev-requirements.txt

# setup docker buildx
docker buildx install
docker buildx ls | grep bentoml-builder &>/dev/null || docker buildx create --use --name bentoml-builder --platform linux/amd64,linux/arm64 &>/dev/null
