from collections import abc
from pandas.io.sas.sasreader import ReaderBase
from pandas.util._decorators import Appender

_correct_line1 = ...
_correct_header1 = ...
_correct_header2 = ...
_correct_obs_header = ...
_fieldkeys = ...
_base_params_doc = ...
_params2_doc = ...
_format_params_doc = ...
_iterator_doc = ...
_read_sas_doc = ...
_xport_reader_doc = ...
_read_method_doc = ...

class XportReader(ReaderBase, abc.Iterator):
    __doc__ = ...
    def __init__(
        self, filepath_or_buffer, index=..., encoding=..., chunksize=...
    ) -> None: ...
    def close(self): ...
    def __next__(self): ...
    def get_chunk(self, size=...): ...
