"""
This type stub file was generated by pyright.
"""

class Type:
    """
    Represents the file type object inherited by
    specific file type matchers.
    Provides convenient accessor and helper methods.
    """
    def __init__(self, mime, extension) -> None:
        ...
    
    @property
    def mime(self): # -> Unknown:
        ...
    
    @property
    def extension(self): # -> Unknown:
        ...
    
    def is_extension(self, extension): # -> bool:
        ...
    
    def is_mime(self, mime): # -> bool:
        ...
    
    def match(self, buf):
        ...
    


