"""
This type stub file was generated by pyright.
"""

from .base import Type

class Woff(Type):
    """
    Implements the WOFF font type matcher.
    """
    MIME = ...
    EXTENSION = ...
    def __init__(self) -> None:
        ...
    
    def match(self, buf): # -> Literal[False]:
        ...
    


class Woff2(Type):
    """
    Implements the WOFF2 font type matcher.
    """
    MIME = ...
    EXTENSION = ...
    def __init__(self) -> None:
        ...
    
    def match(self, buf): # -> Literal[False]:
        ...
    


class Ttf(Type):
    """
    Implements the TTF font type matcher.
    """
    MIME = ...
    EXTENSION = ...
    def __init__(self) -> None:
        ...
    
    def match(self, buf): # -> Literal[False]:
        ...
    


class Otf(Type):
    """
    Implements the OTF font type matcher.
    """
    MIME = ...
    EXTENSION = ...
    def __init__(self) -> None:
        ...
    
    def match(self, buf): # -> Literal[False]:
        ...
    


