"""
This type stub file was generated by pyright.
"""

from .base import Type

class IsoBmff(Type):
    """
    Implements the ISO-BMFF base type.
    """
    def __init__(self, mime, extension) -> None:
        ...
    


