from distutils.command.build_clib import build_clib as old_build_clib

""" Modified version of build_clib that handles fortran source files.
"""
_l = old_build_clib.user_options

class build_clib(old_build_clib):
    description = ...
    user_options = ...
    boolean_options = ...
    def initialize_options(self): ...
    def finalize_options(self): ...
    def have_f_sources(self): ...
    def have_cxx_sources(self): ...
    def run(self): ...
    def get_source_files(self): ...
    def build_libraries(self, libraries): ...
    def build_a_library(self, build_info, lib_name, libraries): ...
