from distutils.command.build_py import build_py as old_build_py

class build_py(old_build_py):
    def run(self): ...
    def find_package_modules(self, package, package_dir): ...
    def find_modules(self): ...
