from distutils.core import Command

def show_fortran_compilers(_cache=...): ...

class config_fc(Command):
    """Distutils command to hold user specified options
    to Fortran compilers.

    config_fc command is used by the FCompiler.customize() method.
    """

    description = ...
    user_options = ...
    help_options = ...
    boolean_options = ...
    def initialize_options(self): ...
    def finalize_options(self): ...
    def run(self): ...

class config_cc(Command):
    """Distutils command to hold user specified options
    to C/C++ compilers.
    """

    description = ...
    user_options = ...
    def initialize_options(self): ...
    def finalize_options(self): ...
    def run(self): ...
