from distutils.core import Command

class install_clib(Command):
    description = ...
    user_options = ...
    def initialize_options(self): ...
    def finalize_options(self): ...
    def run(self): ...
    def get_outputs(self): ...
