import typing

class Convertor:
    regex = ...
    def convert(self, value: str) -> typing.Any: ...
    def to_string(self, value: typing.Any) -> str: ...

class StringConvertor(Convertor):
    regex = ...
    def convert(self, value: str) -> typing.Any: ...
    def to_string(self, value: typing.Any) -> str: ...

class PathConvertor(Convertor):
    regex = ...
    def convert(self, value: str) -> typing.Any: ...
    def to_string(self, value: typing.Any) -> str: ...

class IntegerConvertor(Convertor):
    regex = ...
    def convert(self, value: str) -> typing.Any: ...
    def to_string(self, value: typing.Any) -> str: ...

class FloatConvertor(Convertor):
    regex = ...
    def convert(self, value: str) -> typing.Any: ...
    def to_string(self, value: typing.Any) -> str: ...

class UUIDConvertor(Convertor):
    regex = ...
    def convert(self, value: str) -> typing.Any: ...
    def to_string(self, value: typing.Any) -> str: ...

CONVERTOR_TYPES = ...
