from starlette.requests import Request
from starlette.responses import Response
from starlette.types import Receive, Scope, Send

class GraphQLApp:
    def __init__(
        self, schema: graphene.Schema, executor_class: type = ..., graphiql: bool = ...
    ) -> None: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
    async def handle_graphql(self, request: Request) -> Response: ...
    async def execute(self, query, variables=..., context=..., operation_name=...): ...
    async def handle_graphiql(self, request: Request) -> Response: ...

GRAPHIQL = ...
