repository:
  type: file_system
  file_system:
    directory: Null
  s3:
    url: Null
    endpoint_url: Null
    signature_version: s3v4
    expiration: 3000
  gcs:
    url: Null
    expiration: 3000
database:
  url: Null
namespace: dev
logging:
  path: Null
