from typing import TYPE_CHECKING
from pandas._typing import DtypeObj, FrameOrSeries, JSONSerializable

if TYPE_CHECKING: ...
loads = ...

def as_json_table_type(x: DtypeObj) -> str: ...
def set_default_names(data): ...
def convert_pandas_type_to_json_field(arr): ...
def convert_json_field_to_pandas_type(field): ...
def build_table_schema(
    data: FrameOrSeries,
    index: bool = ...,
    primary_key: bool | None = ...,
    version: bool = ...,
) -> dict[str, JSONSerializable]: ...
