"""EC2 target: deploy the image onto one or more existing EC2 instances over
SSH (docker pull + rm -f + run), require the container to stay Up, and
verify /readyz plus the configured inference request on every host — through
a hardened SSH tunnel by default, or directly when the security group lets
the deploying machine reach the host port.

This script NEVER provisions instances: ec2.hosts must already exist
and accept key-based SSH (provisioning stays in the interactive
bentoml-ec2-deploy skill). All remote docker commands run under ``sudo -n``:
``usermod -aG docker`` does not apply to already-open SSH sessions and races
on fresh instances, while sudo always works — and ``-n`` makes a
password-prompting sudo fail fast instead of hanging a non-interactive run.

Secret transport (ec2.env_names): values are read from THIS
process's environment at deploy time — never from the config, never written
to any file. Each value travels base64-encoded over the SSH channel's stdin
as one ``NAME <base64>`` line; a small remote reader exports the variables
and execs ``sudo -n --preserve-env=<names> docker run ... -e NAME`` using
docker's value-less ``-e NAME`` form, which takes the value from the docker
client's own environment. The values therefore never appear in any argv on
either machine (``ps`` cannot see them locally or remotely) — only in
process environments, which the kernel restricts to the owning user and
root. Variable NAMES are validated against ^[A-Za-z_][A-Za-z0-9_]*$ at
config load, so they are shell-inert; every other user-controlled token
that enters a remote command line goes through shlex.quote().

Generated by the bentoml-deploy-scriptgen skill — do not edit by hand; all
tunables live in config.yml.
"""

# This bundle gets committed into arbitrary user repos; the directive below
# keeps the import layout stable under any repo's ruff/isort configuration.
# isort: skip_file
from __future__ import annotations

import base64
import os
import re
import shlex
import socket
import stat
import subprocess
import tempfile
import time
import urllib.error
from pathlib import Path
from typing import TYPE_CHECKING

from ..arch import buildx_available
from ..arch import decide_platform
from ..arch import docker_builder_arch
from ..arch import host_arch
from ..arch import normalize_arch
from ..common import EXIT_DEPLOY
from ..common import EXIT_GENERIC
from ..common import EXIT_VERIFY
from ..common import DeployError
from ..common import RunResult
from ..common import http_get
from ..common import http_post_json
from ..common import log
from ..common import run
from ..common import section
from ..common import warn
from ..config import ECR_HOST_RE
from ..config import Ec2Config
from ..config import InferenceCheck
from ..config import VerifyConfig
from ..preflight import CheckFailed
from ..preflight import _which
from ..preflight import run_checks

if TYPE_CHECKING:  # pragma: no cover - import cycle guard for type checkers
    from ..context import RunContext

# Remote reader for the env payload (one "NAME <base64>" line per variable
# on stdin). The `&& printf x` / ${...%x} pair preserves trailing newlines
# that the shell's command substitution would otherwise strip; a value that
# fails to decode aborts with exit 78 before docker run starts.
_ENV_READER = (
    "while IFS=' ' read -r __n __b; do "
    '__v=$(printf %s "$__b" | base64 -d && printf x) || exit 78; '
    'export "$__n=${__v%x}"; '
    "done; "
)


def _ssh_base(ec2: Ec2Config) -> list[str]:
    return [
        "ssh",
        "-i",
        str(ec2.ssh_key_path),
        "-o",
        "StrictHostKeyChecking=accept-new",
        "-o",
        "BatchMode=yes",
        "-o",
        "ConnectTimeout=10",
    ]


def _ssh_run(
    ec2: Ec2Config,
    host: str,
    remote_command: str,
    *,
    check: bool = True,
    capture: bool = False,
    input_text: str = "",
    quiet: bool = False,
    timeout: float | None = None,
    exit_code: int = EXIT_GENERIC,
    secret_output: bool = False,
) -> RunResult:
    """Run one remote command over SSH. stdin defaults to an empty pipe so
    ssh can never eat the caller's stdin; input_text carries the secret
    payloads (ECR token, env values) when there are any."""
    return run(
        [*_ssh_base(ec2), f"{ec2.ssh_user}@{host}", remote_command],
        check=check,
        capture=capture,
        input_text=input_text,
        quiet=quiet,
        timeout=timeout,
        exit_code=exit_code,
        secret_output=secret_output,
    )


def _ecr_registry(image: str) -> tuple[str, str]:
    """Return (registry_host, region) for an ECR image ref."""
    host = image.split("/", 1)[0]
    match = ECR_HOST_RE.match(host)
    if match is None:
        raise DeployError(
            "ec2.registry_auth is 'ecr-token-over-ssh' but the "
            f"image ref {image!r} is not in a private ECR registry",
            EXIT_DEPLOY,
            hint="use an ECR image ref, or set ec2.registry_auth to "
            "'preauthed' and handle registry login on the instances yourself",
        )
    return host, match.group("region")


# --------------------------------------------------------------------------
# preflight
# --------------------------------------------------------------------------


def preflight(ctx: RunContext) -> None:
    """Standalone entry point: run this target's checks in one pass."""
    run_checks(preflight_checks(ctx))


def preflight_checks(ctx: RunContext) -> list:
    """Build this target's checks so deploy.py can aggregate them with the
    build-side families into a single report. With ctx.local_only, only
    checks that need no key, credentials, or host connectivity are returned;
    the rest are recorded in the summary's skipped list."""
    ec2 = ctx.cfg.require_ec2()

    def ssh_cli() -> str | None:
        _which("ssh", "install an OpenSSH client")
        return None

    checks = [("ec2.ssh-cli", ssh_cli)]

    ecr_auth = ec2.registry_auth == "ecr-token-over-ssh"
    if ecr_auth:

        def aws_cli() -> str | None:
            _which(
                "aws",
                "install the AWS CLI v2 — it mints the ECR token that is "
                "piped to the hosts",
            )
            return None

        checks.append(("ec2.aws-cli", aws_cli))
        checks.append(("ec2.ecr-image-ref", _ecr_image_ref_check(ctx)))

    if ctx.local_only:
        ctx.summary.skipped += [
            "ec2.ssh-key (--local-only)",
            "ec2.env-vars (--local-only)",
            "ec2.ssh-reachable/remote-docker/remote-arch/host-port per host (--local-only)",
        ]
        if ecr_auth:
            ctx.summary.skipped.append("ec2.ecr-token (--local-only)")
        return checks

    checks.append(("ec2.ssh-key", lambda: _ssh_key_check(ec2)))
    checks.append(("ec2.env-vars", lambda: _env_vars_check(ec2)))
    if ecr_auth:
        checks.append(("ec2.ecr-token", _ecr_token_check(ctx)))
    probes: dict[str, object] = {}
    # Shared across hosts: one image is built for every host, so two hosts of
    # different architectures cannot both be served (see _host_checks).
    host_arches: dict[str, str] = {}
    for host in ec2.hosts:
        checks += _host_checks(ctx, ec2, host, probes, host_arches)
    return checks


def _ecr_image_ref_check(ctx: RunContext):
    def ecr_image_ref() -> str | None:
        if ctx.image is None:
            raise CheckFailed(
                "no image reference resolved, so the ECR registry host "
                "cannot be validated",
                hint="fix the common.git-repo failure, or pass --image/--version",
            )
        host = ctx.image.split("/", 1)[0]
        match = ECR_HOST_RE.match(host)
        if match is None:
            raise CheckFailed(
                "registry_auth is 'ecr-token-over-ssh' but the image ref "
                f"{ctx.image!r} is not in a private ECR registry",
                hint="use an ECR image ref, or set ec2.registry_auth "
                "to 'preauthed' and handle registry login on the instances "
                "yourself",
            )
        return "{} (region {})".format(host, match.group("region"))

    return ecr_image_ref


def _ecr_token_check(ctx: RunContext):
    def ecr_token() -> str | None:
        # This machine mints the token that deploy pipes to the hosts, so
        # probe the exact call deploy will make (a fresh token per run — it
        # cannot be expired).
        match = ECR_HOST_RE.match(ctx.image.split("/", 1)[0]) if ctx.image else None
        if match is None:
            raise CheckFailed("cannot mint an ECR token (see ec2.ecr-image-ref)")
        region = match.group("region")
        res = run(
            ["aws", "ecr", "get-login-password", "--region", region],
            capture=True,
            quiet=True,
            check=False,
            timeout=60,
            secret_output=True,
        )
        if res.returncode != 0:
            raise CheckFailed(
                f"could not obtain an ECR auth token for region {region}: "
                f"{res.stderr.strip()[:300]}",
                hint="export AWS credentials (AWS_PROFILE / access keys / "
                "SSO) for an identity with ecr:GetAuthorizationToken — the "
                "token is minted locally and piped to the hosts over SSH",
            )
        return f"token ok for {region}"

    return ecr_token


def _ssh_key_check(ec2: Ec2Config) -> str | None:
    key = ec2.ssh_key_path
    if not key.is_file():
        raise CheckFailed(
            f"SSH key file not found: {key}",
            hint="fix ec2.ssh_key_path (~ expands; relative paths "
            "resolve against the deploy/ directory)",
        )
    mode = stat.S_IMODE(key.stat().st_mode)
    if mode & 0o077:
        raise CheckFailed(
            f"SSH key {key} is group/other-accessible (mode {mode:03o}) — "
            "OpenSSH itself refuses such keys",
            hint=f"chmod 600 {key}",
        )
    if not mode & 0o400:
        raise CheckFailed(
            f"SSH key {key} is not readable by its owner (mode {mode:03o})",
            hint=f"chmod 600 {key}",
        )
    return f"mode {mode:03o}"


def _env_vars_check(ec2: Ec2Config) -> str | None:
    if not ec2.env_names:
        return "no env vars configured"
    missing = [name for name in ec2.env_names if not os.environ.get(name)]
    if missing:
        raise CheckFailed(
            "missing (or empty) in this process's environment: " + ", ".join(missing),
            hint="export the value(s) before running — they are read from "
            "the environment at deploy time and are never stored anywhere",
        )
    return f"{len(ec2.env_names)} env var(s) present"


def _probe_host(ec2: Ec2Config, host: str, probes: dict) -> dict:
    """One SSH round trip gathering everything the per-host checks need,
    cached so four checks cost one connection per host."""
    cached = probes.get(host)
    if isinstance(cached, CheckFailed):
        raise CheckFailed(
            f"not probed — SSH to {host} failed (see ec2.ssh-reachable[{host}])"
        )
    if isinstance(cached, dict):
        return cached
    fmt_version = shlex.quote("{{.ServerVersion}}")
    fmt_names = shlex.quote("{{.Names}}")
    publish_filter = shlex.quote(f"publish={ec2.host_port}")
    ss_filter = shlex.quote(f"sport = :{ec2.host_port}")
    remote = (
        'echo "arch=$(uname -m)"; '
        "if ! command -v docker >/dev/null 2>&1; then echo docker=missing; "
        "elif ! sudo -n true 2>/dev/null; then echo docker=no-sudo; "
        f"elif __v=$(sudo -n docker info --format {fmt_version} 2>/dev/null); "
        'then echo "docker=$__v"; '
        f'echo "port_owner=$(sudo -n docker ps --filter {publish_filter} '
        f'--format {fmt_names} | tr "\\n" ,)"; '
        "else echo docker=down; fi; "
        "if command -v ss >/dev/null 2>&1; "
        f'then echo "listeners=$(ss -ltn {ss_filter} | grep -c LISTEN)"; '
        "else echo listeners=unknown; fi"
    )
    res = _ssh_run(ec2, host, remote, capture=True, check=False, quiet=True, timeout=90)
    if res.returncode != 0:
        failure = CheckFailed(
            f"SSH to {ec2.ssh_user}@{host} failed (exit {res.returncode}): "
            f"{(res.stderr.strip() or res.stdout.strip())[:300]}",
            hint="check the host address, that the security group allows "
            "port 22 from this machine, ec2.ssh_user (ec2-user for "
            "Amazon Linux, ubuntu for Ubuntu), and the key — BatchMode is "
            "on, so nothing may prompt",
        )
        probes[host] = failure
        raise failure
    parsed: dict[str, str] = {}
    for line in res.stdout.splitlines():
        if "=" in line:
            key, _, value = line.partition("=")
            parsed[key.strip()] = value.strip()
    probes[host] = parsed
    return parsed


def _host_checks(
    ctx: RunContext,
    ec2: Ec2Config,
    host: str,
    probes: dict,
    host_arches: dict,
) -> list:
    def reachable() -> str | None:
        probe = _probe_host(ec2, host, probes)
        return "connected (arch {})".format(probe.get("arch", "?"))

    def remote_docker() -> str | None:
        state = _probe_host(ec2, host, probes).get("docker", "")
        if state == "missing":
            raise CheckFailed(
                f"docker is not installed on {host}",
                hint="Amazon Linux 2023: sudo dnf install -y docker && sudo "
                "systemctl enable --now docker; Ubuntu: sudo apt-get "
                "install -y docker.io && sudo systemctl enable --now docker",
            )
        if state == "no-sudo":
            raise CheckFailed(
                f"{ec2.ssh_user}@{host} has no passwordless sudo — every "
                "remote docker command runs under 'sudo -n'",
                hint="grant NOPASSWD sudo to the SSH user (stock EC2 cloud "
                "images have it by default)",
            )
        if state == "down":
            raise CheckFailed(
                f"the docker daemon is not running on {host}",
                hint="sudo systemctl enable --now docker — 'enable' matters: "
                "--restart unless-stopped only survives reboots if the "
                "daemon itself comes back",
            )
        if not state:
            raise CheckFailed(f"could not determine the docker state on {host}")
        return f"server {state}"

    def remote_arch() -> str | None:
        """Cross-architecture detection for this host — the replacement for
        v3's `image.platform` knob. The image this run builds must match the
        host's architecture, or the container dies with 'exec format error'
        the moment it starts."""
        remote = normalize_arch(_probe_host(ec2, host, probes).get("arch", ""))
        if remote:
            host_arches[host] = remote
        distinct = sorted(set(host_arches.values()))
        if len(distinct) > 1:
            # One image is built and pushed for every host, so it cannot match
            # two architectures at once.
            raise CheckFailed(
                "ec2.hosts have different architectures "
                + ", ".join(f"{h}={a}" for h, a in sorted(host_arches.items()))
                + " — one image cannot run on all of them",
                hint="deploy each architecture from its own bundle/config "
                "(one ec2.hosts list per architecture), or use hosts of a "
                "single architecture",
            )
        builder = docker_builder_arch() or host_arch()
        decision = decide_platform(builder, [remote], f"host {host}")
        if ctx.skip_build:
            # Nothing is built, so a mismatch cannot be fixed here — but it is
            # worth saying out loud before the container crash-loops.
            if decision.cross:
                warn(
                    f"{host} is {remote} while this machine's builder is "
                    f"{builder}; --skip-build means the existing image is "
                    "deployed as-is, so if it was built for the builder's "
                    "architecture the container will die with 'exec format "
                    "error'"
                )
                return f"UNVERIFIED — host is {remote}, image arch unknown"
            return f"{remote} (image arch unverified under --skip-build)"
        if decision.cross:
            if not buildx_available():
                raise CheckFailed(
                    f"{host} is {remote} but the builder is {builder}, so the "
                    "image must be cross-built — and docker buildx is not "
                    "available",
                    hint="install the docker buildx plugin (ships with Docker "
                    "Desktop; on Debian/Ubuntu: docker-buildx-plugin). "
                    "BuildKit is what honours the platform flag.",
                )
            ctx.build_platform = decision.platform
            log(f"  cross-arch build enabled: --opt platform={decision.platform}")
        return decision.message

    def host_port() -> str | None:
        probe = _probe_host(ec2, host, probes)
        owners = [n for n in probe.get("port_owner", "").split(",") if n]
        if ec2.container_name in owners:
            return (
                f"port {ec2.host_port} is bound by our container (it will be replaced)"
            )
        if owners:
            raise CheckFailed(
                f"host port {ec2.host_port} on {host} is published by other "
                f"container(s): {', '.join(owners)}",
                hint="pick another ec2.host_port, or remove the "
                "container on the host if it is obsolete",
            )
        listeners = probe.get("listeners", "unknown")
        if listeners == "unknown":
            warn(
                f"{host}: 'ss' is unavailable — could not check for "
                f"non-docker listeners on port {ec2.host_port}"
            )
            return (
                f"no container publishes {ec2.host_port} "
                "(non-docker listeners unverified)"
            )
        if listeners not in ("", "0"):
            raise CheckFailed(
                f"a non-docker process is listening on port {ec2.host_port} "
                f"on {host} ({listeners} listener(s) reported by ss)",
                hint="pick another ec2.host_port, or stop that process",
            )
        return f"port {ec2.host_port} free"

    return [
        (f"ec2.ssh-reachable[{host}]", reachable),
        (f"ec2.remote-docker[{host}]", remote_docker),
        (f"ec2.remote-arch[{host}]", remote_arch),
        (f"ec2.host-port[{host}]", host_port),
    ]


# --------------------------------------------------------------------------
# deploy
# --------------------------------------------------------------------------


def _docker_run_command(ec2: Ec2Config, image: str) -> str:
    """The remote command that starts the container. Values for env_names
    arrive via stdin (see the module docstring), so this string never
    contains a secret and is safe to log."""
    parts = [
        "docker",
        "run",
        "-d",
        "--name",
        shlex.quote(ec2.container_name),
        "--restart",
        "unless-stopped",
        "-p",
        f"{ec2.host_port}:3000",
    ]
    for name in ec2.env_names:
        parts += ["-e", name]
    parts.append(shlex.quote(image))
    if not ec2.env_names:
        return "sudo -n " + " ".join(parts)
    preserve = ",".join(ec2.env_names)
    return _ENV_READER + f"exec sudo -n --preserve-env={preserve} " + " ".join(parts)


def _env_payload(ec2: Ec2Config) -> str:
    """The stdin payload consumed by _ENV_READER: one 'NAME <base64>' line
    per variable, values straight from this process's environment."""
    if not ec2.env_names:
        return ""
    lines = []
    for name in ec2.env_names:
        value = os.environ.get(name)
        if not value:  # preflight guarantees presence; guard regardless
            raise DeployError(
                f"env var {name} (ec2.env_names) is missing from the environment",
                EXIT_DEPLOY,
                hint=f"export {name}=... before running",
            )
        encoded = base64.b64encode(value.encode("utf-8")).decode("ascii")
        lines.append(f"{name} {encoded}")
    return "\n".join(lines) + "\n"


def _container_status(ec2: Ec2Config, host: str) -> str:
    """The container's docker status line ('Up 3 seconds', 'Exited (1) ...'),
    or '' if no container with that name exists."""
    res = _ssh_run(
        ec2,
        host,
        "sudo -n docker ps -a --filter {} --format {}".format(
            # docker treats the name filter as a regex — escape the name
            shlex.quote(f"name=^{re.escape(ec2.container_name)}$"),
            shlex.quote("{{.Status}}"),
        ),
        capture=True,
        check=False,
        quiet=True,
        timeout=60,
    )
    first_line = res.stdout.strip().splitlines()[:1]
    return first_line[0].strip() if first_line else ""


def _rollback_guidance(ec2: Ec2Config, host: str) -> str:
    ssh = f"ssh -i {shlex.quote(str(ec2.ssh_key_path))} {ec2.ssh_user}@{host}"
    name = ec2.container_name
    return (
        "Diagnose:\n"
        f"  {ssh} 'sudo docker ps -a --filter name={name}'\n"
        f"  {ssh} 'sudo docker logs --tail 100 {name}'\n"
        "Roll back by redeploying the previous image (docker rm -f already "
        "replaced the old container — on EC2 a rollback IS a redeploy):\n"
        "  python3 deploy/deploy.py --target ec2 --skip-build --image <previous-ref>"
    )


def deploy(ctx: RunContext) -> None:
    ec2 = ctx.cfg.require_ec2()
    image = ctx.image or ""
    section(f"deploy: docker over SSH to {len(ec2.hosts)} host(s) (image={image})")
    token: str | None = None
    registry_host = ""
    if ec2.registry_auth == "ecr-token-over-ssh":
        registry_host, region = _ecr_registry(image)
        log(f"minting ECR token for {registry_host} (region {region})")
        token = run(
            ["aws", "ecr", "get-login-password", "--region", region],
            capture=True,
            quiet=True,
            exit_code=EXIT_DEPLOY,
            secret_output=True,
            timeout=60,
        ).stdout.strip()
    for index, host in enumerate(ec2.hosts):
        started = time.monotonic()
        try:
            _deploy_host(ec2, host, image, token, registry_host)
        except BaseException:
            ctx.summary.record_stage(
                f"ec2.deploy[{host}]", False, time.monotonic() - started
            )
            for later in ec2.hosts[index + 1 :]:
                ctx.summary.record_stage(
                    f"ec2.deploy[{later}]",
                    False,
                    0.0,
                    detail="not attempted (fail-fast after a previous host failed)",
                )
            raise
        ctx.summary.record_stage(
            f"ec2.deploy[{host}]", True, time.monotonic() - started
        )


def _deploy_host(
    ec2: Ec2Config, host: str, image: str, token: str | None, registry_host: str
) -> None:
    section(f"deploy {host}")
    if token is not None:
        log(f">>> on {host}: ECR login (token over the SSH channel's stdin)")
        res = _ssh_run(
            ec2,
            host,
            "sudo -n docker login --username AWS --password-stdin "
            + shlex.quote(registry_host),
            input_text=token,
            capture=True,
            check=False,
            secret_output=True,
            timeout=120,
        )
        if res.returncode != 0:
            # Do NOT embed the remote output: the command consumed the auth
            # token on stdin, so its output must be treated as sensitive
            # (that is what secret_output=True means).
            raise DeployError(
                f"ECR login on {host} failed (exit {res.returncode}); "
                "remote output suppressed — it may contain the auth token. "
                "Re-run the login manually on the host to see the error.",
                EXIT_DEPLOY,
                hint="check SSH access to the host and that the local AWS "
                "identity may call ecr:GetAuthorizationToken",
            )
    log(f">>> on {host}: docker pull")
    pulled = _ssh_run(
        ec2, host, "sudo -n docker pull " + shlex.quote(image), check=False
    )
    if pulled.returncode != 0:
        raise DeployError(
            f"docker pull of {image} on {host} failed (exit {pulled.returncode})",
            EXIT_DEPLOY,
            hint="registry auth is the usual cause: ECR tokens expire after "
            "12 hours ('ecr-token-over-ssh' refreshes them each run; "
            "'preauthed' means YOU keep the instance profile or docker "
            "login working). Also check the repository name, that the tag "
            "exists, and free disk space on the host (df -h /).",
        )
    removed = _ssh_run(
        ec2,
        host,
        "sudo -n docker rm -f " + shlex.quote(ec2.container_name),
        capture=True,
        check=False,
        timeout=120,
    )
    if removed.returncode == 0:
        log(f">>> on {host}: removed existing container {ec2.container_name}")
    log(f">>> on {host}: docker run ({len(ec2.env_names)} env var(s) via stdin)")
    started = _ssh_run(
        ec2,
        host,
        _docker_run_command(ec2, image),
        input_text=_env_payload(ec2),
        capture=True,
        check=False,
        timeout=300,
    )
    if started.returncode != 0:
        raise DeployError(
            f"docker run on {host} failed (exit {started.returncode}): "
            f"{(started.stderr.strip() or started.stdout.strip())[-1000:]}",
            EXIT_DEPLOY,
            hint=_rollback_guidance(ec2, host),
        )
    log(
        "waiting 3s before the status check (a container that crashes right "
        "after start still shows 'Up' at t=0)"
    )
    time.sleep(3)
    status = _container_status(ec2, host)
    if not status.startswith("Up"):
        logs = _ssh_run(
            ec2,
            host,
            "sudo -n docker logs --tail 50 " + shlex.quote(ec2.container_name),
            capture=True,
            check=False,
            timeout=60,
        )
        tail = (logs.stdout.strip() + "\n" + logs.stderr.strip()).strip()[-2000:]
        raise DeployError(
            f"container {ec2.container_name} on {host} is not Up "
            f"(status: {status or 'gone'}); last log lines:\n{tail}",
            EXIT_DEPLOY,
            hint=_rollback_guidance(ec2, host),
        )
    log(f">>> on {host}: container status: {status}")


# --------------------------------------------------------------------------
# verify
# --------------------------------------------------------------------------


class _SshTunnel:
    """``ssh -v -N -L`` with liveness checks and guaranteed cleanup — the
    SSH sibling of the k8s target's _PortForward.

    ssh binds the local port only AFTER authentication, so "the port
    answers" is never proof that ssh owns it. Squatter defense is therefore
    two layers: (1) the constructor bind-probes 127.0.0.1:<local_tunnel_port>
    and refuses to spawn ssh while anything already listens there —
    otherwise a pre-existing listener would answer the first probes during
    the auth window with convincing but fake results; (2) the tunnel runs
    with -v, and wait_until_forwarding() requires ssh's own "Local
    forwarding listening on 127.0.0.1 port N" line in the captured log (the
    SSH equivalent of _PortForward's 'Forwarding from' gate) before any TCP
    connect is trusted, re-checking alive() around every probe — this also
    covers a squatter that grabs the port in the gap between the bind-probe
    and ssh's own bind, because ssh then dies (ExitOnForwardFailure=yes) or
    never prints the ownership line. ExitOnForwardFailure stays
    load-bearing for exactly that reason: without it ssh keeps running when
    the forward fails; with it, process death fails fast with the captured
    stderr. The IPv4-pinned -L spec closes the variant where ssh stays
    alive on an IPv6-only bind while an IPv4 squatter answers 127.0.0.1.
    """

    def __init__(self, ec2: Ec2Config, host: str) -> None:
        self._ec2 = ec2
        self._host = host
        # Layer 1: refuse to spawn while the local port is taken. The probe
        # sets SO_REUSEADDR (like ssh's own listener) so a previous host's
        # tunnel socket lingering in TIME_WAIT does not false-positive, but
        # an ACTIVE listener still fails the bind.
        probe = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        try:
            probe.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
            probe.bind(("127.0.0.1", ec2.local_tunnel_port))
        except OSError as exc:
            raise DeployError(
                f"local port {ec2.local_tunnel_port} is already in use "
                f"({exc}) — refusing to start the SSH tunnel: ssh binds the "
                "port only after authentication, so whatever is listening "
                "there now would answer the verification probes instead of "
                "the service (convincing but fake results)",
                EXIT_VERIFY,
                hint="free the local port, or change ec2.local_tunnel_port",
            ) from None
        finally:
            probe.close()
        # Not a context manager on purpose: the file must outlive this
        # constructor (ssh writes to it until close()).
        self._log = tempfile.NamedTemporaryFile(  # noqa: SIM115
            mode="w+", prefix="bentoml-deploy-ec2-tunnel-", suffix=".log", delete=False
        )
        self._proc = subprocess.Popen(
            [
                *_ssh_base(ec2),
                "-o",
                "ExitOnForwardFailure=yes",
                # -v is load-bearing: it makes ssh print the "Local
                # forwarding listening ..." line that wait_until_forwarding
                # requires as ownership evidence.
                "-v",
                "-N",
                "-L",
                # Explicit IPv4 bind address: without it ssh also binds ::1,
                # and an IPv4-only squatter would leave ssh alive (IPv6 bind
                # ok) while our 127.0.0.1 probes hit the squatter.
                f"127.0.0.1:{ec2.local_tunnel_port}:127.0.0.1:{ec2.host_port}",
                f"{ec2.ssh_user}@{host}",
            ],
            stdin=subprocess.DEVNULL,
            stdout=self._log,
            stderr=self._log,
            text=True,
        )

    def alive(self) -> bool:
        return self._proc.poll() is None

    def wait_until_forwarding(self, timeout_seconds: float) -> None:
        deadline = time.monotonic() + timeout_seconds
        while time.monotonic() < deadline:
            if not self.alive():
                raise DeployError(
                    f"SSH tunnel to {self._host} exited before forwarding:\n"
                    + self.captured_output(),
                    EXIT_VERIFY,
                    hint=f"is local port {self._ec2.local_tunnel_port} free "
                    "(ec2.local_tunnel_port), and does BatchMode "
                    f"SSH to {self._host} work?",
                )
            # Ownership evidence first: ssh binds the local port only AFTER
            # authentication, so a bare TCP connect during the auth window
            # could be answered by a squatter. Require ssh's own -v banner
            # before trusting any connect.
            if "Local forwarding listening" not in self.captured_output():
                time.sleep(0.2)
                continue
            try:
                conn = socket.create_connection(
                    ("127.0.0.1", self._ec2.local_tunnel_port), timeout=0.5
                )
            except OSError:
                time.sleep(0.2)
                continue
            conn.close()
            if self.alive():
                return
        raise DeployError(
            f"SSH tunnel to {self._host} did not start forwarding within "
            f"{timeout_seconds:.0f}s:\n" + self.captured_output(),
            EXIT_VERIFY,
        )

    def captured_output(self) -> str:
        try:
            with open(self._log.name, encoding="utf-8") as fh:
                return fh.read().strip()
        except OSError:
            return "(no tunnel output captured)"

    def close(self) -> None:
        if self._proc.poll() is None:
            self._proc.terminate()
            try:
                self._proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._proc.kill()
                self._proc.wait(timeout=5)
        self._log.close()
        try:
            Path(self._log.name).unlink()
        except OSError:
            pass


def verify(ctx: RunContext) -> None:
    ec2 = ctx.cfg.require_ec2()
    vcfg = ctx.cfg.verify
    for index, host in enumerate(ec2.hosts):
        started = time.monotonic()
        try:
            _verify_host(ec2, vcfg, host)
        except BaseException:
            ctx.summary.record_stage(
                f"ec2.verify[{host}]", False, time.monotonic() - started
            )
            for later in ec2.hosts[index + 1 :]:
                ctx.summary.record_stage(
                    f"ec2.verify[{later}]",
                    False,
                    0.0,
                    detail="not attempted (fail-fast after a previous host failed)",
                )
            raise
        ctx.summary.record_stage(
            f"ec2.verify[{host}]", True, time.monotonic() - started
        )


def _verify_host(ec2: Ec2Config, vcfg: VerifyConfig, host: str) -> None:
    if ec2.verify_via == "direct":
        base_url = f"http://{host}:{ec2.host_port}"
        section(f"verify {host}: /readyz direct on {base_url}")
        # A direct probe cannot prove WHO answered — re-check over SSH that
        # our container is the process behind the port before trusting HTTP.
        status = _container_status(ec2, host)
        if not status.startswith("Up"):
            raise DeployError(
                f"container {ec2.container_name} on {host} is not Up "
                f"(status: {status or 'gone'}) — direct HTTP results would "
                "be meaningless",
                EXIT_VERIFY,
                hint=_rollback_guidance(ec2, host),
            )
        _wait_ready(ec2, host, base_url, vcfg.readyz_timeout_seconds, None)
        if vcfg.inference is None:
            log(
                "verify.inference is not configured — verification is /readyz "
                "only (add a verify.inference block to POST a real request)"
            )
        else:
            _inference_smoke(host, base_url, vcfg.inference, None)
        return
    base_url = f"http://127.0.0.1:{ec2.local_tunnel_port}"
    section(f"verify {host}: /readyz via SSH tunnel on {base_url}")
    tunnel = _SshTunnel(ec2, host)
    try:
        tunnel.wait_until_forwarding(30)
        _wait_ready(ec2, host, base_url, vcfg.readyz_timeout_seconds, tunnel)
        if vcfg.inference is None:
            log(
                "verify.inference is not configured — verification is /readyz "
                "only (add a verify.inference block to POST a real request)"
            )
        else:
            _inference_smoke(host, base_url, vcfg.inference, tunnel)
    finally:
        tunnel.close()


def _wait_ready(
    ec2: Ec2Config,
    host: str,
    base_url: str,
    timeout_seconds: int,
    tunnel: _SshTunnel | None,
) -> None:
    deadline = time.monotonic() + timeout_seconds
    attempt = 0
    while True:
        if tunnel is not None and not tunnel.alive():
            raise DeployError(
                f"SSH tunnel to {host} exited unexpectedly:\n"
                + tunnel.captured_output(),
                EXIT_VERIFY,
                hint=f"is local port {ec2.local_tunnel_port} free "
                f"(ec2.local_tunnel_port), and is SSH to {host} stable?",
            )
        attempt += 1
        try:
            status, _ = http_get(base_url + "/readyz", timeout=3)
            if status == 200:
                if tunnel is not None and not tunnel.alive():
                    # The tunnel died — whatever answered was not our
                    # service. Never trust a probe the tunnel can't explain.
                    raise DeployError(
                        "SSH tunnel died during the readiness probe; the "
                        "200 response cannot be trusted:\n" + tunnel.captured_output(),
                        EXIT_VERIFY,
                    )
                log(f"/readyz on {host} returned 200 (attempt {attempt})")
                return
            log(f"/readyz returned {status} — retrying")
        except (urllib.error.URLError, OSError, ConnectionError) as exc:
            if attempt % 5 == 1:
                log(f"waiting for /readyz on {host} ({exc})")
        if time.monotonic() >= deadline:
            detail = ""
            if tunnel is not None:
                detail = f"; tunnel output:\n{tunnel.captured_output()}"
            else:
                detail = (
                    " (direct verify: the security group must allow port "
                    f"{ec2.host_port} from this machine's IP — set "
                    "ec2.verify_via to 'tunnel' if it does not)"
                )
            raise DeployError(
                f"service on {host} did not become ready within "
                f"{timeout_seconds}s{detail}",
                EXIT_VERIFY,
                hint=_rollback_guidance(ec2, host),
            )
        time.sleep(2)


def _inference_smoke(
    host: str, base_url: str, inference: InferenceCheck, tunnel: _SshTunnel | None
) -> None:
    url = base_url + inference.path
    log(f"inference smoke test on {host}: POST {inference.path}")
    if tunnel is not None and not tunnel.alive():
        raise DeployError(
            "SSH tunnel died before the inference request:\n"
            + tunnel.captured_output(),
            EXIT_VERIFY,
        )
    try:
        status, body = http_post_json(
            url, inference.body, timeout=inference.timeout_seconds
        )
    except (urllib.error.URLError, OSError) as exc:
        raise DeployError(
            f"inference request to {inference.path} on {host} failed: {exc}",
            EXIT_VERIFY,
        ) from None
    if tunnel is not None and not tunnel.alive():
        raise DeployError(
            "SSH tunnel died during the inference request; the response "
            "cannot be trusted:\n" + tunnel.captured_output(),
            EXIT_VERIFY,
        )
    snippet = body[:500].replace("\n", " ")
    log(f"response {status}: {snippet}")
    if not 200 <= status < 300:
        raise DeployError(
            f"inference smoke test returned HTTP {status} for "
            f"{inference.path} on {host} (body: {snippet})",
            EXIT_VERIFY,
            hint="check verify.inference.body against the service's "
            "@bentoml.api signature",
        )
    if inference.expect_substring and inference.expect_substring not in body:
        raise DeployError(
            f"inference response from {host} did not contain expected "
            f"substring {inference.expect_substring!r} (body: {snippet})",
            EXIT_VERIFY,
        )
    log("inference smoke test passed")
