"""Kubernetes target: render the manifests, apply them, wait for every service's
rollout in dependency order, and verify /readyz (plus an optional inference
smoke test) against the entry service through a port-forward.

Deployment model: one Kubernetes Deployment + Service per BentoML service THE
BENTO DECLARES; a single-service bento degenerates to exactly one of each. The
service list, the entry service and the dependency DAG come from the bento's own
bento.yaml (see _internal/topology.py) — config.yml only overrides per-service
details, so nothing here can contradict the code. Everything is applied in one
pass, then ``kubectl rollout status`` runs per service in the DERIVED rollout
order — a topological sort of that DAG, deepest dependencies first — because a
caller's /readyz fans out to its dependencies and 503s until they answer.
Verification only ever targets the entry service: inter-service payloads are
pickle and must not leave the cluster.

Cross-architecture builds are detected here too (k8s.node-arch): the cluster's
node architecture decides whether ``bentoml containerize`` needs
``--opt platform=linux/<arch>``, which is why v4 has no ``platform`` knob.

Image mechanism: the manifests are rendered in memory on every run
(_internal/render.py) with this run's image ref written straight into the
Deployments, and the result is piped to ``kubectl apply -f -``. Nothing is
written to disk, and re-applying the full set (rather than ``kubectl set
image``) also reconciles drift and recreates objects that were deleted.

Escape hatch: when ``kubernetes.manifests_dir`` is set, rendering is skipped
and the *.yaml files in that directory are applied VERBATIM — image reference
included. Nothing is substituted, so those files pin whatever tag they carry and
this run's built/passed image ref does NOT reach the pods unless the files name
it; the deploy log and the summary say when this path was taken, and preflight
warns when the pinned refs differ from the run's image. Those files are
hand-owned, so the preflight checks that police hand-written YAML stay active
for them; in the rendering path the same mistakes are impossible by
construction.

Generated by the bentoml-deploy-scriptgen skill — do not edit by hand; all
tunables live in config.yml.
"""

# This bundle gets committed into arbitrary user repos; the directive below
# keeps the import layout stable under any repo's ruff/isort configuration.
# isort: skip_file
from __future__ import annotations

import re
import subprocess
import tempfile
import time
import urllib.error
from datetime import datetime
from datetime import timezone
from pathlib import Path
from typing import TYPE_CHECKING

from ..arch import buildx_available
from ..arch import cluster_node_arches
from ..arch import decide_platform
from ..arch import docker_builder_arch
from ..common import EXIT_DEPLOY
from ..common import EXIT_VERIFY
from ..common import DeployError
from ..common import RunResult
from ..common import http_get
from ..common import http_post_json
from ..common import log
from ..common import run
from ..common import section
from ..common import warn
from ..config import PLACEHOLDER_RE
from ..config import REGISTRY_KIND_ECR
from ..config import InferenceCheck
from ..config import K8sConfig
from ..config import ServiceSpec
from ..config import yaml
from ..topology import unavailable_error
from ..preflight import ECR_PULL_SECRET_MAX_AGE
from ..preflight import CheckFailed
from ..preflight import _which
from ..preflight import parse_k8s_timestamp
from ..preflight import run_checks
from ..render import SERVE_DEPENDS_ENV
from ..render import render_all
from ..render import render_documents
from ..render import serve_depends_value

if TYPE_CHECKING:  # pragma: no cover - import cycle guard for type checkers
    from ..context import RunContext

# Never acceptable in a pod spec: the serving parent overwrites a runner map,
# and any dependency missing from the effective map is then instantiated
# IN-PROCESS with no log line and no readiness signal — the pod loads every
# model and still reports healthy.
RUNNER_MAP_ENVS = ("BENTOML_RUNNER_MAP", "BENTOML_SERVE_RUNNER_MAP")

# Prometheus counter every BentoML server exposes on :3000/metrics. Health
# probes are instrumented too, so samples for these endpoints are excluded
# when proving that an inter-service call really crossed the network: kubelet
# probes each pod every few seconds, and a gateway's /readyz fans out to its
# dependencies. Scraping /metrics itself is NOT counted (the metrics path
# short-circuits before the counter), so a before/after diff is meaningful.
REQUEST_TOTAL_METRIC = "bentoml_service_request_total"
HEALTH_ENDPOINTS = ("/readyz", "/livez", "/healthz", "/health", "/metrics")

# Prometheus exposition-format matchers for the dependency-metrics proof (the
# only text this module still parses by hand — /metrics is not YAML).
_METRIC_SAMPLE_RE = re.compile(
    r"^" + REQUEST_TOTAL_METRIC + r"(?:\{([^}]*)\})?[ \t]+([0-9eE.+-]+)[ \t]*$",
    re.M,
)
_LABEL_RE = re.compile(r'([A-Za-z_][A-Za-z0-9_]*)="((?:[^"\\]|\\.)*)"')


def _label_value(labels: str, name: str) -> str:
    for match in _LABEL_RE.finditer(labels or ""):
        if match.group(1) == name:
            return match.group(2)
    return ""


def _sum_request_total(body: str) -> float:
    """Sum bentoml_service_request_total across non-health endpoints. Health
    samples are excluded so kubelet probes and a gateway's readiness fan-out
    cannot be mistaken for an inference call."""
    total = 0.0
    for match in _METRIC_SAMPLE_RE.finditer(body):
        if _label_value(match.group(1) or "", "endpoint") in HEALTH_ENDPOINTS:
            continue
        try:
            total += float(match.group(2))
        except ValueError:
            continue
    return total


def _kubectl(k8s: K8sConfig, *args: str) -> list[str]:
    return ["kubectl", "--context", k8s.context, *args]


def _manifest_files(k8s: K8sConfig) -> list[Path]:
    """kubernetes.manifests_dir only: every *.yaml in that directory, in name
    order. The whole directory is applied, so a file that is present WILL be
    applied on the next run; deleting a file only stops applying it, it never
    deletes the object from the cluster."""
    if k8s.manifests_dir is None or not k8s.manifests_dir.is_dir():
        return []
    return sorted(
        p
        for p in k8s.manifests_dir.iterdir()
        if p.suffix in (".yaml", ".yml") and p.is_file()
    )


# --------------------------------------------------------------------------
# preflight
# --------------------------------------------------------------------------


def preflight(ctx: RunContext) -> None:
    """Standalone entry point: run this target's checks in one pass."""
    run_checks(preflight_checks(ctx))


def preflight_checks(ctx: RunContext) -> list:
    """Build this target's checks so deploy.py can aggregate them with the
    build-side families into a single report. With ctx.local_only, only
    checks that need no cluster connectivity are returned; the rest are
    recorded in the summary's skipped list."""
    k8s = ctx.cfg.require_k8s()

    def kubectl_cli() -> str | None:
        _which("kubectl", "install kubectl and configure access to the cluster")
        return None

    def context_reachable() -> str | None:
        res = run(
            _kubectl(k8s, "version", "--request-timeout=10s", "-o", "yaml"),
            capture=True,
            quiet=True,
            check=False,
            timeout=30,
        )
        if res.returncode != 0:
            raise CheckFailed(
                f"cluster for context {k8s.context!r} is not reachable: {(res.stderr.strip() or res.stdout.strip())[:300]}",
                hint="check the context name (kubectl config get-contexts), "
                "VPN/credentials, and that the cluster is up",
            )
        return f"context {k8s.context} reachable"

    def rbac() -> str | None:
        res = run(
            _kubectl(k8s, "auth", "can-i", "create", "deployment", "-n", k8s.namespace),
            capture=True,
            quiet=True,
            check=False,
            timeout=30,
        )
        if res.stdout.strip().lower() != "yes":
            raise CheckFailed(
                f"identity for context {k8s.context!r} may not create deployments in "
                f"namespace {k8s.namespace!r}",
                hint="ask a cluster admin for edit rights in the namespace, "
                "or fix kubernetes.namespace",
            )
        return None

    def namespace_exists() -> str | None:
        # Still required even though nothing renders a Namespace object: this
        # bundle never creates namespaces (a bundle that could would happily
        # create a typo'd one).
        res = run(
            _kubectl(k8s, "get", "namespace", k8s.namespace),
            capture=True,
            quiet=True,
            check=False,
            timeout=30,
        )
        if res.returncode != 0:
            raise CheckFailed(
                f"namespace {k8s.namespace!r} does not exist in context {k8s.context!r}",
                hint=f"kubectl --context {k8s.context} create namespace {k8s.namespace}",
            )
        return None

    def pull_secret() -> str | None:
        if not k8s.image_pull_secret:
            # Nothing named in config.yml. The pods will run under the
            # namespace's `default` serviceaccount, so credentials can still
            # come from that account's imagePullSecrets, or from the nodes
            # themselves (an EKS instance role with the ECR credential
            # provider, a kubelet docker config, or a public registry). None of
            # those can be proven from here, but the serviceaccount can be
            # read, and its absence is the single most common cause of a
            # rollout that dies of ImagePullBackOff after burning the whole
            # rollout timeout.
            sa = run(
                _kubectl(
                    k8s,
                    "get",
                    "serviceaccount",
                    "default",
                    "-n",
                    k8s.namespace,
                    "-o",
                    "jsonpath={.imagePullSecrets[*].name}",
                ),
                capture=True,
                quiet=True,
                check=False,
                timeout=30,
            )
            names = sa.stdout.split() if sa.returncode == 0 else []
            if names:
                return (
                    "none in config.yml; the namespace's default "
                    "serviceaccount supplies " + ", ".join(sorted(names))
                )
            host = ctx.cfg.image.registry or "docker.io"
            if ctx.cfg.image.kind == REGISTRY_KIND_ECR:
                warn(
                    f"no image pull secret: {host} is a private ECR registry, "
                    "which always requires authentication, and neither "
                    "kubernetes.image_pull_secret nor the namespace's default "
                    "serviceaccount names one. Unless the NODES carry ECR "
                    "credentials (an instance role plus the ECR credential "
                    "provider), every pod will fail with ImagePullBackOff. "
                    "Fix it either way:\n"
                    f"  kubectl --context {k8s.context} -n {k8s.namespace} "
                    "create secret docker-registry ecr-creds "
                    f"--docker-server={host} --docker-username=AWS "
                    '--docker-password="$(aws ecr get-login-password '
                    f'--region {ctx.cfg.image.ecr_region or "<region>"})"\n'
                    "then set kubernetes.image_pull_secret: ecr-creds (an ECR "
                    "token expires after 12 h — recreate the secret or give "
                    "the nodes a credential provider for anything long-lived)"
                )
            elif ctx.cfg.image.pushes:
                warn(
                    "no image pull secret: neither kubernetes.image_pull_secret "
                    "nor the namespace's default serviceaccount names one, so "
                    f"the cluster must be able to pull {host} anonymously or "
                    "with node-level credentials. If it cannot, the pods fail "
                    "with ImagePullBackOff (create a docker-registry secret "
                    "and set kubernetes.image_pull_secret)"
                )
            return "no image pull secret configured"
        res = run(
            _kubectl(
                k8s,
                "get",
                "secret",
                k8s.image_pull_secret,
                "-n",
                k8s.namespace,
                "-o",
                "jsonpath={.metadata.creationTimestamp}",
            ),
            capture=True,
            quiet=True,
            check=False,
            timeout=30,
        )
        if res.returncode != 0:
            raise CheckFailed(
                f"image pull secret {k8s.image_pull_secret!r} not found in namespace {k8s.namespace!r}",
                hint=f"kubectl --context {k8s.context} create secret docker-registry {k8s.image_pull_secret} "
                f"-n {k8s.namespace} --docker-server=... --docker-username=... "
                "--docker-password=...",
            )
        if ctx.cfg.image.kind == REGISTRY_KIND_ECR:
            created = parse_k8s_timestamp(res.stdout)
            if created is not None:
                age = datetime.now(timezone.utc) - created
                if age > ECR_PULL_SECRET_MAX_AGE:
                    warn(
                        f"ECR pull secret {k8s.image_pull_secret!r} is {age.total_seconds() / 3600:.1f} h old — ECR tokens expire "
                        "after 12 h, so image pulls will likely fail. "
                        "Delete and recreate the secret with a fresh "
                        "'aws ecr get-login-password' (kubectl apply keeps "
                        "the original creationTimestamp, so recreating is "
                        "the only way this check can see it as fresh). Note "
                        "this age check is a heuristic: it cannot detect a "
                        "recently created secret that embeds an "
                        "already-expired token."
                    )
        return None

    def topology_source() -> str | None:
        """Report where the bento's service topology came from — or why there
        is none yet. config.yml carries no service list, no entry service and
        no `depends`: they are read from the bento's own bento.yaml (see
        _internal/topology.py) out of the local bento store, the image, or the
        cache next to config.yml."""
        topo = ctx.cfg.topology
        if topo is not None:
            return f"{topo.describe()} — from the {topo.source}"
        if ctx.skip_build:
            # Nothing later in this run will produce it: --skip-build means no
            # bento is built, so the store cannot answer either.
            err = unavailable_error(ctx.cfg.bundle_dir, ctx.image)
            raise CheckFailed(str(err), hint=err.hint)
        warn(
            "the service topology is not available yet — it will be read from "
            "the bento this run builds. Until then there is nothing to render, "
            "so k8s.render and k8s.rollout-plan are skipped this time. Commit "
            "the .bento-topology.json cache (or run once with --skip-build "
            "against the built image) to get those checks in a build-free run."
        )
        return "UNRESOLVED — will come from the bento built by this run"

    def node_arch() -> str | None:
        """Cross-architecture detection, the replacement for v3's
        `image.platform`: compare the builder's architecture with the cluster
        nodes' `kubernetes.io/arch` and, when they differ, build for the nodes'
        (an image of the wrong architecture starts and then dies with 'exec
        format error', burning the whole rollout timeout in CrashLoopBackOff).
        """
        builder = docker_builder_arch()
        arches = cluster_node_arches(k8s.context)
        decision = decide_platform(builder, arches, "cluster nodes")
        if decision.cross and not buildx_available():
            raise CheckFailed(
                f"a cross-architecture build is needed ({decision.message}) "
                "but docker buildx is not available",
                hint="install the docker buildx plugin (it ships with Docker "
                "Desktop; on Debian/Ubuntu: the docker-buildx-plugin package). "
                "BuildKit is what honours the platform flag — without it the "
                "image would be built for the wrong architecture and every pod "
                "would die with 'exec format error'.",
            )
        if decision.mixed:
            warn(decision.message)
        if decision.cross:
            ctx.build_platform = decision.platform
            log(f"  cross-arch build enabled: --opt platform={decision.platform}")
        return decision.message

    # ---- rendering path ---------------------------------------------------

    def render_ok() -> str | None:
        """Render the manifests exactly as the deploy would and prove the
        result is well-formed YAML. Cheap, credential-free, and it is also the
        check that the config renders AT ALL before anything is built."""
        image = ctx.image or "pending/unresolved:image"
        docs = render_documents(ctx.cfg, image)
        if yaml is not None:
            for doc in docs:
                try:
                    parsed = yaml.safe_load(doc.text)
                except yaml.YAMLError as exc:
                    raise CheckFailed(
                        f"rendered {doc.kind}/{doc.name} is not valid YAML: {exc}",
                        hint="this is a bug in the bundle, not in your config "
                        "— report it with the config.yml that triggered it "
                        "(see it with --render-only)",
                    ) from None
                if not isinstance(parsed, dict) or "kind" not in parsed:
                    raise CheckFailed(
                        f"rendered {doc.filename} is not a Kubernetes object",
                        hint="this is a bug in the bundle, not in your config",
                    )
        kinds: dict[str, int] = {}
        for doc in docs:
            kinds[doc.kind] = kinds.get(doc.kind, 0) + 1
        summary = ", ".join(f"{count} {kind}" for kind, count in sorted(kinds.items()))
        return f"{summary} rendered from config.yml"

    def rollout_plan() -> str | None:
        """Report the DERIVED rollout order and the dependency wiring EXACTLY as
        it will be emitted, so a wrong `depends:` — or a hand-written
        BENTOML_SERVE_DEPENDS that replaces it — is visible before the deploy
        rather than after."""
        wired = 0
        for svc in k8s.services:
            raw = svc.env.get(SERVE_DEPENDS_ENV)
            if raw is not None:
                # The raw value REPLACES the derived one (the loader validated
                # its syntax and that it covers `depends`). Print what the pod
                # actually gets, never the value that is not emitted.
                wired += 1
                log(f"    {svc.name} -> {raw}   [raw, from services.{svc.name}.env]")
                continue
            if not svc.depends:
                continue
            wired += 1
            value = serve_depends_value(k8s, svc)
            for pair in value.split():
                # Belt-and-braces on the renderer's own output: a URL with a
                # '=' in it raises at BentoML startup, and a comma-separated
                # value makes the dependency silently in-process.
                if pair.count("=") != 1:
                    raise CheckFailed(
                        f"{svc.name}: {SERVE_DEPENDS_ENV} pair {pair!r} does "
                        "not have exactly one '='",
                        hint="a slug or namespace containing '=' cannot be "
                        "expressed — fix services.<name>.slug / "
                        "kubernetes.namespace",
                    )
            log(f"    {svc.name} -> {value}")
        order = " -> ".join(f"{svc.name} ({svc.slug})" for svc in k8s.services)
        return (
            f"rollout order {order}; {wired} service(s) wired via {SERVE_DEPENDS_ENV}"
        )

    # ---- kubernetes.manifests_dir path (hand-owned YAML) ------------------
    #
    # These files are applied verbatim, so every invariant the renderer
    # guarantees has to be re-checked here. The checks are STRUCTURAL (PyYAML is
    # a hard requirement of this bundle anyway): a regex over lines can only see
    # the file it was pointed at, and the fault that matters most — an extra
    # file exposing a dependency's pods — lives in a file no per-service naming
    # convention would ever name.

    def _objects() -> list[tuple[Path, int, dict]]:
        """Every Kubernetes object in the directory, as (file, doc index, obj).
        Multi-document files included; a parse failure is a check failure (the
        apply would fail on it anyway, after other objects were created)."""
        out: list[tuple[Path, int, dict]] = []
        for path in _manifest_files(k8s):
            text = path.read_text(encoding="utf-8")
            if PLACEHOLDER_RE.search(text):
                raise CheckFailed(
                    f"unreplaced {{{{PLACEHOLDER}}}} values remain in {path.name}",
                    hint="regenerate the manifests with --render-only (after "
                    "unsetting kubernetes.manifests_dir), or fill them in",
                )
            try:
                docs = list(yaml.safe_load_all(text))
            except yaml.YAMLError as exc:
                raise CheckFailed(
                    f"{path.name} is not valid YAML: {exc}",
                    hint="kubectl apply would reject it — after having already "
                    "created the objects from the files before it",
                ) from None
            for index, doc in enumerate(docs, start=1):
                if doc is None:  # a trailing '---' or a comment-only document
                    continue
                if not isinstance(doc, dict) or "kind" not in doc:
                    where = path.name if index == 1 else f"{path.name} (doc {index})"
                    raise CheckFailed(
                        f"{where} is not a Kubernetes object (no 'kind')",
                        hint="every document in this directory is applied; "
                        "remove the file or the stray document",
                    )
                out.append((path, index, doc))
        return out

    def _where(path: Path, index: int) -> str:
        return path.name if index == 1 else f"{path.name} (document {index})"

    def _meta(obj: dict) -> dict:
        meta = obj.get("metadata")
        return meta if isinstance(meta, dict) else {}

    def _pod_spec(obj: dict) -> dict | None:
        """The PodSpec of a workload object, whatever wraps it."""
        spec = obj.get("spec")
        if not isinstance(spec, dict):
            return None
        if obj.get("kind") == "Pod":
            return spec
        template = spec.get("template")
        if isinstance(template, dict) and isinstance(template.get("spec"), dict):
            return template["spec"]
        return None

    def _containers(obj: dict) -> list[dict]:
        pod = _pod_spec(obj)
        if pod is None:
            return []
        out: list[dict] = []
        for key in ("initContainers", "containers"):
            for item in pod.get(key) or []:
                if isinstance(item, dict):
                    out.append(item)
        return out

    def manifests_present() -> str | None:
        files = _manifest_files(k8s)
        if not files:
            # The directory exists (the loader checked) but holds no manifests.
            raise CheckFailed(
                f"kubernetes.manifests_dir ({k8s.manifests_dir}) contains no "
                "*.yaml or *.yml files",
                hint="unset kubernetes.manifests_dir to render the manifests "
                "from config.yml instead (the normal mode), or populate the "
                "directory — `deploy.py --target k8s --render-only DIR` writes "
                "a correct starting point (unset manifests_dir first, then set "
                "it back).",
            )
        objects = _objects()
        # One Deployment + one Service OBJECT per configured service — by name,
        # not by file name: the rollout waits on deployment/<slug> and verify
        # port-forwards to svc/<slug>, so those two objects must exist. How they
        # are split across files is the user's business.
        present = {(obj.get("kind"), _meta(obj).get("name")) for _, _, obj in objects}
        missing = [
            f"{kind}/{svc.slug}"
            for svc in k8s.services
            for kind in ("Deployment", "Service")
            if (kind, svc.slug) not in present
        ]
        if missing:
            raise CheckFailed(
                f"no object for {', '.join(missing)} in {k8s.manifests_dir}",
                hint="every service in config.yml's `services:` needs a "
                "Deployment and a Service named after its slug (the rollout "
                "waits on deployment/<slug>, verify port-forwards to "
                "svc/<slug>). Re-render with --render-only, or fix the slugs.",
            )
        # Every object must DECLARE the configured namespace. An object with no
        # namespace: lands in whatever namespace the kubeconfig points at, while
        # rollout status -n <ns> watches somewhere else.
        for path, index, obj in objects:
            declared = _meta(obj).get("namespace")
            kind_name = f"{obj.get('kind')}/{_meta(obj).get('name')}"
            if not declared:
                raise CheckFailed(
                    f"{_where(path, index)}: {kind_name} declares no "
                    "metadata.namespace",
                    hint=f"add 'namespace: {k8s.namespace}' — without it the "
                    "object goes to the kubeconfig's current namespace, which "
                    "is not necessarily kubernetes.namespace",
                )
            if declared != k8s.namespace:
                raise CheckFailed(
                    f"{_where(path, index)}: {kind_name} declares namespace "
                    f"{declared!r} but kubernetes.namespace is "
                    f"{k8s.namespace!r}",
                    hint="fix the manifest, or fix kubernetes.namespace — "
                    "deploying across namespaces would roll out in one place "
                    "and verify another",
                )
        # Every container of our Deployments must name an image. The files are
        # applied verbatim, so the ref they carry is what runs — worth saying
        # out loud when it is not the ref this run resolved.
        pinned: list[str] = []
        slugs = {svc.slug for svc in k8s.services}
        for path, index, obj in objects:
            if obj.get("kind") != "Deployment" or _meta(obj).get("name") not in slugs:
                continue
            containers = _containers(obj)
            refs = [str(c.get("image")) for c in containers if c.get("image")]
            if not refs:
                raise CheckFailed(
                    f"{_where(path, index)}: Deployment/"
                    f"{_meta(obj).get('name')} has no container image",
                    hint="kubernetes.manifests_dir files are applied verbatim, "
                    "so each Deployment must name the image it should run. "
                    "`--render-only DIR` writes a correct starting point.",
                )
            pinned += refs
        drifted = sorted({ref for ref in pinned if ctx.image and ref != ctx.image})
        if drifted:
            warn(
                "kubernetes.manifests_dir is set, so the manifests are applied "
                f"verbatim: they pin {drifted} while this run resolved "
                f"{ctx.image!r}. The pinned refs are what will run — update "
                "them (or unset manifests_dir to render from config.yml) if "
                "that is not what you meant."
            )
        # An HPA owns the replica count. Because every run re-applies the whole
        # directory, a Deployment that also declares spec.replicas resets the
        # count on each deploy and then fights the autoscaler.
        deployments = {
            _meta(obj).get("name"): (path, index, obj)
            for path, index, obj in objects
            if obj.get("kind") == "Deployment"
        }
        hpas = 0
        for path, index, obj in objects:
            if obj.get("kind") != "HorizontalPodAutoscaler":
                continue
            hpas += 1
            spec = obj.get("spec") if isinstance(obj.get("spec"), dict) else {}
            target = spec.get("scaleTargetRef")
            name = target.get("name") if isinstance(target, dict) else None
            owned = deployments.get(name)
            if owned is None:
                warn(
                    f"{_where(path, index)}: HPA targets "
                    f"{name!r}, which is not a Deployment in this directory"
                )
                continue
            dep_spec = owned[2].get("spec")
            if isinstance(dep_spec, dict) and dep_spec.get("replicas") is not None:
                raise CheckFailed(
                    f"{_where(path, index)} scales Deployment/{name}, but "
                    f"{_where(owned[0], owned[1])} still declares "
                    f"replicas: {dep_spec['replicas']}",
                    hint="delete the replicas: line from the Deployment (or "
                    "the HPA). This script re-applies the whole manifests dir "
                    "on every run, so a declared replicas: resets the count "
                    "the HPA just chose and the two fight after every deploy.",
                )
        note = (
            f"{len(files)} hand-owned file(s), {len(objects)} object(s), "
            f"{len(k8s.services)} service(s)"
        )
        if hpas:
            note += f", {hpas} HPA(s) (applied too)"
        return note

    def serve_depends() -> str | None:
        """Prove, statically, that each dependency edge is wired over the
        network in the hand-owned manifests.

        An unmapped dependency is NOT an error at runtime: BentoML silently
        instantiates it IN-PROCESS (no log line), the caller's /readyz skips it
        entirely, and the inference smoke test returns a correct answer from a
        pod that loaded every model. Nothing observable at deploy time
        distinguishes that from a working split — except the manifests.
        """
        objects = _objects()
        pairs: dict[str, str] = {}  # pair -> where it was declared
        for path, index, obj in objects:
            for container in _containers(obj):
                for entry in container.get("env") or []:
                    if not isinstance(entry, dict):
                        continue
                    name = entry.get("name")
                    if name in RUNNER_MAP_ENVS:
                        raise CheckFailed(
                            f"{_where(path, index)} sets {name}",
                            hint="never set a runner map on a pod: the serving "
                            "parent overwrites it, and any dependency missing "
                            "from the effective map is instantiated in-process "
                            "with no log — the pod loads every model and still "
                            f"reports ready. Use {SERVE_DEPENDS_ENV} instead.",
                        )
                    if name != SERVE_DEPENDS_ENV:
                        continue
                    value = entry.get("value")
                    if value is None:
                        raise CheckFailed(
                            f"{_where(path, index)}: {SERVE_DEPENDS_ENV} has no "
                            "literal value",
                            hint="a valueFrom/ConfigMap indirection cannot be "
                            "checked here, and an unwired dependency fails "
                            "silently — set the value inline",
                        )
                    for pair in str(value).split():
                        if "," in pair:
                            raise CheckFailed(
                                f"{_where(path, index)}: {SERVE_DEPENDS_ENV} "
                                f"pair {pair!r} contains a comma",
                                hint="pairs are separated by WHITESPACE, not "
                                "commas — a comma becomes part of the URL and "
                                "the dependency is then silently served "
                                "in-process",
                            )
                        if pair.count("=") != 1:
                            raise CheckFailed(
                                f"{_where(path, index)}: {SERVE_DEPENDS_ENV} "
                                f"pair {pair!r} has {pair.count('=')} '=' "
                                "characters, expected exactly one",
                                hint="each pair is Name=URL and BentoML splits "
                                "on '=', so a URL containing '=' (a query "
                                "string) raises at startup; a pair with none "
                                "is ignored",
                            )
                        pairs.setdefault(pair, _where(path, index))
        # One expected pair per dependency EDGE in config.yml's `services:`.
        expected: dict[str, str] = {}
        for svc in k8s.services:
            for pair in serve_depends_value(k8s, svc).split():
                expected[pair] = svc.name
        for pair, caller in sorted(expected.items()):
            if pair not in pairs:
                raise CheckFailed(
                    f"no Deployment wires {pair!r} (needed by {caller}), found "
                    + (f"{sorted(pairs)}" if pairs else "no pairs at all"),
                    hint="the depending service's Deployment must carry "
                    f"{SERVE_DEPENDS_ENV} with one Name=URL pair per direct "
                    "dependency, keyed on the exact BentoML service name. "
                    "Without it the dependency is instantiated in-process: the "
                    "pod loads every model, /readyz still returns 200 and "
                    "inference still answers correctly. Re-render with "
                    "--render-only and copy the env block.",
                )
        unknown = sorted(
            pair
            for pair in pairs
            if pair.split("=", 1)[0] not in {svc.name for svc in k8s.services}
        )
        if unknown:
            warn(
                f"{SERVE_DEPENDS_ENV} names service(s) that are not in "
                f"config.yml's `services:`: {unknown} — a typo here is "
                "silently served in-process (dependency lookup keys on the "
                "exact BentoML service name)"
            )
        if not expected:
            return "no dependency edges to wire"
        return f"{len(expected)} dependency edge(s) wired over the network"

    def service_exposure() -> str | None:
        """No object in the directory may publish a dependency's port.

        Inter-service payloads are unauthenticated
        application/vnd.bentoml+pickle, so anything that can reach a
        dependency's port can execute code in that pod. Checking only the
        <slug>-service.yaml files would miss exactly the file that does this by
        accident: a second Service (or an Ingress) that selects a dependency's
        pods from some other file, which is applied just the same.
        """
        objects = _objects()
        dependency_targets = {svc.slug for svc in k8s.dependencies} | {
            svc.name for svc in k8s.dependencies
        }
        entry_slug = k8s.entry_service.slug
        checked = 0
        for path, index, obj in objects:
            kind = obj.get("kind")
            spec = obj.get("spec") if isinstance(obj.get("spec"), dict) else {}
            name = _meta(obj).get("name")
            if kind == "Service":
                selector = spec.get("selector")
                selected = (
                    {str(value) for value in selector.values()}
                    if isinstance(selector, dict)
                    else set()
                )
                hits = sorted(selected & dependency_targets)
                if not hits:
                    continue
                checked += 1
                svc_type = spec.get("type", "ClusterIP")
                if svc_type != "ClusterIP":
                    raise CheckFailed(
                        f"{_where(path, index)}: Service/{name} selects "
                        f"dependency pods ({', '.join(hits)}) but is "
                        f"type: {svc_type}",
                        hint="dependency Services must be ClusterIP. "
                        "Inter-service traffic is unauthenticated pickle, so "
                        "anything that can reach the port can execute code in "
                        f"the pod. Only the entry service (svc/{entry_slug}) "
                        "may be exposed.",
                    )
                node_ports = [
                    port.get("nodePort")
                    for port in spec.get("ports") or []
                    if isinstance(port, dict) and port.get("nodePort")
                ]
                if node_ports:
                    raise CheckFailed(
                        f"{_where(path, index)}: Service/{name} selects "
                        f"dependency pods ({', '.join(hits)}) and declares "
                        f"nodePort: {node_ports[0]}",
                        hint="a nodePort publishes the pickle port on every "
                        "cluster node. Remove it — only the entry service may "
                        "be exposed.",
                    )
            elif kind == "Ingress":
                backends: list[str] = []
                default = spec.get("defaultBackend")
                if isinstance(default, dict) and isinstance(
                    default.get("service"), dict
                ):
                    backends.append(str(default["service"].get("name")))
                for rule in spec.get("rules") or []:
                    http = rule.get("http") if isinstance(rule, dict) else None
                    for entry in (http or {}).get("paths") or []:
                        backend = (
                            entry.get("backend") if isinstance(entry, dict) else None
                        )
                        service = (backend or {}).get("service")
                        if isinstance(service, dict):
                            backends.append(str(service.get("name")))
                hits = sorted(set(backends) & dependency_targets)
                if hits:
                    raise CheckFailed(
                        f"{_where(path, index)}: Ingress/{name} routes to "
                        f"dependency service(s) {', '.join(hits)}",
                        hint="an Ingress for a dependency publishes an "
                        "unauthenticated pickle endpoint (remote code "
                        f"execution). Route to the entry service ({entry_slug}) "
                        "only.",
                    )
                checked += 1
        return (
            f"{len(k8s.dependencies)} dependency service(s) unexposed "
            f"({checked} selecting object(s) inspected)"
        )

    checks = [("k8s.kubectl-cli", kubectl_cli), ("k8s.topology", topology_source)]
    if ctx.local_only:
        ctx.summary.skipped += [
            "k8s.context-reachable (--local-only)",
            "k8s.rbac-create-deployment (--local-only)",
            "k8s.namespace (--local-only)",
            "k8s.image-pull-secret (--local-only)",
            "k8s.node-arch (--local-only: needs the cluster's node labels)",
        ]
    else:
        checks += [
            ("k8s.context-reachable", context_reachable),
            ("k8s.rbac-create-deployment", rbac),
            ("k8s.namespace", namespace_exists),
            ("k8s.image-pull-secret", pull_secret),
        ]
        if ctx.skip_build:
            ctx.summary.skipped.append(
                "k8s.node-arch (--skip-build: nothing is built, so no "
                "platform to choose)"
            )
        else:
            checks.append(("k8s.node-arch", node_arch))
    if not k8s.bound:
        # No topology yet (a build-first run with no cache): everything below
        # needs the service list. k8s.topology above already said so.
        ctx.summary.skipped += [
            "k8s.render (topology not yet discovered)",
            "k8s.rollout-plan (topology not yet discovered)",
        ]
        if k8s.manifests_dir is not None:
            ctx.summary.skipped += [
                "k8s.manifests (topology not yet discovered)",
                "k8s.serve-depends (topology not yet discovered)",
                "k8s.service-exposure (topology not yet discovered)",
            ]
        return checks
    # The manifest checks need no cluster: they run under --local-only too.
    if k8s.manifests_dir is None:
        # Rendering path. The checks that used to police hand-written YAML
        # (image sentinel, namespace consistency, serve-depends wiring,
        # non-entry ClusterIP, HPA-vs-replicas) are impossible to fail here:
        # the renderer writes the image ref and the namespace into every
        # object, derives BENTOML_SERVE_DEPENDS from `depends`, forces
        # ClusterIP on non-entry Services, and omits spec.replicas whenever it
        # emits an HPA. What is left to check is that the config renders and
        # that the derived plan is what the user expects.
        checks.append(("k8s.render", render_ok))
        checks.append(("k8s.rollout-plan", rollout_plan))
    else:
        checks.append(("k8s.manifests", manifests_present))
        checks.append(("k8s.serve-depends", serve_depends))
        if len(k8s.services) > 1:
            checks.append(("k8s.service-exposure", service_exposure))
    return checks


# --------------------------------------------------------------------------
# deploy
# --------------------------------------------------------------------------


def _manifests_dir_text(k8s: K8sConfig) -> tuple[str, int]:
    """kubernetes.manifests_dir: the files concatenated VERBATIM. No
    substitution of any kind — those files are the source of truth, image
    reference included."""
    docs: list[str] = []
    files = _manifest_files(k8s)
    for path in files:
        docs.append(path.read_text(encoding="utf-8").rstrip() + "\n")
    return "---\n".join(docs), len(files)


def _role(svc: ServiceSpec) -> str:
    return "entry" if svc.entry else "dependency"


def _rollback_guidance(k8s: K8sConfig) -> str:
    """Diagnosis + rollback commands naming EVERY deployment: one bad
    dependency takes the whole bento down, so a partial list would send the
    user looking in the wrong pod."""
    base = f"kubectl --context {k8s.context} -n {k8s.namespace}"
    lines = [f"Diagnose ({len(k8s.services)} deployment(s), one per service):"]
    for svc in k8s.services:
        lines.append(f"  # {svc.name} ({_role(svc)})")
        lines.append(f"  {base} get pods -l app.kubernetes.io/name={svc.slug}")
        lines.append(f"  {base} describe deployment/{svc.slug}")
        lines.append(f"  {base} logs deployment/{svc.slug} --all-containers --tail=100")
    lines.append("Roll back to the previous revision (dependencies first, entry last):")
    for svc in k8s.services:
        lines.append(f"  {base} rollout undo deployment/{svc.slug}")
        lines.append(
            f"  {base} rollout status deployment/{svc.slug}"
            f" --timeout={k8s.rollout_timeout_seconds}s"
        )
    lines.append("(or re-run this script with --image <previous-ref>)")
    if len(k8s.services) > 1:
        lines.append(
            "Note: a caller's /readyz fans out to its dependencies, so it "
            "stays 503 (and its pods stay unready) until every dependency "
            "answers — diagnose the deepest dependencies first."
        )
    return "\n".join(lines)


def deploy(ctx: RunContext) -> None:
    k8s = ctx.cfg.require_k8s()
    started = time.monotonic()
    if k8s.manifests_dir is None:
        section(
            f"deploy: render config.yml + kubectl apply (context={k8s.context} "
            f"namespace={k8s.namespace} services={len(k8s.services)} "
            f"image={ctx.image})"
        )
        rendered = render_all(ctx.cfg, str(ctx.image))
        objects = len(render_documents(ctx.cfg, str(ctx.image)))
        source = f"rendered {objects} object(s) from config.yml"
        log(f"{source} (see them with --render-only)")
    else:
        section(
            f"deploy: kubectl apply of {k8s.manifests_dir} AS-IS "
            f"(kubernetes.manifests_dir is set — config.yml does NOT drive the "
            f"workload shape; context={k8s.context} namespace={k8s.namespace} "
            f"image={ctx.image})"
        )
        rendered, count = _manifests_dir_text(k8s)
        if not rendered.strip():
            raise DeployError(
                f"no manifests to apply in {k8s.manifests_dir}",
                EXIT_DEPLOY,
                hint="unset kubernetes.manifests_dir to render from config.yml",
            )
        source = (
            f"applied {count} file(s) from {k8s.manifests_dir} VERBATIM "
            "(kubernetes.manifests_dir) — the image refs in those files are "
            f"what runs; this run's image ({ctx.image}) was NOT substituted"
        )
        log(source)
    # -n is belt-and-braces: every object declares this namespace anyway, and
    # kubectl rejects a mismatch rather than silently splitting the deploy
    # across two namespaces.
    res = run(
        _kubectl(k8s, "apply", "-n", k8s.namespace, "-f", "-"),
        input_text=rendered,
        capture=True,
        check=False,
    )
    for line in (res.stdout.strip() + "\n" + res.stderr.strip()).splitlines():
        if line:
            log("  " + line)
    if res.returncode != 0:
        ctx.summary.record_stage(
            "k8s.apply", False, time.monotonic() - started, detail=source
        )
        raise DeployError(
            f"kubectl apply failed (exit {res.returncode})",
            EXIT_DEPLOY,
            hint=_rollback_guidance(k8s),
        )
    ctx.summary.record_stage(
        "k8s.apply", True, time.monotonic() - started, detail=source
    )

    _wait_for_rollouts(ctx, k8s)


def _wait_for_rollouts(ctx: RunContext, k8s: K8sConfig) -> None:
    """`kubectl rollout status` per service in the derived rollout order
    (deepest dependencies first) with the configured timeout each, fail-fast.
    Every service gets its own k8s.rollout[<slug>] stage in the summary."""
    log(
        f"waiting for {len(k8s.services)} rollout(s) in dependency order "
        f"(deepest dependencies first, entry last; timeout "
        f"{k8s.rollout_timeout_seconds}s each)..."
    )
    for index, svc in enumerate(k8s.services):
        started = time.monotonic()
        log(f"rollout {index + 1}/{len(k8s.services)}: {svc.name} ({_role(svc)})")
        rollout, fatal = _rollout_status(k8s, svc)
        if rollout.returncode != 0:
            ctx.summary.record_stage(
                _rollout_stage(svc), False, time.monotonic() - started
            )
            for later in k8s.services[index + 1 :]:
                ctx.summary.record_stage(
                    _rollout_stage(later),
                    False,
                    0.0,
                    detail="not attempted (fail-fast after an earlier "
                    "service's rollout failed)",
                )
            if fatal:
                raise DeployError(
                    f"rollout of deployment/{svc.slug} (BentoML service "
                    f"{svc.name!r}, {_role(svc)}) cannot succeed: {fatal}",
                    EXIT_DEPLOY,
                    hint=_rollback_guidance(k8s),
                )
            raise DeployError(
                f"rollout of deployment/{svc.slug} (BentoML service "
                f"{svc.name!r}, {_role(svc)}) did not complete within "
                f"{k8s.rollout_timeout_seconds}s",
                EXIT_DEPLOY,
                hint=_rollback_guidance(k8s),
            )
        ctx.summary.record_stage(_rollout_stage(svc), True, time.monotonic() - started)
        log(f"rollout of deployment/{svc.slug} complete")
    log("all rollouts complete")


# A pod state that no amount of further waiting can fix. Without this, a
# mistyped image or a missing pull secret burns the whole rollout timeout
# (kubectl rollout status keeps waiting, and the Deployment's own progress
# deadline is 10 min) before saying anything useful. Reasons are matched on
# the container's waiting.reason, which kubelet sets long before either
# deadline expires.
_FATAL_WAITING_REASONS = (
    "ImagePullBackOff",
    "ErrImagePull",
    "InvalidImageName",
    "ImageInspectError",
    "RegistryUnavailable",
    "CreateContainerConfigError",
    "CreateContainerError",
)

# CrashLoopBackOff is only fatal once the container has proven it keeps dying:
# one early restart can be a slow dependency or a transient OOM on a busy node.
_CRASHLOOP_RESTART_THRESHOLD = 3

# How long to let kubectl rollout status run before pausing to inspect the
# pods. Short enough that a pull failure is reported in well under a minute,
# long enough that a healthy rollout is not interrupted more than a few times.
_ROLLOUT_POLL_SECONDS = 15


def _fatal_pod_state(k8s: K8sConfig, svc: ServiceSpec) -> str | None:
    """A one-line diagnosis when a pod of this service is in a state that
    waiting cannot fix, else None. Read-only; any kubectl failure (RBAC, a
    flaky apiserver) yields None so this can only ever speed up a failure
    that was going to happen anyway, never invent one."""
    res = run(
        _kubectl(
            k8s,
            "get",
            "pods",
            "-n",
            k8s.namespace,
            "-l",
            "app.kubernetes.io/name=" + svc.slug,
            "-o",
            "yaml",
        ),
        capture=True,
        quiet=True,
        check=False,
        timeout=30,
    )
    if res.returncode != 0:
        return None
    try:
        parsed = yaml.safe_load(res.stdout) or {}
    except Exception:
        return None
    for pod in parsed.get("items") or []:
        if not isinstance(pod, dict):
            continue
        name = (pod.get("metadata") or {}).get("name", "?")
        status = pod.get("status") or {}
        for container in status.get("containerStatuses") or []:
            waiting = (container.get("state") or {}).get("waiting") or {}
            reason = waiting.get("reason") or ""
            message = (waiting.get("message") or "").strip().splitlines()
            detail = message[0] if message else ""
            if reason in _FATAL_WAITING_REASONS:
                return f"pod {name}: {reason}" + (f" — {detail}" if detail else "")
            if (
                reason == "CrashLoopBackOff"
                and int(container.get("restartCount") or 0)
                >= _CRASHLOOP_RESTART_THRESHOLD
            ):
                return (
                    f"pod {name}: CrashLoopBackOff after "
                    f"{container.get('restartCount')} restarts — see "
                    f"`kubectl --context {k8s.context} -n {k8s.namespace} "
                    f"logs {name} --previous`"
                )
    return None


def _pod_blocked_reason(k8s: K8sConfig, svc: ServiceSpec) -> str | None:
    """Why this service's pods are not running yet, from the pods' own
    conditions (`Unschedulable` and friends). Unlike _fatal_pod_state this is
    NOT a verdict — a pod can stop being unschedulable the moment capacity
    frees up — so it is only used to enrich a failure the Deployment itself has
    already given up on. Read-only, None on any kubectl problem."""
    res = run(
        _kubectl(
            k8s,
            "get",
            "pods",
            "-n",
            k8s.namespace,
            "-l",
            "app.kubernetes.io/name=" + svc.slug,
            "-o",
            "yaml",
        ),
        capture=True,
        quiet=True,
        check=False,
        timeout=30,
    )
    if res.returncode != 0:
        return None
    try:
        parsed = yaml.safe_load(res.stdout) or {}
    except Exception:
        return None
    for pod in parsed.get("items") or []:
        if not isinstance(pod, dict):
            continue
        status = pod.get("status") or {}
        if status.get("phase") != "Pending":
            continue
        name = (pod.get("metadata") or {}).get("name", "?")
        for condition in status.get("conditions") or []:
            if condition.get("status") == "True":
                continue
            reason = condition.get("reason") or ""
            message = (condition.get("message") or "").strip().splitlines()
            if not reason:
                continue
            detail = message[0] if message else ""
            return f"pod {name}: {reason}" + (f" — {detail}" if detail else "")
    return None


# The Deployment's own verdict, printed by `kubectl rollout status` once
# spec.progressDeadlineSeconds (10 min by default) expires without progress.
# Waiting past it is pointless: Kubernetes has stopped trying to make progress
# and will not resume without a change.
_PROGRESS_DEADLINE_MARKER = "exceeded its progress deadline"


def _rollout_status(k8s: K8sConfig, svc: ServiceSpec) -> tuple[RunResult, str | None]:
    """kubectl rollout status for one service, in short slices so the pods can
    be inspected in between. Returns (last result, fatal diagnosis or None);
    a fatal diagnosis short-circuits the wait instead of burning the timeout."""
    deadline = time.monotonic() + k8s.rollout_timeout_seconds
    reported = ""
    while True:
        slice_seconds = min(
            _ROLLOUT_POLL_SECONDS, max(1, int(deadline - time.monotonic()))
        )
        res = run(
            _kubectl(
                k8s,
                "rollout",
                "status",
                "deployment/" + svc.slug,
                "-n",
                k8s.namespace,
                f"--timeout={slice_seconds}s",
            ),
            capture=True,
            quiet=True,
            check=False,
        )
        # kubectl repeats the same progress line every slice; echo it only when
        # it changes, so a slow image pull does not scroll the log. The
        # per-slice "timed out waiting" is this function's own pacing, not a
        # failure, so it is never echoed.
        progress = [
            line.strip()
            for line in (res.stdout or "").splitlines()
            if line.strip() and not line.strip().startswith("error:")
        ]
        if progress and progress[-1] != reported:
            reported = progress[-1]
            log("  " + reported)
        if res.returncode == 0:
            return res, None
        fatal = _fatal_pod_state(k8s, svc)
        if fatal is not None:
            return res, fatal
        if _PROGRESS_DEADLINE_MARKER in (res.stdout or "") + (res.stderr or ""):
            # Kubernetes gave up before our own timeout did. Say why the pods
            # never came up when they can tell us (Unschedulable is the usual
            # answer), and stop rather than idling until rollout_timeout_seconds.
            blocked = _pod_blocked_reason(k8s, svc)
            return res, "the Deployment exceeded its own progress deadline" + (
                f" ({blocked})" if blocked else ""
            )
        if time.monotonic() >= deadline:
            # Log kubectl's last word: it is captured, so it never reached the
            # terminal, and the timeout message alone does not say what stalled.
            last = [
                line.strip()
                for line in (
                    (res.stderr or "") + "\n" + (res.stdout or "")
                ).splitlines()
                if line.strip()
            ]
            if last:
                log("  " + last[0])
            return res, None


def _rollout_stage(svc: ServiceSpec) -> str:
    return f"k8s.rollout[{svc.slug}]"


# --------------------------------------------------------------------------
# verify
# --------------------------------------------------------------------------


class _PortForward:
    """kubectl port-forward to one Service, with PID-liveness checks and
    guaranteed cleanup.

    A local health probe is only trustworthy while the port-forward process
    is alive — if it died, whatever squats on the local port would produce
    convincing but fake results. alive() must be checked before every probe.

    Defaults to the ENTRY service (the only one that speaks the public HTTP
    API); the dependency-metrics check forwards to each dependency POD to
    scrape its /metrics, which is a read-only probe inside the cluster.

    Pass `pod=` to target one pod instead of a Service. That matters for
    /metrics: a Service load-balances, so scraping svc/<dep> reads ONE
    replica's counters at random and a request served by a sibling pod looks
    like no request at all.
    """

    def __init__(
        self,
        k8s: K8sConfig,
        service: str | None = None,
        local_port: int | None = None,
        pod: str | None = None,
    ) -> None:
        self._k8s = k8s
        self._service = service or k8s.entry_service.slug
        self._target = f"pod/{pod}" if pod else f"svc/{self._service}"
        self._local_port = local_port or k8s.local_port
        # Not a context manager on purpose: the file must outlive this
        # constructor (the port-forward writes to it until close()).
        self._log = tempfile.NamedTemporaryFile(  # noqa: SIM115
            mode="w+", prefix="bentoml-deploy-pf-", suffix=".log", delete=False
        )
        self._proc = subprocess.Popen(
            _kubectl(
                k8s,
                "port-forward",
                self._target,
                "-n",
                k8s.namespace,
                f"{self._local_port}:3000",
            ),
            stdout=self._log,
            stderr=self._log,
            text=True,
        )

    def alive(self) -> bool:
        return self._proc.poll() is None

    def wait_until_forwarding(self, timeout_seconds: float) -> None:
        """Block until kubectl reports 'Forwarding from' (i.e. it owns the
        local port). Probing earlier risks hitting an unrelated process that
        squats on the port during kubectl's spawn-to-bind window — a
        convincing but fake result."""
        deadline = time.monotonic() + timeout_seconds
        while time.monotonic() < deadline:
            if not self.alive():
                raise DeployError(
                    "kubectl port-forward exited before binding the local "
                    "port:\n" + self.captured_output(),
                    EXIT_VERIFY,
                    hint=f"is local port {self._local_port} free "
                    "(kubernetes.local_port / local_port + 1), and does "
                    f"{self._target} exist in namespace "
                    f"{self._k8s.namespace}?",
                )
            if "Forwarding from" in self.captured_output():
                return
            time.sleep(0.2)
        raise DeployError(
            f"kubectl port-forward did not report 'Forwarding from' within "
            f"{timeout_seconds:.0f}s:\n" + self.captured_output(),
            EXIT_VERIFY,
        )

    def captured_output(self) -> str:
        try:
            with open(self._log.name, encoding="utf-8") as fh:
                return fh.read().strip()
        except OSError:
            return "(no port-forward output captured)"

    def close(self) -> None:
        if self._proc.poll() is None:
            self._proc.terminate()
            try:
                self._proc.wait(timeout=5)
            except subprocess.TimeoutExpired:
                self._proc.kill()
                self._proc.wait(timeout=5)
        self._log.close()
        try:
            Path(self._log.name).unlink()
        except OSError:
            pass


def verify(ctx: RunContext) -> None:
    k8s = ctx.cfg.require_k8s()
    vcfg = ctx.cfg.verify
    entry = k8s.entry_service
    deps = k8s.dependencies
    base_url = f"http://127.0.0.1:{k8s.local_port}"
    section(
        f"verify: entry service {entry.name} — /readyz via port-forward to "
        f"svc/{entry.slug} on {base_url}"
    )

    pf = _PortForward(k8s)
    try:
        pf.wait_until_forwarding(30)
        _wait_ready(pf, base_url, vcfg.readyz_timeout_seconds, k8s)
        if vcfg.inference is None:
            # verify.inference is OPTIONAL: with no block, /readyz above IS the
            # verification. That is enough to prove every pod started, served
            # HTTP and (for a caller) reached its dependencies' /readyz — but
            # not that an inference request travels the dependency path.
            log(
                "verify.inference is not configured — verification is /readyz "
                "only (add a verify.inference block to POST a real request)"
            )
            if deps:
                log(
                    "dependency-metrics proof SKIPPED: this bento has "
                    f"{len(deps)} dependency service(s), and only a real "
                    "inference request exercises the dependency path. Without "
                    "one, a gateway that silently instantiated its "
                    "dependencies IN-PROCESS answers /readyz exactly like a "
                    "correctly wired split — set verify.inference to close "
                    "that gap."
                )
            return
        # A gateway's /readyz proves NOTHING about a dependency that was
        # instantiated in-process: readiness only fans out to dependencies
        # that are remote proxies, so an in-process one is skipped and
        # readiness is trivially true. The dependency's own request counter
        # is the only positive evidence that the call crossed the network.
        measure = bool(deps) and vcfg.dependency_metrics
        before: dict[str, float] = {}
        if measure:
            log(
                f"sampling {REQUEST_TOTAL_METRIC} on {len(deps)} "
                "dependency service(s) before the inference request"
            )
            before = _sample_dependency_totals(k8s, deps)
        elif deps:
            warn(
                "verify.dependency_metrics is false — not proving that the "
                "dependencies are reached over the network. A gateway that "
                "silently instantiated them in-process answers correctly "
                "and reports ready, so this run cannot tell the two apart."
            )
        _inference_smoke(pf, base_url, vcfg.inference)
        if measure:
            after = _sample_dependency_totals(k8s, deps)
            _assert_dependencies_called(k8s, deps, before, after)
    finally:
        pf.close()


def _running_pods(k8s: K8sConfig, slug: str) -> list[str]:
    """Names of this service's Running pods, or [] when they cannot be listed
    (the caller then falls back to scraping the Service)."""
    res = run(
        _kubectl(
            k8s,
            "get",
            "pods",
            "-n",
            k8s.namespace,
            "-l",
            "app.kubernetes.io/name=" + slug,
            "--field-selector=status.phase=Running",
            "-o",
            "jsonpath={.items[*].metadata.name}",
        ),
        capture=True,
        quiet=True,
        check=False,
        timeout=30,
    )
    if res.returncode != 0:
        return []
    return res.stdout.split()


def _sample_dependency_totals(
    k8s: K8sConfig, deps: list[ServiceSpec]
) -> dict[str, float]:
    """Scrape each dependency's own /metrics through short-lived port-forwards
    and return its non-health request total, summed over ALL of its pods.

    Per POD, not per Service: a Service load-balances, so one scrape of
    svc/<dep> reads a random replica and a request that a sibling pod served
    would look like no request at all — a false "served no request" failure on
    any dependency with replicas > 1. Summing every pod is exact regardless of
    which replica the entry service happened to call.

    Read-only: /metrics is not instrumented by the metrics middleware, so
    scraping never moves the counter it reports. The forwards are sequential
    and share one local port (kubernetes.local_port + 1)."""
    port = k8s.local_port + 1
    totals: dict[str, float] = {}
    for dep in deps:
        pods = _running_pods(k8s, dep.slug)
        if not pods:
            # No pod list (RBAC, or a race with a restart): fall back to the
            # Service. Still correct for a single replica, and the alternative
            # is losing the proof entirely.
            warn(
                f"could not list pods of dependency {dep.name} "
                f"(svc/{dep.slug}); scraping the Service instead, which reads "
                "one replica at random — a false 'served no request' is "
                "possible if this dependency has more than one pod"
            )
        targets = pods or [None]
        total = 0.0
        for pod in targets:
            label = f"pod/{pod}" if pod else f"svc/{dep.slug}"
            pf = _PortForward(k8s, dep.slug, port, pod=pod)
            try:
                pf.wait_until_forwarding(30)
                try:
                    status, body = http_get(
                        f"http://127.0.0.1:{port}/metrics", timeout=10
                    )
                except (urllib.error.URLError, OSError) as exc:
                    raise DeployError(
                        f"could not scrape /metrics of dependency {label}: {exc}",
                        EXIT_VERIFY,
                        hint="set verify.dependency_metrics to false to skip "
                        "this proof (and lose the only signal that the "
                        "dependency is reached over the network)",
                    ) from None
                if not pf.alive():
                    raise DeployError(
                        "port-forward to dependency "
                        f"{label} died during the /metrics scrape; the "
                        "response cannot be trusted:\n" + pf.captured_output(),
                        EXIT_VERIFY,
                    )
                if status != 200:
                    raise DeployError(
                        f"/metrics of dependency {label} returned HTTP {status}",
                        EXIT_VERIFY,
                        hint="every BentoML server exposes /metrics on port "
                        "3000; if it is disabled in this bento, set "
                        "verify.dependency_metrics to false",
                    )
                total += _sum_request_total(body)
            finally:
                pf.close()
        totals[dep.slug] = total
    return totals


def _assert_dependencies_called(
    k8s: K8sConfig,
    deps: list[ServiceSpec],
    before: dict[str, float],
    after: dict[str, float],
) -> None:
    """Fail unless every dependency's request counter moved: that is the only
    positive proof the inference request crossed the network instead of being
    served by an in-process copy inside the gateway pod."""
    stale = [
        dep for dep in deps if after.get(dep.slug, 0.0) <= before.get(dep.slug, 0.0)
    ]
    for dep in deps:
        delta = after.get(dep.slug, 0.0) - before.get(dep.slug, 0.0)
        log(f"  {dep.name} (svc/{dep.slug}): {REQUEST_TOTAL_METRIC} +{delta:g}")
    if not stale:
        log("every dependency served a request over the network")
        return
    names = ", ".join(f"{dep.name} (svc/{dep.slug})" for dep in stale)
    raise DeployError(
        f"dependency service(s) {names} served no request during the "
        "inference smoke test — the entry service answered without calling "
        "them over the network",
        EXIT_VERIFY,
        hint="most likely a caller's "
        f"{SERVE_DEPENDS_ENV} does not name them exactly as the bento "
        "declares them, so BentoML instantiated them IN-PROCESS: that pod "
        "loaded those models itself, answers correctly and "
        "reports ready, while the dependency pods idle. The names are the "
        "bento's own (bento.yaml's services[].name and "
        "services[].dependencies[].service), so this points at a hand-owned "
        "manifests_dir or an overridden container command rather than at "
        "config.yml — check what was applied:\n"
        f"  kubectl --context {k8s.context} -n {k8s.namespace} get "
        "deployment/"
        + k8s.entry_service.slug
        + " -o jsonpath='{.spec.template.spec.containers[0].env}'\n"
        "If instead this dependency is simply not on the code path of "
        "verify.inference.path, point the smoke test at an API that uses "
        "it, or set verify.dependency_metrics to false.",
    )


def _wait_ready(
    pf: _PortForward, base_url: str, timeout_seconds: int, k8s: K8sConfig
) -> None:
    entry_slug = k8s.entry_service.slug
    deadline = time.monotonic() + timeout_seconds
    attempt = 0
    while True:
        if not pf.alive():
            raise DeployError(
                "kubectl port-forward exited unexpectedly:\n" + pf.captured_output(),
                EXIT_VERIFY,
                hint=f"is service/{entry_slug} in namespace {k8s.namespace} reachable? "
                f"(kubectl --context {k8s.context} -n {k8s.namespace} get svc,endpoints {entry_slug})",
            )
        attempt += 1
        try:
            status, _ = http_get(base_url + "/readyz", timeout=3)
            if status == 200:
                if not pf.alive():
                    # The forwarder died — whatever answered was not our
                    # service. Never trust a probe the tunnel can't explain.
                    raise DeployError(
                        "port-forward died during the readiness probe; "
                        "the 200 response cannot be trusted:\n" + pf.captured_output(),
                        EXIT_VERIFY,
                    )
                log(f"/readyz returned 200 (attempt {attempt})")
                return
            log(f"/readyz returned {status} — retrying")
        except (urllib.error.URLError, OSError, ConnectionError) as exc:
            if attempt % 5 == 1:
                log(f"waiting for /readyz ({exc})")
        if time.monotonic() >= deadline:
            raise DeployError(
                f"entry service {k8s.entry_service.name!r} "
                f"(svc/{entry_slug}) did not become ready within "
                f"{timeout_seconds}s; port-forward output:"
                f"\n{pf.captured_output()}",
                EXIT_VERIFY,
                hint=_rollback_guidance(k8s),
            )
        time.sleep(2)


def _inference_smoke(
    pf: _PortForward, base_url: str, inference: InferenceCheck
) -> None:
    url = base_url + inference.path
    log(f"inference smoke test: POST {inference.path}")
    if not pf.alive():
        raise DeployError(
            "port-forward died before the inference request:\n" + pf.captured_output(),
            EXIT_VERIFY,
        )
    try:
        status, body = http_post_json(
            url, inference.body, timeout=inference.timeout_seconds
        )
    except (urllib.error.URLError, OSError) as exc:
        raise DeployError(
            f"inference request to {inference.path} failed: {exc}",
            EXIT_VERIFY,
        ) from None
    if not pf.alive():
        raise DeployError(
            "port-forward died during the inference request; the response "
            "cannot be trusted:\n" + pf.captured_output(),
            EXIT_VERIFY,
        )
    snippet = body[:500].replace("\n", " ")
    log(f"response {status}: {snippet}")
    if not 200 <= status < 300:
        raise DeployError(
            f"inference smoke test returned HTTP {status} for "
            f"{inference.path} (body: {snippet})",
            EXIT_VERIFY,
            hint="check verify.inference.body against the service's "
            "@bentoml.api signature",
        )
    if inference.expect_substring and inference.expect_substring not in body:
        raise DeployError(
            f"inference response did not contain expected substring {inference.expect_substring!r} "
            f"(body: {snippet})",
            EXIT_VERIFY,
        )
    log("inference smoke test passed")
