from pandas.util._decorators import doc

class DirNamesMixin:
    _accessors: set[str] = ...
    _hidden_attrs: frozenset[str] = ...
    def __dir__(self) -> list[str]: ...

class PandasDelegate: ...

def delegate_names(delegate, accessors, typ: str, overwrite: bool = ...): ...

class CachedAccessor:
    def __init__(self, name: str, accessor) -> None: ...
    def __get__(self, obj, cls): ...

@doc(_register_accessor, klass="DataFrame")
def register_dataframe_accessor(name): ...
@doc(_register_accessor, klass="Series")
def register_series_accessor(name): ...
