import abc
from typing import TYPE_CHECKING, Any, Dict, Iterator
from pandas import DataFrame, Index, Series
from pandas._typing import (
    AggFuncType,
    AggFuncTypeDict,
    AggObjType,
    Axis,
    FrameOrSeries,
    FrameOrSeriesUnion,
)
from pandas.core.groupby import GroupBy
from pandas.core.resample import Resampler
from pandas.core.window.rolling import BaseWindow
from pandas.util._decorators import cache_readonly

if TYPE_CHECKING: ...
ResType = Dict[int, Any]

def frame_apply(
    obj: DataFrame,
    func: AggFuncType,
    axis: Axis = ...,
    raw: bool = ...,
    result_type: str | None = ...,
    args=...,
    kwargs=...,
) -> FrameApply: ...

class Apply(metaclass=abc.ABCMeta):
    axis: int
    def __init__(
        self, obj: AggObjType, func, raw: bool, result_type: str | None, args, kwargs
    ) -> None: ...
    @abc.abstractmethod
    def apply(self) -> FrameOrSeriesUnion: ...
    def agg(self) -> FrameOrSeriesUnion | None: ...
    def transform(self) -> FrameOrSeriesUnion: ...
    def transform_dict_like(self, func): ...
    def transform_str_or_callable(self, func) -> FrameOrSeriesUnion: ...
    def agg_list_like(self) -> FrameOrSeriesUnion: ...
    def agg_dict_like(self) -> FrameOrSeriesUnion: ...
    def apply_str(self) -> FrameOrSeriesUnion: ...
    def apply_multiple(self) -> FrameOrSeriesUnion: ...
    def normalize_dictlike_arg(
        self, how: str, obj: FrameOrSeriesUnion, func: AggFuncTypeDict
    ) -> AggFuncTypeDict: ...

class NDFrameApply(Apply):
    @property
    def index(self) -> Index: ...
    @property
    def agg_axis(self) -> Index: ...

class FrameApply(NDFrameApply):
    obj: DataFrame
    @property
    @abc.abstractmethod
    def result_index(self) -> Index: ...
    @property
    @abc.abstractmethod
    def result_columns(self) -> Index: ...
    @property
    @abc.abstractmethod
    def series_generator(self) -> Iterator[Series]: ...
    @abc.abstractmethod
    def wrap_results_for_axis(
        self, results: ResType, res_index: Index
    ) -> FrameOrSeriesUnion: ...
    @property
    def res_columns(self) -> Index: ...
    @property
    def columns(self) -> Index: ...
    @cache_readonly
    def values(self): ...
    @cache_readonly
    def dtypes(self) -> Series: ...
    def apply(self) -> FrameOrSeriesUnion: ...
    def agg(self): ...
    def apply_empty_result(self): ...
    def apply_raw(self): ...
    def apply_broadcast(self, target: DataFrame) -> DataFrame: ...
    def apply_standard(self): ...
    def apply_series_generator(self) -> tuple[ResType, Index]: ...
    def wrap_results(
        self, results: ResType, res_index: Index
    ) -> FrameOrSeriesUnion: ...
    def apply_str(self) -> FrameOrSeriesUnion: ...

class FrameRowApply(FrameApply):
    axis = ...
    def apply_broadcast(self, target: DataFrame) -> DataFrame: ...
    @property
    def series_generator(self): ...
    @property
    def result_index(self) -> Index: ...
    @property
    def result_columns(self) -> Index: ...
    def wrap_results_for_axis(
        self, results: ResType, res_index: Index
    ) -> FrameOrSeriesUnion: ...

class FrameColumnApply(FrameApply):
    axis = ...
    def apply_broadcast(self, target: DataFrame) -> DataFrame: ...
    @property
    def series_generator(self): ...
    @property
    def result_index(self) -> Index: ...
    @property
    def result_columns(self) -> Index: ...
    def wrap_results_for_axis(
        self, results: ResType, res_index: Index
    ) -> FrameOrSeriesUnion: ...
    def infer_to_same_shape(self, results: ResType, res_index: Index) -> DataFrame: ...

class SeriesApply(NDFrameApply):
    obj: Series
    axis = ...
    def __init__(
        self, obj: Series, func: AggFuncType, convert_dtype: bool, args, kwargs
    ) -> None: ...
    def apply(self) -> FrameOrSeriesUnion: ...
    def agg(self): ...
    def apply_empty_result(self) -> Series: ...
    def apply_standard(self) -> FrameOrSeriesUnion: ...

class GroupByApply(Apply):
    def __init__(
        self, obj: GroupBy[FrameOrSeries], func: AggFuncType, args, kwargs
    ) -> None: ...
    def apply(self): ...
    def transform(self): ...

class ResamplerWindowApply(Apply):
    axis = ...
    obj: Resampler | BaseWindow
    def __init__(
        self, obj: Resampler | BaseWindow, func: AggFuncType, args, kwargs
    ) -> None: ...
    def apply(self): ...
    def transform(self): ...
