use_bottleneck_doc = ...

def use_bottleneck_cb(key): ...

use_numexpr_doc = ...

def use_numexpr_cb(key): ...

use_numba_doc = ...

def use_numba_cb(key): ...

pc_precision_doc = ...
pc_colspace_doc = ...
pc_max_rows_doc = ...
pc_min_rows_doc = ...
pc_max_cols_doc = ...
pc_max_categories_doc = ...
pc_max_info_cols_doc = ...
pc_nb_repr_h_doc = ...
pc_pprint_nest_depth = ...
pc_multi_sparse_doc = ...
float_format_doc = ...
max_colwidth_doc = ...
colheader_justify_doc = ...
pc_expand_repr_doc = ...
pc_show_dimensions_doc = ...
pc_east_asian_width_doc = ...
pc_ambiguous_as_wide_doc = ...
pc_latex_repr_doc = ...
pc_table_schema_doc = ...
pc_html_border_doc = ...
pc_html_use_mathjax_doc = ...
pc_width_doc = ...
pc_chop_threshold_doc = ...
pc_max_seq_items = ...
pc_max_info_rows_doc = ...
pc_large_repr_doc = ...
pc_memory_usage_doc = ...
pc_latex_escape = ...
pc_latex_longtable = ...
pc_latex_multicolumn = ...
pc_latex_multicolumn_format = ...
pc_latex_multirow = ...

def table_schema_cb(key): ...
def is_terminal() -> bool: ...

tc_sim_interactive_doc = ...
use_inf_as_null_doc = ...
use_inf_as_na_doc = ...

def use_inf_as_na_cb(key): ...

data_manager_doc = ...
chained_assignment = ...
string_storage_doc = ...
reader_engine_doc = ...
_xls_options = ...
_xlsm_options = ...
_xlsx_options = ...
_ods_options = ...
_xlsb_options = ...
writer_engine_doc = ...
_xls_options = ...
_xlsm_options = ...
_xlsx_options = ...
_ods_options = ...
parquet_engine_doc = ...
sql_engine_doc = ...
plotting_backend_doc = ...

def register_plotting_backend_cb(key): ...

register_converter_doc = ...

def register_converter_cb(key): ...

styler_sparse_index_doc = ...
styler_sparse_columns_doc = ...
styler_max_elements = ...
