from typing import TYPE_CHECKING
import numpy as np
from pandas._typing import Any, AnyArrayLike, ArrayLike
from pandas.core.frame import DataFrame
from pandas.core.indexes.base import Index

if TYPE_CHECKING: ...

def is_valid_positional_slice(slc: slice) -> bool: ...
def is_list_like_indexer(key) -> bool: ...
def is_scalar_indexer(indexer, ndim: int) -> bool: ...
def is_empty_indexer(indexer, arr_value: np.ndarray) -> bool: ...
def check_setitem_lengths(indexer, value, values) -> bool: ...
def validate_indices(indices: np.ndarray, n: int) -> None: ...
def maybe_convert_indices(indices, n: int, verify: bool = ...): ...
def is_exact_shape_match(target: ArrayLike, value: ArrayLike) -> bool: ...
def length_of_indexer(indexer, target=...) -> int: ...
def deprecate_ndim_indexing(result, stacklevel: int = ...): ...
def unpack_1tuple(tup): ...
def check_key_length(columns: Index, key, value: DataFrame): ...
def check_array_indexer(array: AnyArrayLike, indexer: Any) -> Any: ...
