from pandas._libs.internals import BlockPlacement
from pandas._typing import Dtype
from pandas.core.internals.blocks import Block

def make_block(
    values, placement, klass=..., ndim=..., dtype: Dtype | None = ...
) -> Block: ...
def maybe_infer_ndim(values, placement: BlockPlacement, ndim: int | None) -> int: ...
