from typing import TYPE_CHECKING
from pandas import Index
from pandas._typing import ArrayLike, DtypeObj, Manager, Shape
from pandas.util._decorators import cache_readonly

if TYPE_CHECKING: ...

def concat_arrays(to_concat: list) -> ArrayLike: ...
def concatenate_managers(
    mgrs_indexers, axes: list[Index], concat_axis: int, copy: bool
) -> Manager: ...

class JoinUnit:
    def __init__(self, block, shape: Shape, indexers=...) -> None: ...
    def __repr__(self) -> str: ...
    @cache_readonly
    def needs_filling(self) -> bool: ...
    @cache_readonly
    def dtype(self): ...
    def is_valid_na_for(self, dtype: DtypeObj) -> bool: ...
    @cache_readonly
    def is_na(self) -> bool: ...
    def get_reindexed_values(self, empty_dtype: DtypeObj, upcasted_na) -> ArrayLike: ...
