import typing as t

class Base64Decoder:
    def __init__(self, underlying: t.BinaryIO) -> None: ...
    def write(self, data: t.AnyStr) -> None: ...
    def close(self) -> None: ...
    def finalize(self) -> None: ...
    def __repr__(self) -> str: ...

class QuotedPrintableDecoder:
    def __init__(self, underlying: t.BinaryIO) -> None: ...
    def write(self, data: t.AnyStr) -> None: ...
    def close(self) -> None: ...
    def finalize(self) -> None: ...
    def __repr__(self) -> str: ...
