class FormParserError(ValueError): ...

class ParseError(FormParserError):
    offset: int = ...

class MultipartParseError(ParseError): ...
class QuerystringParseError(ParseError): ...
class DecodeError(ParseError): ...
class FileError(FormParserError, OSError): ...

Base64Error: TypeError = ...
