#!/usr/bin/env bash

GIT_ROOT=$(git rev-parse --show-toplevel)
cd $GIT_ROOT/docker || exit 1

if $(docker buildx ls | grep bento-server-builder >| /tmp/builder.log); then

    sed -n 'p;n' /tmp/builder.log | cut -d ' ' -f 1 >generated/builder.log

    cat generated/builder.log | while  read -r line ; do
        docker buildx rm "$line"
    done

    rm -rf generated/builder.log
    echo "Finished removing emphemeral builder."

else
    echo "No builder found, exiting..."; exit 0;
fi
