#!/usr/bin/env bash

set -e

SCRIPT_DIR="$(cd "$( dirname "$(readlink -f $0)")" && pwd)"
TEST_PATH=$(realpath "${SCRIPT_DIR}/tests")


POSITIONAL_ARGS=()

while [[ $# -gt 0 ]]; do
case $1 in
    -img|--image_name)
    IMAGE_NAME="$2"
    shift # past argument
    shift # past value
    ;;
    -bv|--bentoml_version)
    BENTOML_VERSION="$2"
    shift # past argument
    shift # past value
    ;;
    -pv|--python_version)
    PYTHON_VERSION="$2"
    shift # past argument
    shift # past value
    ;;
    -os|--distros)
    OS="$2"
    shift # past argument
    shift # past value
    ;;
    -sf|--suffix)
    IMAGE_TAG_SUFFIX="$2"
    shift # past argument
    shift # past value
    ;;
    -pl|--platforms)
    PLATFORMS="$2"
    shift # past argument
    shift # past value
    ;;
    -og|--organization)
    ORGANIZATION="$2"
    shift # past argument
    shift # past value
    ;;
    --default)
    BENTOML_VERSION=$(git describe --tags $(git rev-list --tags --max-count=1) | sed 's/v\(\)/\1/; s/-//g')
    IMAGE_NAME='bento-server'
    PLATFORMS='amd64'
    shift # past argument
    ;;
    -*|--*)
    echo "Unknown option $1"
    exit 1
    ;;
    *)
    POSITIONAL_ARGS+=("$1") # save positional arg
    shift # past argument
    ;;
esac
done

set -- "${POSITIONAL_ARGS[@]}" # restore positional parameters

main(){
    export BENTOML_TEST_PYTHON_VERSION="$PYTHON_VERSION"
    export BENTOML_TEST_OS="$OS"
    export BENTOML_TEST_IMAGE_TAG_SUFFIX="$IMAGE_TAG_SUFFIX"
    export BENTOML_TEST_IMAGE_NAME="$IMAGE_NAME"
    export BENTOML_TEST_BENTOML_VERSION="$BENTOML_VERSION"
    export BENTOML_TEST_IMAGE_NAME="$IMAGE_NAME"
    export BENTOML_TEST_ARCH="$PLATFORMS"
	export BENTOML_TEST_ORGANIZATION="$ORGANIZATION"

	if [ -f "/.dockerenv" ]; then
		TEST_PATH="./tests"
    fi

	for file in $(find "$TEST_PATH" -type f -iname "[0-9]*-*.bats" | sort); do
		bats --tap "$file"
    done
}

main "$@"
