from argparse import ArgumentParser
from typing import Iterable, Tuple, Union

DataClass = ...
DataClassType = ...

def string_to_bool(v): ...

class HfArgumentParser(ArgumentParser):
    dataclass_types: Iterable[DataClassType]
    def __init__(
        self, dataclass_types: Union[DataClassType, Iterable[DataClassType]], **kwargs
    ) -> None: ...
    def parse_args_into_dataclasses(
        self,
        args=...,
        return_remaining_strings=...,
        look_for_args_file=...,
        args_filename=...,
    ) -> Tuple[DataClass, ...]: ...
    def parse_json_file(self, json_file: str) -> Tuple[DataClass, ...]: ...
    def parse_dict(self, args: dict) -> Tuple[DataClass, ...]: ...
