IMAGENET_DEFAULT_MEAN = ...
IMAGENET_DEFAULT_STD = ...

def is_torch_tensor(obj): ...

class ImageFeatureExtractionMixin:
    def to_pil_image(self, image, rescale=...): ...
    def to_numpy_array(self, image, rescale=..., channel_first=...): ...
    def normalize(self, image, mean, std): ...
    def resize(self, image, size, resample=...): ...
