logger = ...

def convert_tf_weight_name_to_pt_weight_name(tf_name, start_prefix_to_remove=...): ...
def load_pytorch_checkpoint_in_tf2_model(
    tf_model, pytorch_checkpoint_path, tf_inputs=..., allow_missing_keys=...
): ...
def load_pytorch_model_in_tf2_model(
    tf_model, pt_model, tf_inputs=..., allow_missing_keys=...
): ...
def load_pytorch_weights_in_tf2_model(
    tf_model, pt_state_dict, tf_inputs=..., allow_missing_keys=...
): ...
def load_tf2_checkpoint_in_pytorch_model(
    pt_model, tf_checkpoint_path, tf_inputs=..., allow_missing_keys=...
): ...
def load_tf2_model_in_pytorch_model(pt_model, tf_model, allow_missing_keys=...): ...
def load_tf2_weights_in_pytorch_model(pt_model, tf_weights, allow_missing_keys=...): ...
