#!/bin/sh
# A git hook to block an unsigned-off commit

COMMIT_MSG_FILE=$1

SIGNOFF_PATTERN="Signed-off-by: .+ <.+@.+>"
COMMIT_MESSAGE=$(cat "$COMMIT_MSG_FILE")

if [ ! "$COMMIT_MESSAGE" =~ $SIGNOFF_PATTERN ]; then
  echo "Aborted \`git commit\` because it's not signed-off."
  echo "You can sign-off your commit using the \`-s\` flag as follow:"
  echo
  echo "git commit -sm <commit message>"
  exit 1
fi
