"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.duration_pb2
import google.protobuf.internal.containers
import google.protobuf.message
import google.protobuf.timestamp_pb2
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Tuple(google.protobuf.message.Message):
    """Tuple represents a repeated field containing data with same or different datatypes."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUE_FIELD_NUMBER: builtins.int
    @property
    def value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Value]: ...
    def __init__(self,
        *,
        value: typing.Optional[typing.Iterable[global___Value]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["value",b"value"]) -> None: ...
global___Tuple = Tuple

class Value(google.protobuf.message.Message):
    """Value represents a single instance of the supported datatypes.
    TODO: int32, int64, fixed32, fixed64, sfixed32, sfixed64.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FLOAT_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    BYTES_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    UINT32_VALUE_FIELD_NUMBER: builtins.int
    SINT32_VALUE_FIELD_NUMBER: builtins.int
    TIMESTAMP_VALUE_FIELD_NUMBER: builtins.int
    DURATION_VALUE_FIELD_NUMBER: builtins.int
    ARRAY_VALUE_FIELD_NUMBER: builtins.int
    TUPLE_VALUE_FIELD_NUMBER: builtins.int
    UINT64_VALUE_FIELD_NUMBER: builtins.int
    SINT64_VALUE_FIELD_NUMBER: builtins.int
    float_value: builtins.float
    double_value: builtins.float
    bytes_value: builtins.bytes
    bool_value: builtins.bool
    string_value: typing.Text
    uint32_value: builtins.int
    sint32_value: builtins.int
    @property
    def timestamp_value(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def duration_value(self) -> google.protobuf.duration_pb2.Duration: ...
    @property
    def array_value(self) -> global___Array: ...
    @property
    def tuple_value(self) -> global___Tuple: ...
    uint64_value: builtins.int
    sint64_value: builtins.int
    def __init__(self,
        *,
        float_value: builtins.float = ...,
        double_value: builtins.float = ...,
        bytes_value: builtins.bytes = ...,
        bool_value: builtins.bool = ...,
        string_value: typing.Text = ...,
        uint32_value: builtins.int = ...,
        sint32_value: builtins.int = ...,
        timestamp_value: typing.Optional[google.protobuf.timestamp_pb2.Timestamp] = ...,
        duration_value: typing.Optional[google.protobuf.duration_pb2.Duration] = ...,
        array_value: typing.Optional[global___Array] = ...,
        tuple_value: typing.Optional[global___Tuple] = ...,
        uint64_value: builtins.int = ...,
        sint64_value: builtins.int = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["array_value",b"array_value","bool_value",b"bool_value","bytes_value",b"bytes_value","double_value",b"double_value","duration_value",b"duration_value","float_value",b"float_value","sint32_value",b"sint32_value","sint64_value",b"sint64_value","string_value",b"string_value","timestamp_value",b"timestamp_value","tuple_value",b"tuple_value","uint32_value",b"uint32_value","uint64_value",b"uint64_value","value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["array_value",b"array_value","bool_value",b"bool_value","bytes_value",b"bytes_value","double_value",b"double_value","duration_value",b"duration_value","float_value",b"float_value","sint32_value",b"sint32_value","sint64_value",b"sint64_value","string_value",b"string_value","timestamp_value",b"timestamp_value","tuple_value",b"tuple_value","uint32_value",b"uint32_value","uint64_value",b"uint64_value","value",b"value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["value",b"value"]) -> typing.Optional[typing_extensions.Literal["float_value","double_value","bytes_value","bool_value","string_value","uint32_value","sint32_value","timestamp_value","duration_value","array_value","tuple_value","uint64_value","sint64_value"]]: ...
global___Value = Value

class Array(google.protobuf.message.Message):
    """TODO: message complex types

    Array contains a dtype which identifies the type of the array.
    Repeated field for the identified dtype contains the array.
    TODO: int32, int64, fixed32, fixed64, sfixed32, sfixed64
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    FLOAT_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    BYTES_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    UINT32_VALUE_FIELD_NUMBER: builtins.int
    SINT32_VALUE_FIELD_NUMBER: builtins.int
    TIMESTAMP_VALUE_FIELD_NUMBER: builtins.int
    DURATION_VALUE_FIELD_NUMBER: builtins.int
    ARRAY_VALUE_FIELD_NUMBER: builtins.int
    TUPLE_VALUE_FIELD_NUMBER: builtins.int
    UINT64_VALUE_FIELD_NUMBER: builtins.int
    SINT64_VALUE_FIELD_NUMBER: builtins.int
    @property
    def float_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def double_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]: ...
    @property
    def bytes_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]: ...
    @property
    def bool_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]: ...
    @property
    def string_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    @property
    def uint32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sint32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def timestamp_value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.timestamp_pb2.Timestamp]: ...
    @property
    def duration_value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[google.protobuf.duration_pb2.Duration]: ...
    @property
    def array_value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Array]: ...
    @property
    def tuple_value(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Tuple]: ...
    @property
    def uint64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    @property
    def sint64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]: ...
    def __init__(self,
        *,
        float_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        double_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        bytes_value: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        bool_value: typing.Optional[typing.Iterable[builtins.bool]] = ...,
        string_value: typing.Optional[typing.Iterable[typing.Text]] = ...,
        uint32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sint32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        timestamp_value: typing.Optional[typing.Iterable[google.protobuf.timestamp_pb2.Timestamp]] = ...,
        duration_value: typing.Optional[typing.Iterable[google.protobuf.duration_pb2.Duration]] = ...,
        array_value: typing.Optional[typing.Iterable[global___Array]] = ...,
        tuple_value: typing.Optional[typing.Iterable[global___Tuple]] = ...,
        uint64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        sint64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["array_value",b"array_value","bool_value",b"bool_value","bytes_value",b"bytes_value","double_value",b"double_value","duration_value",b"duration_value","float_value",b"float_value","sint32_value",b"sint32_value","sint64_value",b"sint64_value","string_value",b"string_value","timestamp_value",b"timestamp_value","tuple_value",b"tuple_value","uint32_value",b"uint32_value","uint64_value",b"uint64_value"]) -> None: ...
global___Array = Array
