

import inspect
import typing

from starlette.requests import Request
from starlette.responses import Response
from starlette.types import ASGIApp, Receive, Scope, Send

STYLES = ...
JS = ...
TEMPLATE = ...
FRAME_TEMPLATE = ...
LINE = ...
CENTER_LINE = ...

class ServerErrorMiddleware:
    """
    Handles returning 500 responses when a server error occurs.

    If 'debug' is set, then traceback responses will be returned,
    otherwise the designated 'handler' will be called.

    This middleware class should generally be used to wrap *everything*
    else up, so that unhandled exceptions anywhere in the stack
    always result in an appropriate 500 response.
    """

    def __init__(
        self, app: ASGIApp, handler: typing.Callable = ..., debug: bool = ...
    ) -> None: ...
    async def __call__(self, scope: Scope, receive: Receive, send: Send) -> None: ...
    def format_line(
        self, index: int, line: str, frame_lineno: int, frame_index: int
    ) -> str: ...
    def generate_frame_html(
        self, frame: inspect.FrameInfo, is_collapsed: bool
    ) -> str: ...
    def generate_html(self, exc: Exception, limit: int = ...) -> str: ...
    def generate_plain_text(self, exc: Exception) -> str: ...
    def debug_response(self, request: Request, exc: Exception) -> Response: ...
    def error_response(self, request: Request, exc: Exception) -> Response: ...
