from pandas._typing import StorageOptions
from pandas.io.excel._base import BaseExcelReader

class XlrdReader(BaseExcelReader):
    def __init__(
        self, filepath_or_buffer, storage_options: StorageOptions = ...
    ) -> None: ...
    def load_workbook(self, filepath_or_buffer): ...
    @property
    def sheet_names(self): ...
    def get_sheet_by_name(self, name): ...
    def get_sheet_by_index(self, index): ...
    def get_sheet_data(self, sheet, convert_float): ...
