
"""Deprecation messages and bits of code used elsewhere in the codebase that
is planned to be removed in the next pytest release.

Keeping it in a central location makes it easy to track what is deprecated and should
be removed when the time comes.

All constants defined in this module should be either instances of
:class:`PytestWarning`, or :class:`UnformattedWarning`
in case of warnings which need to format their messages.
"""
DEPRECATED_EXTERNAL_PLUGINS = ...
FILLFUNCARGS = ...
PYTEST_COLLECT_MODULE = ...
YIELD_FIXTURE = ...
MINUS_K_DASH = ...
MINUS_K_COLON = ...
WARNING_CAPTURED_HOOK = ...
FSCOLLECTOR_GETHOOKPROXY_ISINITPATH = ...
STRICT_OPTION = ...
PRIVATE = ...
def check_ispytest(ispytest: bool) -> None:
    ...

