# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import bentoml_service_v1alpha1_pb2 as bentoml__service__v1alpha1__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bentoml_service_v1alpha1_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BentoServiceStub(object):
    """The BentoService service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CallStream = channel.unary_stream(
                '/bentoml.grpc.v1alpha1.BentoService/CallStream',
                request_serializer=bentoml__service__v1alpha1__pb2.Request.SerializeToString,
                response_deserializer=bentoml__service__v1alpha1__pb2.Response.FromString,
                _registered_method=True)


class BentoServiceServicer(object):
    """The BentoService service definition.
    """

    def CallStream(self, request, context):
        """A streaming RPC method that accepts a Request message and returns a stream of Response messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BentoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CallStream': grpc.unary_stream_rpc_method_handler(
                    servicer.CallStream,
                    request_deserializer=bentoml__service__v1alpha1__pb2.Request.FromString,
                    response_serializer=bentoml__service__v1alpha1__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bentoml.grpc.v1alpha1.BentoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bentoml.grpc.v1alpha1.BentoService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BentoService(object):
    """The BentoService service definition.
    """

    @staticmethod
    def CallStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/bentoml.grpc.v1alpha1.BentoService/CallStream',
            bentoml__service__v1alpha1__pb2.Request.SerializeToString,
            bentoml__service__v1alpha1__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
