#!/bin/bash

set -e

WORKSPACE=$(bazel info workspace)

pushd "$WORKSPACE" >/dev/null
BIN_FOLDER="$(bazel info bazel-bin)"

# We will use BentoML tools/bazel.rc
echo "Building shared C++ gRPC..."
if ! [ -f "$BAZEL_BIN/external/com_github_grpc_grpc/src/compiler/grpc_php_plugin" ]; then
	echo "We will compile grpc_php_plugin from source."
	bazel build @com_github_grpc_grpc//src/compiler:grpc_php_plugin
fi

PLUGIN_PATH="$BIN_FOLDER/external/com_github_grpc_grpc/src/compiler/grpc_php_plugin"

echo "Generate PHP stubs."
pushd "$WORKSPACE"/src >/dev/null
bazel run @com_google_protobuf//:protoc -- -I"$(pwd)" \
	-I "$BIN_FOLDER/external/com_google_protobuf/_virtual_imports/struct_proto" \
	-I "$BIN_FOLDER/external/com_google_protobuf/_virtual_imports/wrappers_proto" \
	--php_out="$(pwd)"/../grpc-client/php --grpc_out="$(pwd)"/../grpc-client/php --plugin=protoc-gen-grpc="$PLUGIN_PATH" "$(pwd)"/bentoml/grpc/v1alpha1/service.proto
bazel run @com_google_protobuf//:protoc -- -I"$(pwd)" \
	-I "$BIN_FOLDER/external/com_google_protobuf/_virtual_imports/struct_proto" \
	-I "$BIN_FOLDER/external/com_google_protobuf/_virtual_imports/wrappers_proto" \
	--php_out="$(pwd)"/../grpc-client/php --grpc_out="$(pwd)"/../grpc-client/php --plugin=protoc-gen-grpc="$PLUGIN_PATH" "$(pwd)"/bentoml/grpc/v1/service.proto

popd >/dev/null
popd >/dev/null
