from typing import TYPE_CHECKING
from pandas._typing import Dtype
from pandas.core.frame import DataFrame
from pandas.core.indexes.api import MultiIndex
from pandas.util._decorators import cache_readonly

if TYPE_CHECKING: ...

class _Unstacker:
    def __init__(self, index: MultiIndex, level=..., constructor=...) -> None: ...
    @cache_readonly
    def sorted_labels(self): ...
    def get_result(self, values, value_columns, fill_value): ...
    def get_new_values(self, values, fill_value=...): ...
    def get_new_columns(self, value_columns): ...
    @cache_readonly
    def new_index(self): ...

def unstack(obj, level, fill_value=...): ...
def stack(frame, level=..., dropna=...): ...
def stack_multiple(frame, level, dropna=...): ...
def get_dummies(
    data,
    prefix=...,
    prefix_sep=...,
    dummy_na: bool = ...,
    columns=...,
    sparse: bool = ...,
    drop_first: bool = ...,
    dtype: Dtype | None = ...,
) -> DataFrame: ...
