class CSSWarning(UserWarning): ...

class CSSResolver:
    UNIT_RATIOS = ...
    FONT_SIZE_RATIOS = ...
    MARGIN_RATIOS = ...
    BORDER_WIDTH_RATIOS = ...
    SIDE_SHORTHANDS = ...
    SIDES = ...
    def __call__(
        self, declarations_str: str, inherited: dict[str, str] | None = ...
    ) -> dict[str, str]: ...
    def size_to_pt(self, in_val, em_pt=..., conversions=...): ...
    def atomize(self, declarations): ...
    expand_border_color = ...
    expand_border_style = ...
    expand_border_width = ...
    expand_margin = ...
    expand_padding = ...
