from typing import Any, Iterable
from pandas.io.formats.format import DataFrameFormatter

class HTMLFormatter:
    indent_delta = ...
    def __init__(
        self,
        formatter: DataFrameFormatter,
        classes: str | list[str] | tuple[str, ...] | None = ...,
        border: int | None = ...,
        table_id: str | None = ...,
        render_links: bool = ...,
    ) -> None: ...
    def to_string(self) -> str: ...
    def render(self) -> list[str]: ...
    @property
    def should_show_dimensions(self): ...
    @property
    def show_row_idx_names(self) -> bool: ...
    @property
    def show_col_idx_names(self) -> bool: ...
    @property
    def row_levels(self) -> int: ...
    @property
    def is_truncated(self) -> bool: ...
    @property
    def ncols(self) -> int: ...
    def write(self, s: Any, indent: int = ...) -> None: ...
    def write_th(
        self, s: Any, header: bool = ..., indent: int = ..., tags: str | None = ...
    ) -> None: ...
    def write_td(self, s: Any, indent: int = ..., tags: str | None = ...) -> None: ...
    def write_tr(
        self,
        line: Iterable,
        indent: int = ...,
        indent_delta: int = ...,
        header: bool = ...,
        align: str | None = ...,
        tags: dict[int, str] | None = ...,
        nindex_levels: int = ...,
    ) -> None: ...

class NotebookFormatter(HTMLFormatter):
    def write_style(self) -> None: ...
    def render(self) -> list[str]: ...
