from pandas.io.formats.format import DataFrameFormatter

class StringFormatter:
    def __init__(
        self, fmt: DataFrameFormatter, line_width: int | None = ...
    ) -> None: ...
    def to_string(self) -> str: ...
