%YAML 1.2
---
# CUDA dependencies
components:
  cudart:
    version: 11.5.117-1
  cudart_dev:
    version: 11.5.117-1
  libcublas:
    version: 11.7.4.6-1
  libcublas_dev:
    version: 11.7.4.6-1
  libcusparse:
    version: 11.7.0.107-1
  libcusparse_dev:
    version: 11.7.0.107-1
  libnpp:
    version: 11.5.1.107-1
  libnpp_dev:
    version: 11.5.1.107-1
  nvml_dev:
    version: 11.5.50-1
  nvtx:
    version: 11.5.114-1
  libnccl2:
    version: 2.11.4-1
  libnccl2_dev:
    version: 2.11.4-1
  cudnn8:
    version: 8.3.1.22-1
  nvprof:
    version: 11.5.114-1
requires: 'cuda>=11.5'
...
