from typing import Any
import numpy as np
from pandas._typing import ArrayLike, Shape

def comp_method_OBJECT_ARRAY(op, x, y): ...
def arithmetic_op(left: ArrayLike, right: Any, op): ...
def comparison_op(left: ArrayLike, right: Any, op) -> ArrayLike: ...
def na_logical_op(x: np.ndarray, y, op): ...
def logical_op(left: ArrayLike, right: Any, op) -> ArrayLike: ...
def get_array_op(op): ...
def maybe_prepare_scalar_for_op(obj, shape: Shape): ...

_BOOL_OP_NOT_ALLOWED = ...
