#!/usr/bin/env bash

set -ex

SCRIPTS_DIR="$(cd "$(dirname "${BASHSOURCE[0]}" )" && pwd)"
TEST_PATH=$(realpath "${SCRIPTS_DIR}/../")

echo "$TEST_PATH"

for test in $(find "$TEST_PATH" -iname )
$HOME/.local/bin/bats --tap "${test}"
