import types

STRING_TYPES = ...

def py_str(x): ...
def lazy_isinstance(instance, module, name): ...

class LazyLoader(types.ModuleType):
    def __init__(
        self, local_name, parent_module_globals, name, warning=...
    ) -> None: ...
    def __getattr__(self, item): ...
    def __dir__(self): ...
