from typing import Any, Callable, List, Optional
import numpy as np

def init(args: Optional[List[bytes]] = ...) -> None: ...
def finalize() -> None: ...
def get_rank() -> int: ...
def get_world_size() -> int: ...
def is_distributed() -> int: ...
def tracker_print(msg: Any) -> None: ...
def get_processor_name() -> bytes: ...

T = ...

def broadcast(data: T, root: int) -> T: ...

DTYPE_ENUM__ = ...

class Op:
    MAX = ...
    MIN = ...
    SUM = ...
    OR = ...

def allreduce(
    data: np.ndarray, op: int, prepare_fun: Optional[Callable[[np.ndarray], None]] = ...
) -> np.ndarray: ...
def version_number() -> int: ...
