# syntax = docker/dockerfile:1.2

FROM python:3.8-alpine as node_builder

RUN apk add curl gcc musl-dev libffi-dev

ENV NODE_VERSION="17.1.0"

RUN curl -fsSLO --compressed "https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/node-v$NODE_VERSION-linux-x64-musl.tar.xz"
RUN curl -fsSLO --compressed "https://unofficial-builds.nodejs.org/download/release/v$NODE_VERSION/SHASUMS256.txt"
RUN grep " node-v$NODE_VERSION-linux-x64-musl.tar.xz\$" SHASUMS256.txt | sha256sum -c -
RUN tar -xf "node-v$NODE_VERSION-linux-x64-musl.tar.xz"

FROM python:3.8-alpine

ENV NODE_VERSION="17.1.0"

COPY --from=node_builder /node-v"$NODE_VERSION"-linux-x64-musl /usr/local

RUN apk add libstdc++ gcc build-base bash git
RUN npm i -g npm@^7 yarn pyright

RUN pip install -U pip setuptools
# TODO: Should we sync this with setup.py and add documentations dependencies?
RUN pip install "mypy>=0.910" "pylint>=2.9.3" "black==21.4b2" "flake8>=3.8.2" "isort>=5.0.0"

WORKDIR "/bentoml"
