from enum import Enum

parser_defaults = ...

class ParserBase:
    class BadLineHandleMethod(Enum):
        ERROR = ...
        WARN = ...
        SKIP = ...
    _implicit_index: bool = ...
    _first_chunk: bool
    def __init__(self, kwds) -> None: ...
    def close(self): ...

def is_index_col(col) -> bool: ...
