from collections import abc
from typing import Iterator
from pandas._typing import FilePathOrBuffer
from pandas.io.parsers.base_parser import ParserBase

_BOM = ...

class PythonParser(ParserBase):
    def __init__(self, f: FilePathOrBuffer | list, **kwds) -> None: ...
    def read(self, rows=...): ...
    def get_chunk(self, size=...): ...
    _implicit_index = ...

class FixedWidthReader(abc.Iterator):
    def __init__(
        self, f, colspecs, delimiter, comment, skiprows=..., infer_nrows=...
    ) -> None: ...
    def get_rows(self, infer_nrows, skiprows=...): ...
    def detect_colspecs(self, infer_nrows=..., skiprows=...): ...
    def __next__(self): ...

class FixedWidthFieldParser(PythonParser):
    def __init__(self, f, **kwds) -> None: ...

def count_empty_vals(vals) -> int: ...
