from enum import IntEnum
from enum import unique

@unique
class ResourceType(IntEnum):
    unknown = ...
    directory = ...
    file = ...
    character = ...
    block_special_file = ...
    fifo = ...
    socket = ...
    symlink = ...

@unique
class Seek(IntEnum):
    current = ...
    end = ...
    set = ...
