import typing
from typing import SupportsInt, Text

if typing.TYPE_CHECKING: ...
__all__ = ["traditional", "decimal", "binary"]

def traditional(size: SupportsInt) -> Text: ...
def binary(size: SupportsInt) -> Text: ...
def decimal(size: SupportsInt) -> Text: ...
