

import typing
from datetime import datetime
from typing import Optional

"""Time related tools.
"""
if typing.TYPE_CHECKING: ...
utcfromtimestamp = ...
utclocalize = ...
GMT = ...

def datetime_to_epoch(d: datetime) -> int:
    """Convert datetime to epoch."""
    ...

@typing.overload
def epoch_to_datetime(t: None) -> None: ...
@typing.overload
def epoch_to_datetime(t: int) -> datetime: ...
def epoch_to_datetime(t: Optional[int]) -> Optional[datetime]:
    """Convert epoch time to a UTC datetime."""
    ...
