from typing import Callable

GLOBAL_USE_NUMBA: bool = ...
NUMBA_FUNC_CACHE: dict[tuple[Callable, str], Callable] = ...

def maybe_use_numba(engine: str | None) -> bool: ...
def set_use_numba(enable: bool = ...) -> None: ...
def get_jit_arguments(
    engine_kwargs: dict[str, bool] | None = ..., kwargs: dict | None = ...
) -> tuple[bool, bool, bool]: ...
def jit_user_function(
    func: Callable, nopython: bool, nogil: bool, parallel: bool
) -> Callable: ...
