import sys

if "setuptools" in sys.modules:
    have_setuptools = ...
else:
    have_setuptools = ...
numpy_cmdclass = ...
if have_setuptools: ...

def get_distribution(always=...): ...
def setup(**attr): ...
