from distutils.log import Log as old_Log
from distutils.log import *

class Log(old_Log):
    def good(self, msg, *args):
        """
        If we log WARN messages, log this message as a 'nice' anti-warn
        message.

        """
        ...

good = ...

def set_threshold(level, force=...): ...
def get_threshold(): ...
def set_verbosity(v, force=...): ...

_global_color_map = ...
