from pandas.core.shared_docs import _shared_docs

_shared_docs = ...

def create_section_header(header: str) -> str: ...

template_header = ...
template_returns = ...
template_see_also = ...
args_compat = ...
kwargs_compat = ...
kwargs_scipy = ...
window_apply_parameters = ...
numba_notes = ...
window_agg_numba_parameters = ...
