from typing import Dict, Optional

def generate_online_numba_ewma_func(engine_kwargs: Optional[Dict[str, bool]]): ...

class EWMMeanState:
    def __init__(self, com, adjust, ignore_na, axis, shape) -> None: ...
    def run_ewm(self, weighted_avg, deltas, min_periods, ewm_func): ...
    def reset(self): ...
