#!/usr/bin/env sh

set -e

: "${OVERRIDE:=false}"

: "${DEBUG:=false}"
[ "${DEBUG}" = "true" ] && set -x && OVERRIDE=true

: "${MODEL_TYPE:=yolov5s}"
: "${UPDATE_YOLOV5}"

BASEDIR="$(cd "$(dirname "$0")" && pwd)"

[ "${UPDATE_YOLOV5}" = "true" ] && [ -d "$BASEDIR/yolov5" ] && \rm -rf yolov5

main() {
	prev_dir="$(pwd)"
	cd "$BASEDIR"

	! [ -d yolov5 ] &&
		mkdir -p yolov5 && cd yolov5 &&
		! [ -d yolov5.git ] && git clone --bare https://github.com/ultralytics/yolov5.git &&
		git --git-dir=./yolov5.git --work-tree=. checkout HEAD -- data models utils LICENSE detect.py export.py val.py requirements.txt && \rm -rf yolov5.git && cd "${BASEDIR}"

	args="--dynamic"
	exported="onnx saved_model torchscript"

	for ex in ${exported}; do
		exists=0
		case "$ex" in
		saved_model)
			[ -d "${BASEDIR}/${MODEL_TYPE}_${ex}" ] && exists=1
			[ "${OVERRIDE}" = "true" ] && \rm -rf "${BASEDIR}/${MODEL_TYPE}_${ex}"
			! [ -d "${BASEDIR}/model_repository/tensorflow_${MODEL_TYPE}/1" ] && mkdir -p "${BASEDIR}/model_repository/tensorflow_${MODEL_TYPE}/1"
			[ -d "${BASEDIR}/model_repository/tensorflow_${MODEL_TYPE}/1/model.savedmodel" ] && \rm -rf "$BASEDIR/model_repository/tensorflow_${MODEL_TYPE}/1/model.savedmodel"
			;;
		*)
			! [ -d "${BASEDIR}/model_repository/${ex}_${MODEL_TYPE}/1" ] && mkdir -p "${BASEDIR}/model_repository/${ex}_${MODEL_TYPE}/1"
			[ -f "${BASEDIR}/${MODEL_TYPE}.${ex}" ] && exists=1
			[ "${OVERRIDE}" = "true" ] && \rm -rf "${BASEDIR}/${MODEL_TYPE}.${ex}"
			;;
		esac
		[ "${exists}" -eq 0 ] || [ "$OVERRIDE" = "true" ] && python3 yolov5/export.py --weights "$MODEL_TYPE.pt" --include "$ex" --batch-size "$1" ${args}
		case "$ex" in
		onnx)
			# ONNX
			cp "${BASEDIR}/${MODEL_TYPE}.onnx" "${BASEDIR}/model_repository/onnx_${MODEL_TYPE}/1/model.onnx"
			;;
		saved_model)
			# TensorFlow SavedModel
			cp -r "${BASEDIR}/${MODEL_TYPE}_saved_model" "${BASEDIR}/model_repository/tensorflow_${MODEL_TYPE}/1/model.savedmodel"
			;;
		torchscript)
			# TorchScript
			cp "${BASEDIR}/${MODEL_TYPE}.torchscript" "${BASEDIR}/model_repository/torchscript_${MODEL_TYPE}/1/model.pt"
			;;
		esac
	done

	echo "Successfully export YOLOv5 weights for ${exported}"
	cd "${prev_dir}"
}

if ! [ "$#" -eq 1 ]; then
	echo "Usage: $0 <batch_size>. Set to 1 by default if not passed."
	main 1
else
	main "$@"
fi
