import numpy as np

"""
masked_reductions.py is for reduction algorithms using a mask-based approach
for missing values.
"""

def sum(
    values: np.ndarray, mask: np.ndarray, *, skipna: bool = ..., min_count: int = ...
): ...
def prod(
    values: np.ndarray, mask: np.ndarray, *, skipna: bool = ..., min_count: int = ...
): ...
def min(values: np.ndarray, mask: np.ndarray, *, skipna: bool = ...): ...
def max(values: np.ndarray, mask: np.ndarray, *, skipna: bool = ...): ...
def mean(values: np.ndarray, mask: np.ndarray, skipna: bool = ...): ...
