import numpy as np

def sum(
    values: np.ndarray, mask: np.ndarray, *, skipna: bool = ..., min_count: int = ...
): ...
def prod(
    values: np.ndarray, mask: np.ndarray, *, skipna: bool = ..., min_count: int = ...
): ...
def min(values: np.ndarray, mask: np.ndarray, *, skipna: bool = ...): ...
def max(values: np.ndarray, mask: np.ndarray, *, skipna: bool = ...): ...
