from typing import Any
import numpy as np
from pandas._typing import ArrayLike

def putmask_inplace(values: ArrayLike, mask: np.ndarray, value: Any) -> None: ...
def putmask_smart(values: np.ndarray, mask: np.ndarray, new) -> np.ndarray: ...
def putmask_without_repeat(values: np.ndarray, mask: np.ndarray, new: Any) -> None: ...
def validate_putmask(
    values: ArrayLike, mask: np.ndarray
) -> tuple[np.ndarray, bool]: ...
def extract_bool_array(mask: ArrayLike) -> np.ndarray: ...
