from typing import TYPE_CHECKING, overload
import numpy as np
from pandas._typing import ArrayLike
from pandas.core.arrays.base import ExtensionArray

if TYPE_CHECKING: ...

@overload
def take_nd(
    arr: np.ndarray, indexer, axis: int = ..., fill_value=..., allow_fill: bool = ...
) -> np.ndarray: ...
@overload
def take_nd(
    arr: ExtensionArray,
    indexer,
    axis: int = ...,
    fill_value=...,
    allow_fill: bool = ...,
) -> ArrayLike: ...
def take_nd(
    arr: ArrayLike, indexer, axis: int = ..., fill_value=..., allow_fill: bool = ...
) -> ArrayLike: ...
def take_1d(
    arr: ArrayLike, indexer: np.ndarray, fill_value=..., allow_fill: bool = ...
) -> ArrayLike: ...
def take_2d_multi(
    arr: np.ndarray, indexer: tuple[np.ndarray, np.ndarray], fill_value=...
) -> np.ndarray: ...

_take_1d_dict = ...
_take_2d_axis0_dict = ...
_take_2d_axis1_dict = ...
_take_2d_multi_dict = ...
