#!/usr/bin/env sh

export BUILDX_NO_DEFAULT_LOAD=true

GIT_ROOT=$(git rev-parse --show-toplevel)

cd "$GIT_ROOT" || exit 1

TRITON_GENERATED_PB3_DIR="src/bentoml/_internal/integrations/triton/_generated_pb3"
\rm -rf "$GIT_ROOT/${TRITON_GENERATED_PB3_DIR:?}"
docker buildx build --build-arg GENERATED_PB3_DIR="${TRITON_GENERATED_PB3_DIR}" \
        --target "triton-protobuf-3-output" --output "type=local,dest=${TRITON_GENERATED_PB3_DIR}" \
        --file "tools/dev.Dockerfile" .

TRITON_GENERATED_PB4_DIR="src/bentoml/_internal/integrations/triton/_generated_pb4"
\rm -rf "$GIT_ROOT/${TRITON_GENERATED_PB4_DIR:?}"
docker buildx build --build-arg GENERATED_PB4_DIR="${TRITON_GENERATED_PB4_DIR}" \
        --target "triton-protobuf-4-output" --output "type=local,dest=${TRITON_GENERATED_PB4_DIR}" \
        --file "tools/dev.Dockerfile" .
