#!/bin/bash

set -e

BASEDIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]:-$0}")" &>/dev/null && pwd 2>/dev/null)"

# NOTE that we are using local bazel instead of system bazel.
BAZEL_BIN="$BASEDIR/bazel"

case $(uname -s) in
"Linux")
	"${BAZEL_BIN}" run //:pypi-linux.update
	;;
"Darwin")
	"${BAZEL_BIN}" run //:pypi-macos.update
	;;
"MINGW"* | "MSYS_NT"*)
	"${BAZEL_BIN}" run //:pypi-windows.update
	;;
*)
	echo "Unsupported OS: $(uname -s)" >&2
	exit 1
	;;
esac
