from .base_operator import QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase

class QLinearActivation(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def QuantizeClipRelu(self): ...
    def quantize(self): ...

class QDQRemovableActivation(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
