from .base_operator import QuantOperatorBase
from .qdq_base_operator import QDQOperatorBase

class ConvInteger(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def add_bias(self, nodes, scaled_output): ...
    def quantize(self): ...

class QLinearConv(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self): ...

class QDQConv(QDQOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
