from .base_operator import QuantOperatorBase

class MatMulInteger(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self): ...

class QLinearMatMul(QuantOperatorBase):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
