from .direct_q8 import Direct8BitOp, QDQDirect8BitOp

class QMaxPool(Direct8BitOp):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
    def quantize(self): ...

class QDQMaxPool(QDQDirect8BitOp):
    def __init__(self, onnx_quantizer, onnx_node) -> None: ...
