# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: labels_selector.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='labels_selector.proto',
  package='bentoml',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x15labels_selector.proto\x12\x07\x62\x65ntoml\"\x9c\x03\n\x0eLabelsSelector\x12>\n\x0cmatch_labels\x18\x01 \x03(\x0b\x32(.bentoml.LabelsSelector.MatchLabelsEntry\x12J\n\x11match_expressions\x18\x02 \x03(\x0b\x32/.bentoml.LabelsSelector.LabelSelectorExpression\x1a\xc9\x01\n\x17LabelSelectorExpression\x12O\n\x08operator\x18\x01 \x01(\x0e\x32=.bentoml.LabelsSelector.LabelSelectorExpression.OPERATOR_TYPE\x12\x0b\n\x03key\x18\x02 \x01(\t\x12\x0e\n\x06values\x18\x03 \x03(\t\"@\n\rOPERATOR_TYPE\x12\x06\n\x02In\x10\x00\x12\t\n\x05NotIn\x10\x01\x12\n\n\x06\x45xists\x10\x02\x12\x10\n\x0c\x44oesNotExist\x10\x03\x1a\x32\n\x10MatchLabelsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x62\x06proto3'
)



_LABELSSELECTOR_LABELSELECTOREXPRESSION_OPERATOR_TYPE = _descriptor.EnumDescriptor(
  name='OPERATOR_TYPE',
  full_name='bentoml.LabelsSelector.LabelSelectorExpression.OPERATOR_TYPE',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='In', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NotIn', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Exists', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DoesNotExist', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=331,
  serialized_end=395,
)
_sym_db.RegisterEnumDescriptor(_LABELSSELECTOR_LABELSELECTOREXPRESSION_OPERATOR_TYPE)


_LABELSSELECTOR_LABELSELECTOREXPRESSION = _descriptor.Descriptor(
  name='LabelSelectorExpression',
  full_name='bentoml.LabelsSelector.LabelSelectorExpression',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operator', full_name='bentoml.LabelsSelector.LabelSelectorExpression.operator', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='bentoml.LabelsSelector.LabelSelectorExpression.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='bentoml.LabelsSelector.LabelSelectorExpression.values', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _LABELSSELECTOR_LABELSELECTOREXPRESSION_OPERATOR_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=395,
)

_LABELSSELECTOR_MATCHLABELSENTRY = _descriptor.Descriptor(
  name='MatchLabelsEntry',
  full_name='bentoml.LabelsSelector.MatchLabelsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='bentoml.LabelsSelector.MatchLabelsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='bentoml.LabelsSelector.MatchLabelsEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=397,
  serialized_end=447,
)

_LABELSSELECTOR = _descriptor.Descriptor(
  name='LabelsSelector',
  full_name='bentoml.LabelsSelector',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='match_labels', full_name='bentoml.LabelsSelector.match_labels', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='match_expressions', full_name='bentoml.LabelsSelector.match_expressions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_LABELSSELECTOR_LABELSELECTOREXPRESSION, _LABELSSELECTOR_MATCHLABELSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=447,
)

_LABELSSELECTOR_LABELSELECTOREXPRESSION.fields_by_name['operator'].enum_type = _LABELSSELECTOR_LABELSELECTOREXPRESSION_OPERATOR_TYPE
_LABELSSELECTOR_LABELSELECTOREXPRESSION.containing_type = _LABELSSELECTOR
_LABELSSELECTOR_LABELSELECTOREXPRESSION_OPERATOR_TYPE.containing_type = _LABELSSELECTOR_LABELSELECTOREXPRESSION
_LABELSSELECTOR_MATCHLABELSENTRY.containing_type = _LABELSSELECTOR
_LABELSSELECTOR.fields_by_name['match_labels'].message_type = _LABELSSELECTOR_MATCHLABELSENTRY
_LABELSSELECTOR.fields_by_name['match_expressions'].message_type = _LABELSSELECTOR_LABELSELECTOREXPRESSION
DESCRIPTOR.message_types_by_name['LabelsSelector'] = _LABELSSELECTOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LabelsSelector = _reflection.GeneratedProtocolMessageType('LabelsSelector', (_message.Message,), {

  'LabelSelectorExpression' : _reflection.GeneratedProtocolMessageType('LabelSelectorExpression', (_message.Message,), {
    'DESCRIPTOR' : _LABELSSELECTOR_LABELSELECTOREXPRESSION,
    '__module__' : 'labels_selector_pb2'
    # @@protoc_insertion_point(class_scope:bentoml.LabelsSelector.LabelSelectorExpression)
    })
  ,

  'MatchLabelsEntry' : _reflection.GeneratedProtocolMessageType('MatchLabelsEntry', (_message.Message,), {
    'DESCRIPTOR' : _LABELSSELECTOR_MATCHLABELSENTRY,
    '__module__' : 'labels_selector_pb2'
    # @@protoc_insertion_point(class_scope:bentoml.LabelsSelector.MatchLabelsEntry)
    })
  ,
  'DESCRIPTOR' : _LABELSSELECTOR,
  '__module__' : 'labels_selector_pb2'
  # @@protoc_insertion_point(class_scope:bentoml.LabelsSelector)
  })
_sym_db.RegisterMessage(LabelsSelector)
_sym_db.RegisterMessage(LabelsSelector.LabelSelectorExpression)
_sym_db.RegisterMessage(LabelsSelector.MatchLabelsEntry)


_LABELSSELECTOR_MATCHLABELSENTRY._options = None
# @@protoc_insertion_point(module_scope)
