np = ...

class KeyValue:
    __slots__ = ...
    @classmethod
    def GetRootAsKeyValue(cls, buf, offset): ...
    def Init(self, buf, pos): ...
    def Key(self): ...
    def Value(self): ...

def KeyValueStart(builder): ...
def KeyValueAddKey(builder, key): ...
def KeyValueAddValue(builder, value): ...
def KeyValueEnd(builder): ...
