np = ...

class TrtTable:
    __slots__ = ...
    @classmethod
    def GetRootAsTrtTable(cls, buf, offset): ...
    def Init(self, buf, pos): ...
    def Dict(self, j): ...
    def DictLength(self): ...
    def DictIsNone(self): ...

def TrtTableStart(builder): ...
def TrtTableAddDict(builder, dict): ...
def TrtTableStartDictVector(builder, numElems): ...
