"""
Provide basic components for groupby. These definitions
hold the allowlist of methods that are exposed on the
SeriesGroupBy and the DataFrameGroupBy objects.
"""
OutputKey = ...
plotting_methods = ...
common_apply_allowlist = ...
series_apply_allowlist: frozenset[str] = ...
dataframe_apply_allowlist: frozenset[str] = ...
cythonized_kernels = ...
reduction_kernels = ...
transformation_kernels = ...
groupby_other_methods = ...
transform_kernel_allowlist = ...
