"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import bentoml.grpc.service_pb2
import google.protobuf.empty_pb2
import grpc

class BentoServiceStub:
    """a gRPC BentoServer."""
    def __init__(self, channel: grpc.Channel) -> None: ...
    HealthCheck: grpc.UnaryUnaryMultiCallable[
        google.protobuf.empty_pb2.Empty,
        bentoml.grpc.service_pb2.HealthCheckResponse]
    """HealthCheck defines a rpc for service health."""

    Call: grpc.UnaryUnaryMultiCallable[
        bentoml.grpc.service_pb2.CallRequest,
        bentoml.grpc.service_pb2.CallResponse]
    """Call takes a `CallRequest` and returns `CallResponse`."""


class BentoServiceServicer(metaclass=abc.ABCMeta):
    """a gRPC BentoServer."""
    @abc.abstractmethod
    def HealthCheck(self,
        request: google.protobuf.empty_pb2.Empty,
        context: grpc.ServicerContext,
    ) -> bentoml.grpc.service_pb2.HealthCheckResponse:
        """HealthCheck defines a rpc for service health."""
        pass

    @abc.abstractmethod
    def Call(self,
        request: bentoml.grpc.service_pb2.CallRequest,
        context: grpc.ServicerContext,
    ) -> bentoml.grpc.service_pb2.CallResponse:
        """Call takes a `CallRequest` and returns `CallResponse`."""
        pass


def add_BentoServiceServicer_to_server(servicer: BentoServiceServicer, server: grpc.Server) -> None: ...
