"""SageMaker target: deploy the image as a real-time inference endpoint
(bring-your-own-container) and keep the SAME long-lived endpoint updated on
every subsequent run.

Naming and idempotency: every run derives one name,
``<endpoint_name>-<sanitized version tag>``, used for BOTH the model and the
endpoint config (separate SageMaker namespaces). When sanitizing changed the
tag, a short hash of the raw tag is appended so distinct tags (``v1.2.3`` vs
``v1-2-3``) can never alias to the same name. Models and endpoint configs
are immutable, so a same-tag redeploy deletes and recreates the exact-name
model/config it is about to create — never anything else. What happens to
the endpoint itself depends on ``describe-endpoint``:

    absent                        -> create-endpoint
    InService (different config)  -> update-endpoint (the previous config
                                     name is recorded for rollback)
    InService (this exact config) -> nothing to deploy: AWS forbids deleting
                                     the in-use config, and UpdateEndpoint
                                     requires a NEW config — a rebuild of
                                     the same tag needs a new --version
    Failed                        -> delete-endpoint + wait endpoint-deleted
                                     + create-endpoint (AWS rejects
                                     UpdateEndpoint on a Failed endpoint)
    Creating/Updating/Deleting/…  -> abort (exit 6): a concurrent operation
                                     is in progress; this script never
                                     interrupts one

Superseded models/endpoint-configs from earlier tags accumulate (they are
free); the bundle README carries the list/delete commands. This script never
deletes resources it did not just (re)create in the same run, and it NEVER
creates or modifies IAM — targets.sagemaker.execution_role_arn must already
exist (the interactive bentoml-sagemaker-deploy skill can find one or hand
an admin a ready-to-send creation snippet).

The service must already satisfy SageMaker's BYOC contract — HTTP on port
8080 (this target always injects BENTOML_PORT=8080 into the container
environment), ``GET /ping`` -> 200, ``POST /invocations`` — via the
interactive skill's service adaptation; this script deploys the image as-is.

Values in targets.sagemaker.environment travel into the model definition
(argv + describe-model visible) — never put secrets there.

Generated by the bentoml-deploy-scriptgen skill — do not edit by hand; all
tunables live in deploy.config.json.
"""

# This bundle gets committed into arbitrary user repos; the directive below
# keeps the import layout stable under any repo's ruff/isort configuration.
# isort: skip_file
from __future__ import annotations

import hashlib
import json
import re
import tempfile
import time
import urllib.parse
from pathlib import Path
from typing import TYPE_CHECKING

from ..common import EXIT_DEPLOY
from ..common import EXIT_VERIFY
from ..common import DeployError
from ..common import log
from ..common import run
from ..common import section
from ..common import warn
from ..config import ECR_HOST_RE
from ..config import SAGEMAKER_NAME_RE
from ..config import InferenceCheck
from ..config import SageMakerConfig
from ..preflight import CheckFailed
from ..preflight import _which
from ..preflight import run_checks

if TYPE_CHECKING:  # pragma: no cover - import cycle guard for type checkers
    from ..context import RunContext

_AWS_CLI_VERSION_RE = re.compile(r"aws-cli/(\d+)\.(\d+)\.(\d+)")

# Endpoint statuses during which no create/update/delete may be issued.
_BUSY_STATUSES = (
    "Creating",
    "Updating",
    "SystemUpdating",
    "RollingBack",
    "Deleting",
)

# Instance provisioning + image pull budget added on top of the container's
# own startup-health-check budget to form the Python-side overall timeout
# around `aws sagemaker wait endpoint-in-service` (which itself polls every
# 30 s and gives up after 120 polls).
_PROVISION_BUDGET_SECONDS = 1500

_ROLE_HINT = (
    "provide the ARN of an existing role whose trust policy includes "
    "sagemaker.amazonaws.com — this script never creates or modifies IAM. "
    "The interactive bentoml-sagemaker-deploy skill finds candidate roles "
    "with a trust-policy scan, and its references/aws-setup.md carries a "
    "ready-to-send admin snippet when the role must be created by an "
    "account admin."
)


def _aws_sm(sm: SageMakerConfig, *args: str) -> list[str]:
    return ["aws", "sagemaker", *args, "--region", sm.region]


def _sanitize_tag(version: str) -> str:
    """Map an image tag onto SageMaker's name alphabet (alphanumerics and
    hyphens): every run of other characters becomes one hyphen."""
    return re.sub(r"[^A-Za-z0-9]+", "-", version).strip("-")


def _derived_name(sm: SageMakerConfig, version: str) -> str:
    """The per-tag name shared by the model and the endpoint config."""
    tag = _sanitize_tag(version)
    if not tag:
        raise DeployError(
            f"version tag {version!r} sanitizes to an empty SageMaker name",
            EXIT_DEPLOY,
            hint="pass a --version containing at least one alphanumeric character",
        )
    if tag != version:
        # Sanitizing is lossy (v1.2.3 and v1-2-3 both become v1-2-3); a
        # short stable hash of the raw tag keeps distinct tags distinct —
        # otherwise a redeploy of the aliasing tag would hit the
        # already-live no-op branch and silently not deploy.
        tag += "-" + hashlib.sha256(version.encode("utf-8")).hexdigest()[:6]
    name = f"{sm.endpoint_name}-{tag}"
    if len(name) > 63 or not SAGEMAKER_NAME_RE.match(name):
        raise DeployError(
            f"derived model/endpoint-config name {name!r} is not a valid "
            "SageMaker name (max 63 chars, pattern "
            f"{SAGEMAKER_NAME_RE.pattern})",
            EXIT_DEPLOY,
            hint="shorten targets.sagemaker.endpoint_name or use a shorter "
            "--version tag",
        )
    return name


def _describe_endpoint(
    sm: SageMakerConfig, exit_code: int = EXIT_DEPLOY
) -> dict | None:
    """The endpoint's describe-endpoint document, or None if it does not
    exist."""
    res = run(
        _aws_sm(
            sm,
            "describe-endpoint",
            "--endpoint-name",
            sm.endpoint_name,
            "--output",
            "json",
        ),
        capture=True,
        quiet=True,
        check=False,
        timeout=60,
    )
    if res.returncode != 0:
        err = res.stderr.strip() or res.stdout.strip()
        if "Could not find endpoint" in err:
            return None
        raise DeployError(
            f"could not describe endpoint {sm.endpoint_name!r}: {err[:300]}",
            exit_code,
            hint="check AWS credentials, targets.sagemaker.region, and that "
            "the identity may call sagemaker:DescribeEndpoint",
        )
    try:
        return json.loads(res.stdout)
    except json.JSONDecodeError:
        raise DeployError(
            "describe-endpoint returned unparseable JSON", exit_code
        ) from None


def _resource_exists(sm: SageMakerConfig, describe_args: list, kind: str) -> bool:
    res = run(
        _aws_sm(sm, *describe_args, "--output", "json"),
        capture=True,
        quiet=True,
        check=False,
        timeout=60,
    )
    if res.returncode == 0:
        return True
    err = res.stderr.strip() or res.stdout.strip()
    if "Could not find" in err:
        return False
    raise DeployError(
        f"could not describe {kind}: {err[:300]}",
        EXIT_DEPLOY,
        hint="check AWS credentials and the sagemaker:Describe* permissions",
    )


# --------------------------------------------------------------------------
# preflight
# --------------------------------------------------------------------------


def preflight(ctx: RunContext) -> None:
    """Standalone entry point: run this target's checks in one pass."""
    run_checks(preflight_checks(ctx))


def preflight_checks(ctx: RunContext) -> list:
    """Build this target's checks so deploy.py can aggregate them with the
    build-side families into a single report. With ctx.local_only, only
    config-derived checks and CLI presence are returned; the rest are
    recorded in the summary's skipped list."""
    sm = ctx.cfg.require_sagemaker()

    def aws_cli_v2() -> str | None:
        _which("aws", "install the AWS CLI v2")
        res = run(
            ["aws", "--version"], capture=True, quiet=True, check=False, timeout=30
        )
        text = (res.stdout + res.stderr).strip()
        match = _AWS_CLI_VERSION_RE.search(text)
        if res.returncode != 0 or not match:
            raise CheckFailed(
                f"'aws --version' failed or was unparseable: {text[:200]}"
            )
        if int(match.group(1)) < 2:
            raise CheckFailed(
                f"AWS CLI v2 required, found {match.group(0)}",
                hint="v1 lacks --cli-binary-format and the waiters this "
                "target uses — install the v2 bundle from AWS",
            )
        return match.group(0)

    def resource_names() -> str | None:
        if ctx.version is None:
            raise CheckFailed(
                "no version tag resolved, so the model/endpoint-config "
                "names cannot be derived",
                hint="fix the common.git-repo failure, or pass --version/--image",
            )
        return _derived_name(sm, ctx.version)

    def aws_credentials() -> str | None:
        res = run(
            ["aws", "sts", "get-caller-identity", "--output", "json"],
            capture=True,
            quiet=True,
            check=False,
            timeout=60,
        )
        if res.returncode != 0:
            raise CheckFailed(
                "AWS credentials are not usable: "
                f"{(res.stderr.strip() or res.stdout.strip())[:300]}",
                hint="export AWS_ACCESS_KEY_ID/AWS_SECRET_ACCESS_KEY (or "
                "AWS_PROFILE, or run 'aws sso login') for an identity that "
                "may manage SageMaker endpoints",
            )
        try:
            arn = json.loads(res.stdout).get("Arn", "")
        except json.JSONDecodeError:
            arn = ""
        return arn or None

    def image_in_ecr() -> str | None:
        if ctx.image is None:
            raise CheckFailed(
                "no image reference resolved, so the ECR requirement "
                "cannot be validated",
                hint="fix the common.git-repo failure, or pass --image/--version",
            )
        host = ctx.image.split("/", 1)[0]
        if ECR_HOST_RE.match(host) is None:
            raise CheckFailed(
                f"image {ctx.image!r} is not in a private ECR registry — "
                "SageMaker requires the inference image to live in ECR in "
                "the endpoint's region",
                hint="set image.registry to "
                "<account>.dkr.ecr.<region>.amazonaws.com with "
                "image.registry_type 'ecr' (Docker Hub/GHCR images cannot "
                "back a SageMaker endpoint)",
            )
        return host

    def region_match() -> str | None:
        if ctx.image is not None:
            match = ECR_HOST_RE.match(ctx.image.split("/", 1)[0])
            if match and match.group("region") != sm.region:
                raise CheckFailed(
                    f"image is in ECR region {match.group('region')} but "
                    f"targets.sagemaker.region is {sm.region!r} — SageMaker "
                    "requires the image in the same region as the endpoint",
                    hint=f"push to an ECR repository in {sm.region} (fix "
                    "image.registry) or change targets.sagemaker.region",
                )
        if (
            ctx.cfg.image.registry_type == "ecr"
            and ctx.cfg.image.ecr_region
            and ctx.cfg.image.ecr_region != sm.region
        ):
            raise CheckFailed(
                f"image.ecr_region is {ctx.cfg.image.ecr_region!r} but "
                f"targets.sagemaker.region is {sm.region!r} — the push and "
                "the endpoint would land in different regions",
                hint="make both regions equal (SageMaker cannot pull cross-region)",
            )
        return f"region {sm.region}"

    def execution_role() -> str | None:
        role_name = sm.execution_role_arn.rsplit("/", 1)[-1]
        res = run(
            ["aws", "iam", "get-role", "--role-name", role_name, "--output", "json"],
            capture=True,
            quiet=True,
            check=False,
            timeout=60,
        )
        if res.returncode != 0:
            err = res.stderr.strip() or res.stdout.strip()
            if "AccessDenied" in err or "not authorized" in err:
                # Cannot verify != invalid: many deploy identities may
                # PassRole a role they may not GetRole.
                warn(
                    f"cannot verify execution role {role_name!r} — "
                    "iam:GetRole is denied for this identity. Continuing; "
                    "create-model will surface a wrong role or trust policy."
                )
                return "UNVERIFIED (iam:GetRole denied)"
            if "NoSuchEntity" in err:
                raise CheckFailed(
                    f"execution role {sm.execution_role_arn} does not exist",
                    hint=_ROLE_HINT,
                )
            raise CheckFailed(
                f"could not verify execution role {role_name!r}: {err[:300]}"
            )
        doc = json.loads(res.stdout).get("Role", {}).get("AssumeRolePolicyDocument")
        if isinstance(doc, str):
            # The raw IAM API returns the document URL-encoded; the CLI
            # normally decodes it into JSON, but handle both shapes.
            try:
                doc = json.loads(urllib.parse.unquote(doc))
            except (ValueError, TypeError):
                doc = None
        if not isinstance(doc, dict):
            warn(
                f"could not parse the AssumeRolePolicyDocument of "
                f"{role_name!r} — trust policy unverified"
            )
            return "exists (trust policy unverified)"
        if "sagemaker.amazonaws.com" not in json.dumps(doc):
            raise CheckFailed(
                f"role {role_name!r} exists but its trust policy does not "
                "include sagemaker.amazonaws.com — SageMaker cannot assume it",
                hint=_ROLE_HINT,
            )
        return f"{role_name} trusts sagemaker.amazonaws.com"

    checks = [("sagemaker.aws-cli", aws_cli_v2)]
    if ctx.local_only:
        ctx.summary.skipped += [
            "sagemaker.aws-credentials (--local-only)",
            "sagemaker.image-in-ecr (--local-only)",
            "sagemaker.region-match (--local-only)",
            "sagemaker.execution-role (--local-only)",
        ]
    else:
        checks += [
            ("sagemaker.aws-credentials", aws_credentials),
            ("sagemaker.image-in-ecr", image_in_ecr),
            ("sagemaker.region-match", region_match),
            ("sagemaker.execution-role", execution_role),
        ]
    checks.append(("sagemaker.resource-names", resource_names))
    return checks


# --------------------------------------------------------------------------
# deploy
# --------------------------------------------------------------------------


def _failure_guidance(sm: SageMakerConfig, previous_config: str | None) -> str:
    base = (
        "Diagnose:\n"
        f"  aws sagemaker describe-endpoint --endpoint-name {sm.endpoint_name} "
        f"--region {sm.region} "
        "--query '{Status:EndpointStatus,Reason:FailureReason}'\n"
        f'  aws logs tail "/aws/sagemaker/Endpoints/{sm.endpoint_name}" '
        f"--region {sm.region} --since 1h\n"
    )
    if previous_config:
        return base + (
            "Roll back to the previous endpoint-config (recorded before "
            "this update):\n"
            f"  aws sagemaker update-endpoint --endpoint-name {sm.endpoint_name} "
            f"--endpoint-config-name {previous_config} --region {sm.region}\n"
            "(a failed update keeps serving the previous config; the "
            "endpoint must leave Updating before a rollback is accepted)"
        )
    return base + (
        "This was the first deploy of this endpoint, so there is no "
        "previous config to roll back to. A Failed endpoint still exists "
        "and blocks re-creation under the same name — fix the cause, then "
        "delete it before re-running:\n"
        f"  aws sagemaker delete-endpoint --endpoint-name {sm.endpoint_name} "
        f"--region {sm.region}"
    )


def _run_stage(ctx: RunContext, name: str, fn) -> object:
    started = time.monotonic()
    try:
        result = fn()
    except BaseException:
        ctx.summary.record_stage(name, False, time.monotonic() - started)
        raise
    ctx.summary.record_stage(
        name,
        True,
        time.monotonic() - started,
        result if isinstance(result, str) else None,
    )
    return result


def _create_model(sm: SageMakerConfig, name: str, image: str) -> str:
    if _resource_exists(sm, ["describe-model", "--model-name", name], "model"):
        log(f"model {name} already exists (same-tag redeploy) — recreating it")
        run(
            _aws_sm(sm, "delete-model", "--model-name", name),
            capture=True,
            exit_code=EXIT_DEPLOY,
            timeout=60,
        )
    # The container definition goes over as JSON, not shorthand: shorthand
    # Environment parsing breaks on ',' / '=' inside user-provided values.
    container = json.dumps(
        {"Image": image, "Environment": {**sm.environment, "BENTOML_PORT": "8080"}}
    )
    res = run(
        _aws_sm(
            sm,
            "create-model",
            "--model-name",
            name,
            "--primary-container",
            container,
            "--execution-role-arn",
            sm.execution_role_arn,
        ),
        capture=True,
        check=False,
        timeout=60,
    )
    if res.returncode != 0:
        err = res.stderr.strip() or res.stdout.strip()
        hint = None
        if "AccessDenied" in err and "PassRole" in err:
            hint = (
                "the DEPLOYING identity needs iam:PassRole on "
                f"{sm.execution_role_arn} (this is separate from the role's "
                "own permissions) — ask an admin to grant it"
            )
        elif "Cannot assume role" in err or "assume" in err.lower():
            hint = _ROLE_HINT
        raise DeployError(
            f"create-model failed (exit {res.returncode}): {err[-500:]}",
            EXIT_DEPLOY,
            hint=hint,
        )
    return f"model {name}"


def _create_endpoint_config(sm: SageMakerConfig, name: str) -> str:
    if _resource_exists(
        sm,
        ["describe-endpoint-config", "--endpoint-config-name", name],
        "endpoint config",
    ):
        log(
            f"endpoint-config {name} already exists (same-tag redeploy) — recreating it"
        )
        run(
            _aws_sm(sm, "delete-endpoint-config", "--endpoint-config-name", name),
            capture=True,
            exit_code=EXIT_DEPLOY,
            timeout=60,
        )
    variants = json.dumps(
        [
            {
                "VariantName": "AllTraffic",
                "ModelName": name,
                "InitialInstanceCount": sm.instance_count,
                "InstanceType": sm.instance_type,
                "ContainerStartupHealthCheckTimeoutInSeconds": (
                    sm.startup_health_timeout_seconds
                ),
            }
        ]
    )
    run(
        _aws_sm(
            sm,
            "create-endpoint-config",
            "--endpoint-config-name",
            name,
            "--production-variants",
            variants,
        ),
        capture=True,
        exit_code=EXIT_DEPLOY,
        timeout=60,
    )
    return f"endpoint-config {name}"


def _delete_failed_endpoint(sm: SageMakerConfig) -> str:
    run(
        _aws_sm(sm, "delete-endpoint", "--endpoint-name", sm.endpoint_name),
        capture=True,
        exit_code=EXIT_DEPLOY,
        timeout=60,
    )
    run(
        _aws_sm(sm, "wait", "endpoint-deleted", "--endpoint-name", sm.endpoint_name),
        capture=True,
        exit_code=EXIT_DEPLOY,
        timeout=900,
    )
    return "deleted"


def _wait_in_service(sm: SageMakerConfig, previous_config: str | None) -> str:
    budget = sm.startup_health_timeout_seconds + _PROVISION_BUDGET_SECONDS
    log(
        f"waiting for endpoint {sm.endpoint_name} to be InService "
        f"(timeout {budget}s; SageMaker typically needs 5-10 min)..."
    )
    try:
        res = run(
            _aws_sm(
                sm, "wait", "endpoint-in-service", "--endpoint-name", sm.endpoint_name
            ),
            capture=True,
            check=False,
            timeout=budget,
        )
        wait_failed = res.returncode != 0
    except DeployError:  # Python-side overall timeout
        wait_failed = True
    if not wait_failed:
        log("endpoint is InService")
        return "InService"
    ep = _describe_endpoint(sm) or {}
    status = ep.get("EndpointStatus", "unknown")
    reason = ep.get("FailureReason", "") or "(no FailureReason reported)"
    raise DeployError(
        f"endpoint {sm.endpoint_name} did not reach InService within "
        f"{budget}s (status: {status}; FailureReason: {reason})",
        EXIT_DEPLOY,
        hint=_failure_guidance(sm, previous_config),
    )


def deploy(ctx: RunContext) -> None:
    sm = ctx.cfg.require_sagemaker()
    image = ctx.image or ""
    name = _derived_name(sm, ctx.version or "")
    section(
        f"deploy: SageMaker endpoint {sm.endpoint_name} "
        f"(region {sm.region}, image {image})"
    )

    endpoint = _describe_endpoint(sm)
    status = endpoint.get("EndpointStatus") if endpoint else None
    previous_config = endpoint.get("EndpointConfigName") if endpoint else None

    if status in _BUSY_STATUSES:
        raise DeployError(
            f"endpoint {sm.endpoint_name} has an operation in progress "
            f"(status: {status}) — refusing to interfere",
            EXIT_DEPLOY,
            hint="wait for it to settle (aws sagemaker wait "
            f"endpoint-in-service --endpoint-name {sm.endpoint_name} "
            f"--region {sm.region}) and re-run; concurrent deploys of the "
            "same endpoint cannot be serialized by this script",
        )
    if status is not None and status not in ("InService", "Failed"):
        raise DeployError(
            f"endpoint {sm.endpoint_name} is in unexpected status "
            f"{status!r} — refusing to guess",
            EXIT_DEPLOY,
            hint=_failure_guidance(sm, previous_config),
        )

    if status == "InService" and previous_config == name:
        # AWS forbids deleting the in-use config, and UpdateEndpoint
        # requires a config different from the running one.
        warn(
            f"endpoint {sm.endpoint_name} already serves endpoint-config "
            f"{name} (this exact version tag) — nothing to deploy. If the "
            "image was rebuilt under the same tag, deploy it under a new "
            "tag (--version)."
        )
        ctx.summary.record_stage(
            "sagemaker.endpoint", True, 0.0, detail=f"already-live ({name})"
        )
        return

    if status == "Failed":
        reason = (endpoint or {}).get("FailureReason", "") or "(none reported)"
        warn(
            f"endpoint {sm.endpoint_name} is Failed (FailureReason: "
            f"{reason}) — a Failed endpoint cannot be updated, deleting "
            "and recreating it"
        )
        _run_stage(
            ctx, "sagemaker.delete-failed-endpoint", lambda: _delete_failed_endpoint(sm)
        )
        status, previous_config = None, None

    _run_stage(ctx, "sagemaker.model", lambda: _create_model(sm, name, image))
    _run_stage(
        ctx, "sagemaker.endpoint-config", lambda: _create_endpoint_config(sm, name)
    )

    if status is None:

        def _create_endpoint() -> str:
            run(
                _aws_sm(
                    sm,
                    "create-endpoint",
                    "--endpoint-name",
                    sm.endpoint_name,
                    "--endpoint-config-name",
                    name,
                ),
                capture=True,
                exit_code=EXIT_DEPLOY,
                timeout=60,
            )
            return f"created with config {name}"

        _run_stage(ctx, "sagemaker.endpoint", _create_endpoint)
    else:  # InService with a different config

        def _update_endpoint() -> str:
            log(
                f"endpoint exists (InService, config {previous_config}) — "
                f"updating to config {name}"
            )
            res = run(
                _aws_sm(
                    sm,
                    "update-endpoint",
                    "--endpoint-name",
                    sm.endpoint_name,
                    "--endpoint-config-name",
                    name,
                ),
                capture=True,
                check=False,
                timeout=60,
            )
            if res.returncode != 0:
                err = res.stderr.strip() or res.stdout.strip()
                raise DeployError(
                    f"update-endpoint failed (exit {res.returncode}): {err[-500:]}",
                    EXIT_DEPLOY,
                    hint=_failure_guidance(sm, previous_config),
                )
            return f"updated {previous_config} -> {name}"

        _run_stage(ctx, "sagemaker.endpoint", _update_endpoint)

    _run_stage(
        ctx, "sagemaker.wait-in-service", lambda: _wait_in_service(sm, previous_config)
    )
    log(
        "deployed — remember: the endpoint bills per instance-hour until "
        "'aws sagemaker delete-endpoint' (see the README's teardown section)"
    )


# --------------------------------------------------------------------------
# verify
# --------------------------------------------------------------------------


def verify(ctx: RunContext) -> None:
    sm = ctx.cfg.require_sagemaker()
    inference = ctx.cfg.verify.inference
    section(f"verify: invoke-endpoint on {sm.endpoint_name} (region {sm.region})")
    if inference is None:
        endpoint = _describe_endpoint(sm, exit_code=EXIT_VERIFY) or {}
        status = endpoint.get("EndpointStatus", "absent")
        if status != "InService":
            raise DeployError(
                f"endpoint {sm.endpoint_name} is not InService (status: {status})",
                EXIT_VERIFY,
                hint=_failure_guidance(sm, None),
            )
        log(
            "no inference smoke test configured (verify.inference) — "
            "endpoint is InService, skipping invoke"
        )
        return
    _invoke_smoke(sm, inference)


def _invoke_smoke(sm: SageMakerConfig, inference: InferenceCheck) -> None:
    if inference.path != "/invocations":
        warn(
            f"verify.inference.path is {inference.path!r}, but SageMaker "
            "always invokes POST /invocations — the configured path is "
            "ignored for this target"
        )
    log("inference smoke test: sagemaker-runtime invoke-endpoint")
    body_file = tempfile.NamedTemporaryFile(  # noqa: SIM115 - closed in finally
        mode="w",
        prefix="bentoml-deploy-sm-body-",
        suffix=".json",
        delete=False,
        encoding="utf-8",
    )
    out_path = body_file.name + ".out"
    try:
        json.dump(inference.body, body_file)
        body_file.close()
        res = run(
            [
                "aws",
                "sagemaker-runtime",
                "invoke-endpoint",
                "--endpoint-name",
                sm.endpoint_name,
                "--content-type",
                "application/json",
                "--accept",
                "application/json",
                "--cli-binary-format",
                "raw-in-base64-out",
                "--body",
                f"fileb://{body_file.name}",
                "--region",
                sm.region,
                "--output",
                "json",
                out_path,
            ],
            capture=True,
            check=False,
            timeout=inference.timeout_seconds + 30,
        )
        if res.returncode != 0:
            err = res.stderr.strip() or res.stdout.strip()
            raise DeployError(
                f"invoke-endpoint failed (exit {res.returncode}): {err[-800:]}",
                EXIT_VERIFY,
                hint="a ModelError (424) means the container returned "
                "4xx/5xx — check the payload against the /invocations "
                "signature, and read the container logs: aws logs tail "
                f'"/aws/sagemaker/Endpoints/{sm.endpoint_name}" '
                f"--region {sm.region} --since 1h. Platform limits: 60 s "
                "per request, 6 MB bodies.",
            )
        try:
            metadata = json.loads(res.stdout)
        except json.JSONDecodeError:
            metadata = {}
        content_type = str(metadata.get("ContentType", ""))
        try:
            body = Path(out_path).read_text(encoding="utf-8", errors="replace")
        except OSError:
            body = ""
        snippet = body[:500].replace("\n", " ")
        log(f"response ContentType {content_type or '(missing)'}: {snippet}")
        if not content_type:
            raise DeployError(
                "invoke-endpoint reported no response ContentType",
                EXIT_VERIFY,
                hint="the container's /invocations response is malformed — "
                "read the CloudWatch logs (log group "
                f"/aws/sagemaker/Endpoints/{sm.endpoint_name})",
            )
        if "json" in content_type.lower():
            try:
                json.loads(body)
            except json.JSONDecodeError:
                raise DeployError(
                    f"response declares ContentType {content_type!r} but the "
                    f"body is not valid JSON (body: {snippet})",
                    EXIT_VERIFY,
                ) from None
        if inference.expect_substring and inference.expect_substring not in body:
            raise DeployError(
                "inference response did not contain expected substring "
                f"{inference.expect_substring!r} (body: {snippet})",
                EXIT_VERIFY,
            )
        log("inference smoke test passed")
    finally:
        body_file.close()
        for path in (body_file.name, out_path):
            try:
                Path(path).unlink()
            except OSError:
                pass
