"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import bentoml.grpc.v1.types_pb2
import builtins
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import typing
import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class Shape(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class Dimension(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        SIZE_FIELD_NUMBER: builtins.int
        NAME_FIELD_NUMBER: builtins.int
        size: builtins.int
        """Size of given value in that dimension."""

        name: typing.Text
        """optional name for given dimension"""

        def __init__(self,
            *,
            size: builtins.int = ...,
            name: typing.Optional[typing.Text] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["_name",b"_name","name",b"name"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["_name",b"_name","name",b"name","size",b"size"]) -> None: ...
        def WhichOneof(self, oneof_group: typing_extensions.Literal["_name",b"_name"]) -> typing.Optional[typing_extensions.Literal["name"]]: ...

    DIM_FIELD_NUMBER: builtins.int
    UNKNOWN_RANK_FIELD_NUMBER: builtins.int
    @property
    def dim(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Shape.Dimension]:
        """Dimensions of the tensor"""
        pass
    unknown_rank: builtins.bool
    """if true, the dimension is unknown."""

    def __init__(self,
        *,
        dim: typing.Optional[typing.Iterable[global___Shape.Dimension]] = ...,
        unknown_rank: builtins.bool = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["dim",b"dim","unknown_rank",b"unknown_rank"]) -> None: ...
global___Shape = Shape

class ValueType(google.protobuf.message.Message):
    """Protocol buffer representing contents of a given rpc call.
    Partial verbatim sources of tensorflow/core/framework/tensor.proto.

    One key different from the original is that since we are using proto3,
     repeated values are packed by default.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DTYPE_FIELD_NUMBER: builtins.int
    SHAPE_FIELD_NUMBER: builtins.int
    CONTENTS_FIELD_NUMBER: builtins.int
    HALF_VALUE_FIELD_NUMBER: builtins.int
    FLOAT_VALUE_FIELD_NUMBER: builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: builtins.int
    INT_VALUE_FIELD_NUMBER: builtins.int
    STRING_VALUE_FIELD_NUMBER: builtins.int
    SCOMPLEX_VALUE_FIELD_NUMBER: builtins.int
    INT64_VALUE_FIELD_NUMBER: builtins.int
    BOOL_VALUE_FIELD_NUMBER: builtins.int
    DCOMPLEX_VALUE_FIELD_NUMBER: builtins.int
    UINT32_VALUE_FIELD_NUMBER: builtins.int
    UINT64_VALUE_FIELD_NUMBER: builtins.int
    dtype: bentoml.grpc.v1.types_pb2.DataType.ValueType
    """dtype represents the data type of given contents. This would help us
    to use the correct serialization protocol on the server side if needed.
    """

    @property
    def shape(self) -> global___Shape:
        """shape represents the shape of given contents. This would help us
        to serialize any given contents to the correct shape.
        """
        pass
    contents: builtins.bytes
    """Only one of the representations below is set, one of "contents" and
    the "xxx_value" attributes.  We are not using oneof because as oneofs cannot
    contain repeated fields it would require another extra set of messages.

    Serialized raw contents. This representation
    can be used for all data types. The purpose of this representation is to
    reduce serialization overhead during RPC call by avoiding serialization of
    many repeated small items.
    """

    @property
    def half_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Type specific representations that make it easy to create protos in
        all languages.  Only the representation corresponding to "dtype" can
        be set. The values hold the flattened representation of the inputs in
        row major order.

        DT_HALF, DT_BFLOAT16. Note that since protobuf has no int16 type, we'll
        have some pointless zero padding for each value here.
        """
        pass
    @property
    def float_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """DT_FLOAT."""
        pass
    @property
    def double_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """DT_DOUBLE."""
        pass
    @property
    def int_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """DT_INT32, DT_INT16, DT_UINT16, DT_INT8, DT_UINT8."""
        pass
    @property
    def string_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bytes]:
        """DT_STRING"""
        pass
    @property
    def scomplex_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """DT_COMPLEX64. scomplex_value(2*i) and scomplex_value(2*i+1) are real
        and imaginary parts of i-th single precision complex.
        """
        pass
    @property
    def int64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """DT_INT64"""
        pass
    @property
    def bool_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.bool]:
        """DT_BOOL"""
        pass
    @property
    def dcomplex_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """DT_COMPLEX128. dcomplex_value(2*i) and dcomplex_value(2*i+1) are real
        and imaginary parts of i-th double precision complex.
        """
        pass
    @property
    def uint32_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """DT_UINT32"""
        pass
    @property
    def uint64_value(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """DT_UINT64"""
        pass
    def __init__(self,
        *,
        dtype: bentoml.grpc.v1.types_pb2.DataType.ValueType = ...,
        shape: typing.Optional[global___Shape] = ...,
        contents: builtins.bytes = ...,
        half_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        float_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        double_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        int_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        string_value: typing.Optional[typing.Iterable[builtins.bytes]] = ...,
        scomplex_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        int64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        bool_value: typing.Optional[typing.Iterable[builtins.bool]] = ...,
        dcomplex_value: typing.Optional[typing.Iterable[builtins.float]] = ...,
        uint32_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        uint64_value: typing.Optional[typing.Iterable[builtins.int]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["shape",b"shape"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["bool_value",b"bool_value","contents",b"contents","dcomplex_value",b"dcomplex_value","double_value",b"double_value","dtype",b"dtype","float_value",b"float_value","half_value",b"half_value","int64_value",b"int64_value","int_value",b"int_value","scomplex_value",b"scomplex_value","shape",b"shape","string_value",b"string_value","uint32_value",b"uint32_value","uint64_value",b"uint64_value"]) -> None: ...
global___ValueType = ValueType

class StructuredValue(google.protobuf.message.Message):
    """StructuredValue represents a dynamic typed value representing various
    data structures that are inspired by Python's data structures.
    Partial verbatim sources of tensorflow/core/protobuf/struct.proto.

    [16, 100] will be reserved for future use. Users are free to use from [3, 15]
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    DATA_FIELD_NUMBER: builtins.int
    NONE_VALUE_FIELD_NUMBER: builtins.int
    TUPLE_VALUE_FIELD_NUMBER: builtins.int
    DICT_VALUE_FIELD_NUMBER: builtins.int
    NAMEDTUPLE_VALUE_FIELD_NUMBER: builtins.int
    DATAFRAME_COLUMNS_FIELD_NUMBER: builtins.int
    DATAFRAME_INDICES_FIELD_NUMBER: builtins.int
    @property
    def data(self) -> global___ValueType:
        """Represents any value that can be represented as a payload contents."""
        pass
    @property
    def none_value(self) -> global___NoneValue:
        """Represents a None value."""
        pass
    @property
    def tuple_value(self) -> global___TupleValue:
        """Represents a tuple of `Value`.
        List can also be represented as a tuple.
        """
        pass
    @property
    def dict_value(self) -> global___DictValue:
        """Represents a dict `Value`."""
        pass
    @property
    def namedtuple_value(self) -> global___NamedTupleValue:
        """Represents Python's namedtuple."""
        pass
    @property
    def dataframe_columns(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]:
        """dataframes_columns and dataframe_indices are used
        in conjunction with contents to represent a dataframe.
        """
        pass
    @property
    def dataframe_indices(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[typing.Text]: ...
    def __init__(self,
        *,
        data: typing.Optional[global___ValueType] = ...,
        none_value: typing.Optional[global___NoneValue] = ...,
        tuple_value: typing.Optional[global___TupleValue] = ...,
        dict_value: typing.Optional[global___DictValue] = ...,
        namedtuple_value: typing.Optional[global___NamedTupleValue] = ...,
        dataframe_columns: typing.Optional[typing.Iterable[typing.Text]] = ...,
        dataframe_indices: typing.Optional[typing.Iterable[typing.Text]] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["data",b"data","dict_value",b"dict_value","kind",b"kind","namedtuple_value",b"namedtuple_value","none_value",b"none_value","tuple_value",b"tuple_value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["data",b"data","dataframe_columns",b"dataframe_columns","dataframe_indices",b"dataframe_indices","dict_value",b"dict_value","kind",b"kind","namedtuple_value",b"namedtuple_value","none_value",b"none_value","tuple_value",b"tuple_value"]) -> None: ...
    def WhichOneof(self, oneof_group: typing_extensions.Literal["kind",b"kind"]) -> typing.Optional[typing_extensions.Literal["data","none_value","tuple_value","dict_value","namedtuple_value"]]: ...
global___StructuredValue = StructuredValue

class NoneValue(google.protobuf.message.Message):
    """represents None type."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    def __init__(self,
        ) -> None: ...
global___NoneValue = NoneValue

class TupleValue(google.protobuf.message.Message):
    """Represents a Python tuple."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    VALUES_FIELD_NUMBER: builtins.int
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___StructuredValue]: ...
    def __init__(self,
        *,
        values: typing.Optional[typing.Iterable[global___StructuredValue]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["values",b"values"]) -> None: ...
global___TupleValue = TupleValue

class DictValue(google.protobuf.message.Message):
    """Represents a Python dict with key<str> and value<StructuredValue>.
    This key is analogous with Value.string_value
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    class FieldsEntry(google.protobuf.message.Message):
        DESCRIPTOR: google.protobuf.descriptor.Descriptor
        KEY_FIELD_NUMBER: builtins.int
        VALUE_FIELD_NUMBER: builtins.int
        key: typing.Text
        @property
        def value(self) -> global___StructuredValue: ...
        def __init__(self,
            *,
            key: typing.Text = ...,
            value: typing.Optional[global___StructuredValue] = ...,
            ) -> None: ...
        def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
        def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...

    FIELDS_FIELD_NUMBER: builtins.int
    @property
    def fields(self) -> google.protobuf.internal.containers.MessageMap[typing.Text, global___StructuredValue]: ...
    def __init__(self,
        *,
        fields: typing.Optional[typing.Mapping[typing.Text, global___StructuredValue]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["fields",b"fields"]) -> None: ...
global___DictValue = DictValue

class PairValue(google.protobuf.message.Message):
    """Represents a (key, value) pair."""
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    key: typing.Text
    @property
    def value(self) -> global___StructuredValue: ...
    def __init__(self,
        *,
        key: typing.Text = ...,
        value: typing.Optional[global___StructuredValue] = ...,
        ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["value",b"value"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["key",b"key","value",b"value"]) -> None: ...
global___PairValue = PairValue

class NamedTupleValue(google.protobuf.message.Message):
    """Represents a namedtuple.
    One key different from DictValue is that NamedTupleValue reserved
    the order of key value map, whereas map doesn't.
    """
    DESCRIPTOR: google.protobuf.descriptor.Descriptor
    TYPE_NAME_FIELD_NUMBER: builtins.int
    VALUES_FIELD_NUMBER: builtins.int
    type_name: typing.Text
    @property
    def values(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___PairValue]: ...
    def __init__(self,
        *,
        type_name: typing.Text = ...,
        values: typing.Optional[typing.Iterable[global___PairValue]] = ...,
        ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["type_name",b"type_name","values",b"values"]) -> None: ...
global___NamedTupleValue = NamedTupleValue
