from onnx.backend.base import Backend

class OnnxRuntimeBackend(Backend):
    allowReleasedOpsetsOnly = ...
    @classmethod
    def is_compatible(cls, model, device=..., **kwargs): ...
    @classmethod
    def is_opset_supported(cls, model): ...
    @classmethod
    def supports_device(cls, device): ...
    @classmethod
    def prepare(cls, model, device=..., **kwargs): ...
    @classmethod
    def run_model(cls, model, inputs, device=..., **kwargs): ...
    @classmethod
    def run_node(cls, node, inputs, device=..., outputs_info=..., **kwargs): ...

is_compatible = ...
prepare = ...
run = ...
supports_device = ...
