import logging
from typing import Optional

_lock = ...
_default_handler: Optional[logging.Handler] = ...
log_levels = ...
_default_log_level = ...

def get_log_levels_dict(): ...
def get_logger(name: Optional[str] = ...) -> logging.Logger: ...
def get_verbosity() -> int: ...
def set_verbosity(verbosity: int) -> None: ...
def set_verbosity_info(): ...
def set_verbosity_warning(): ...
def set_verbosity_debug(): ...
def set_verbosity_error(): ...
def disable_default_handler() -> None: ...
def enable_default_handler() -> None: ...
def add_handler(handler: logging.Handler) -> None: ...
def remove_handler(handler: logging.Handler) -> None: ...
def disable_propagation() -> None: ...
def enable_propagation() -> None: ...
def enable_explicit_format() -> None: ...
def reset_format() -> None: ...
