name: Autoformatter
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # run this everyday at 12:00AM UTC
    - cron: "0 0 * * *"
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}
concurrency:
  group: auto-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  BRANCH_NAME: ci/auto
  REPO: bentoml/bentoml
  GIT_AUTHOR_NAME: github-actions[bot]
  GIT_AUTHOR_EMAIL: github-actions[bot]@users.noreply.github.com
jobs:
  format:
    name: "Autoformat check"
    if: github.repository_owner == 'bentoml'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Setup CI
        uses: ./.github/actions/setup-repo
        with:
          python-version: "3.10"
      - name: Setup bufbuild/buf
        uses: bufbuild/buf-setup-action@v1.14.0
        with:
          github_token: ${{ github.token }}
      - name: Install external dependencies
        run: sudo apt-get install -y jq curl
      - name: Tooling
        run: |
          black --config pyproject.toml src tests docs examples
          find src -name "*.pyi" ! -name "*_pb2*" -exec black --pyi --config pyproject.toml {} \;
          isort .
          ruff check src examples tests --fix-only
          buf format --config "${{ github.workspace }}/src/bentoml/grpc/buf.yaml" -w src/bentoml/grpc
          bazel run //:buildfmt
      - name: Meta
        ids: meta
        run: |
          COMMIT_INFO="$(curl "https://api.github.com/repos/${{ env.REPO }}/commits/main")"
          SHA="$(echo $COMMIT_INFO | jq -r ".sha")"
          URL="$(echo $COMMIT_INFO | jq -r ".html_url")"
          DATE="$(date "+%Y-%m-%d %H:%M:%S %Z%z")"

          echo"sha=$SHA" >> $GITHUB_OUTPUT
          echo"url=$URL" >> $GITHUB_OUTPUT
          echo"date=$DATE" >> $GITHUB_OUTPUT
      - name: Generate a PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: "ci: formatter and style"
          commit-message: "style: format and lint (${{ steps.meta.outputs.sha }})"
          body: Follow up from commit ${{ steps.meta.outputs.sha }} [${{ steps.meta.outputs.url
            }}] at ${{ steps.meta.outputs.date }}
          branch-suffix: timestamp
          signoff: true
          delete-branch: true
          reviewers: bentoml/bentoml-reviewers
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          branch: ${{ env.BRANCH_NAME }}
