name: code-quality
on:
  push:
    branches: [main]
    paths-ignore:
      - 'docs/**'
      - 'bazel/**'
      - 'typings/**'
  pull_request:
    paths-ignore:
      - 'docs/**'
      - 'bazel/**'
      - 'typings/**'
  schedule:
    - cron: '0 0 * * 1/2'
env:
  LINES: 200
  COLUMNS: 200
  BENTOML_DO_NOT_TRACK: True
concurrency:
  group: cqa-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}
jobs:
  spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          cache: true
          python-version: '3.11'
          enable-pep582: false
      - name: Install libenchant
        run: sudo apt-get update && sudo apt-get install -y libenchant-2-dev
      - name: Install dependencies
        run: pdm sync -dG docs
      - name: Run spellcheck script
        run: |
          pdm run -v sphinx-build -b spelling ./docs/source ./docs/build || (echo "Failed to run spellcheck. Refer to logs for more details"; exit 1)
