name: framework-on-push

on:
  push:
    branches: [master, bentoml-1.0]
  schedule:
    - cron: '0 0 * * 1/2'

jobs:
  catboost_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_catboost_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  detectron2_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_detectron2_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  easyocr_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_easyocr_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  evalml_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_evalml_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  fastai_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_fastai_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  fasttext_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_fasttext_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  # TODO(aarnphm): add Trax/Flax support

  gluon_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_gluon_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  h2o_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_h2o_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  keras_with_tf1_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.10
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/tensorflow/run_keras_tf1_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  keras_with_tf2_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.10
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/tensorflow/run_keras_tf2_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  lightgbm_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_lightgbm_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  mlflow_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_mlflow_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  onnx_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/onnx/run_onnx_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  onnxmlir_integration_tests:
    runs-on: ubuntu-latest
    container:
      image: onnxmlirczar/onnx-mlir-dev:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/onnx/run_onnxmlir_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  paddle_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_paddle_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  pycaret_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_pycaret_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  pyspark_mllib_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_pyspark_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  pytorch_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_pytorch_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  pytorch_lightning_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Run tests
        run: ./ci/integration/frameworks/run_pytorch_lightning_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  sklearn_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_sklearn_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  spacy_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_spacy_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  statsmodels_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_statsmodels_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  tensorflow_v1_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/tensorflow/run_tf1_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  tensorflow_v2_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/tensorflow/run_tf2_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  transformers_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_transformers_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

  xgboost_integration_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # fetch all tags and branches
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install test dependencies
        run: ./ci/install_test_deps.sh.cmd
      - name: Run tests
        run: ./ci/integration/frameworks/run_xgboost_tests.sh
      - name: Upload test coverage to Codecov
        uses: codecov/codecov-action@v1.0.12

concurrency:
  group: frameworks-on-push-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true
