name: General
on:
  workflow_dispatch:
  schedule:
    # run this everyday at 12:00AM UTC
    - cron: "0 0 * * *"

# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}

env:
  BRANCH_NAME: bazel/lock-requirements
  GIT_AUTHOR_NAME: ${{ github.repository_owner }}
  GIT_AUTHOR_EMAIL: ${{ github.repository_owner }}@users.noreply.github.com

jobs:
  update:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, macos, windows]

    if: "!github.event.repository.fork" # Don't run on fork repository
    name: "Create PR for locking dependencies"
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        uses: ./.github/actions/setup-repo
      - name: Get target lock target
        id: lock
        run: |
          if [ "${{ matrix.os }}" == "ubuntu" ]; then
            target="linux"
          else
            target="${{ matrix.os }}"
          fi
          echo "target=$target" >> $GITHUB_OUTPUT
      - name: Run lock frameworks
        run: |
          bazel run //:pypi.update
          bazel run //:frameworks-${{ steps.lock.output.target }}.update
      - name: Create a Pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          title: "ci: Update bazel lockfiles"
          commit-message: "chore: update lock files"
          branch-suffix: timestamp
          signoff: true
          delete-branch: true
          reviewers: aarnphm
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          branch: ${{ env.BRANCH_NAME }}

  format:
    if: "!github.event.repository.fork" # Don't run on fork repository
    name: "Create PR for running formatter"
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        uses: ./.github/actions/setup-repo
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1.9.0
        with:
          github_token: ${{ github.token }}
      - name: Run tooling
        run: |
          bazel run //:buildfmt
          bazel run //:black -- "${{ github.workspace }}/src"
          bazel run //:black -- --pyi "${{ github.workspace }}/typings" "${{ github.workspace }}/src/bentoml/metrics.pyi"
          bazel run //:isort -- "${{ github.workspace }}/src"
          buf format --config "${{ github.workspace }}/src/bentoml/grpc/buf.yaml" -w src/bentoml/grpc
      - name: Create a Pull request
        uses: peter-evans/create-pull-request@v4
        with:
          base: main
          title: "ci: running formatter and tooling"
          commit-message: "style: format and lint"
          branch-suffix: timestamp
          signoff: true
          delete-branch: true
          reviewers: aarnphm
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          branch: ${{ env.BRANCH_NAME }}
