name: general-admin
on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    # run this everyday at 12:00AM UTC
    - cron: '0 0 * * *'
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#defaultsrun
defaults:
  run:
    shell: bash --noprofile --norc -exo pipefail {0}
concurrency:
  group: general-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
env:
  BRANCH_NAME: bot/style
  GIT_AUTHOR_NAME: ${{ github.repository_owner }}
  GIT_AUTHOR_EMAIL: ${{ github.repository_owner }}@users.noreply.github.com
jobs:
  format:
    name: 'Create a style PR'
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup CI
        uses: ./.github/actions/setup-repo
      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1.9.0
        with:
          github_token: ${{ github.token }}
      - name: Run tooling
        run: |
          pip install -r requirements/dev-requirements.txt

          # bazel BUILD format
          bazel run //:buildfmt
          # Black and isort
          black "${{ github.workspace }}/src"
          black --pyi "${{ github.workspace }}/typings" "${{ github.workspace }}/src/bentoml/metrics.pyi"
          isort "${{ github.workspace }}/src"
          # Ruff fix (if available)
          ruff src docs examples tests --fix
          # Proto files
          buf format --config "${{ github.workspace }}/src/bentoml/grpc/buf.yaml" -w src/bentoml/grpc
      - name: Install jq and curl
        run: sudo apt-get install -y jq curl
      - name: Get infos
        id: meta
        run: |
          COMMIT_INFO="$(curl "https://api.github.com/repos/bentoml/bentoml/commits/main")"
          SHA="$(echo $COMMIT_INFO | jq -r ".sha")"
          URL="$(echo $COMMIT_INFO | jq -r ".html_url")"
          DATE="$(date "+%Y-%m-%d %H:%M:%S %Z%z")"

          echo "sha=$SHA" >> $GITHUB_OUTPUT
          echo "url=$URL" >> $GITHUB_OUTPUT
          echo "date=$DATE" >> $GITHUB_OUTPUT
      - name: Create a PR
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'ci: formatter and style (follow up from ${{ steps.meta.outputs.sha }})'
          commit-message: 'style: format and lint (${{ steps.meta.outputs.sha }})'
          body: Follow up from commit ${{ steps.meta.outputs.sha }} [${{ steps.meta.outputs.url }}] at ${{ steps.meta.outputs.date }}
          branch-suffix: timestamp
          signoff: true
          delete-branch: true
          reviewers: bentoml/bentoml-reviewers
          author: ${{ env.GIT_AUTHOR_NAME }} <${{ env.GIT_AUTHOR_EMAIL }}>
          branch: ${{ env.BRANCH_NAME }}
