# https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/defining-the-mergeability-of-pull-requests/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: ci_fastai

on:
  pull_request:
    paths-ignore:
      - 'requirements/**/*'
      - 'codecov.yml'
      - 'setup.cfg'
      - 'pyproject.toml'
      - '.github/workflow/generated_fastai.yml'
      - bentoml/_internal/runner/**
      - bentoml/_internal/models/**
      - 'bentoml/fastai.py'
      - 'bentoml/_internal/frameworks/fastai.py'
      - 'tests/intergration/frameworks/test_frameworks.py'
      - 'tests/intergration/frameworks/test_fastai_impl.py'

jobs:
  integration_tests_matrix:
    continue-on-error: false
    strategy:
      fail-fast: true
      max-parallel: 4  # since we are supporting 3.7-3.10
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        python-version: [ '3.7', '3.8', '3.9', '3.10' ]

    name: python${{ matrix.python-version }}_intergration_tests_${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
      - run: echo "Skipped"
