name: Slash commands
on:
  repository_dispatch:
    types: [help-command]

jobs:
  display-help-info:
    runs-on: ubuntu-latest
    if:
      github.event_name == 'repository_dispatch' &&
      github.event.client_payload.slash_command.command == 'help'
    steps:
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.event.client_payload.github.payload.issue.number }}
          body: |
            Hello @${{ github.event.client_payload.github.actor }}!
            | Command | Description |
            | ------- | ----------- |
            | /test-e2e-yatai sha="first 7 char of commit sha' | Run Yatai e2e tests |
            | /test-e2e-deployment sha="first 7 char of commit sha" | Run deployment e2e tests |
