name: pytorch_example
channels:
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - torch==1.8.1
    - torchvision==0.9.1
    - mlflow>=1.0
    - protobuf<4.0.0
    - bentoml>=1.0.0rc3
